XtalOpt - API:GlobalSearch::Optimizer Class Reference
GlobalSearch::Optimizer Class Reference
The Optimizer class provides an interface between an OptBase instance and an external optimization engine.
#include <globalsearch/optimizer.h>
Public Slots
virtual bool setData (const QString &identifier, const QVariant &data)
QString localRunCommand () const
Public Member Functions
Optimizer (OptBase *parent, const QString &filename="")
virtual ~Optimizer () override
virtual void readSettings (const QString &filename="")
virtual void writeSettings (const QString &filename="")
virtual QString getIDString () const
virtual bool isReadyToSearch (QString *err)
virtual bool checkIfOutputFileExists (Structure *s, bool *exists)
virtual bool checkForSuccessfulOutput (Structure *s, bool *success)
virtual bool update (Structure *structure)
virtual bool load (Structure *structure)
virtual bool read (Structure *structure, const QString &filename)
virtual QVariant getData (const QString &identifier)
virtual QStringList getTemplateFileNames () const
bool isTemplateFileName (const char *name) const
virtual QHash< QString, QString > getInterpretedTemplates (Structure *s)
virtual QStringList getDataIdentifiers ()
void setLocalRunCommand (const QString &s)
QString stdinFilename () const
QString stdoutFilename () const
QString stderrFilename () const
bool hasDialog ()
virtual QDialog * dialog ()
Public Attributes
QHash< QString, QVariant > m_data
Protected Member Functions
virtual void readDataFromSettings (const QString &filename="")
virtual void writeDataToSettings (const QString &filename="")
Protected Attributes
QStringList m_templates
QString m_completionFilename
QStringList m_completionStrings
QStringList m_outputFilenames
QString m_localRunCommand
QString m_stdinFilename
QString m_stdoutFilename
QString m_stderrFilename
OptBase * m_opt
QString m_idString
Friends
class OptimizerConfigDialog
Detailed Description
The Optimizer class provides an interface between an OptBase instance and an external optimization engine.
Author
David C. Lonie
The Optimizer class standardizes communication between an OptBase instance and an external chemical optimization engine, such as GAMESS, ADF, VASP, etc.
The file contents may be set using the setTemplate, appendTemplate, and removeTemplate functions. These will be passed through the associated OptBase's template interpreter prior to writing.
Once the Optimizer is attached to the OptBase instance and the templates are set, the QueueManager handles all job submission, file writing, and Structure updating automatically.
Definition at line 51 of file optimizer.h.
Constructor & Destructor Documentation
Optimizer()
GlobalSearch::Optimizer::Optimizer (OptBase * parent, const QString & filename = "") explicit
Constructor
Parameters
parent OptBase parent
filename Optional filename to load data from (scheme or resume file)
Definition at line 36 of file optimizer.cpp.
References m_idString, m_stderrFilename, m_stdinFilename, m_stdoutFilename, and readSettings().
~Optimizer()
GlobalSearch::Optimizer::~Optimizer () override virtual
Destructor
Definition at line 93 of file optimizer.cpp.
Member Function Documentation
checkForSuccessfulOutput()
bool GlobalSearch::Optimizer::checkForSuccessfulOutput (Structure * s, bool * success) virtual
Check m_completionFilename for any of the m_completionStrings in the working directory of Structure s. If any are found, success is set to true.
Note
This function uses the argument success to report whether or not m_completionFileName contains any m_completionStrings. The return value indicates whether the file check was performed without errors (e.g. network errors).
Returns
True if the test encountered no errors, false otherwise.
Definition at line 199 of file optimizer.cpp.
References GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::Structure::getGeneration(), GlobalSearch::Structure::getIDNumber(), GlobalSearch::QueueInterface::grepFile(), m_completionFilename, m_completionStrings, m_opt, and GlobalSearch::OptBase::queueInterface().
Referenced by GlobalSearch::LocalQueueInterface::getStatus().
checkIfOutputFileExists()
bool GlobalSearch::Optimizer::checkIfOutputFileExists (Structure * s, bool * exists) virtual
Check if the file m_completionFilename exists in the working directory of Structure s and store the result in exists.
Note
This function uses the argument exists to report whether or not the file exists. The return value indicates whether the file check was performed without errors (e.g. network errors).
Returns
True if the test encountered no errors, false otherwise.
Definition at line 193 of file optimizer.cpp.
References GlobalSearch::QueueInterface::checkIfFileExists(), GlobalSearch::Structure::getCurrentOptStep(), m_completionFilename, m_opt, and GlobalSearch::OptBase::queueInterface().
Referenced by GlobalSearch::LocalQueueInterface::getStatus().
getData()
QVariant GlobalSearch::Optimizer::getData (const QString & identifier) virtual
Get generic data associated with the optimizer.
Parameters
identifier QString identifying the data needed.
Returns
A QVariant version of the generic data.
Definition at line 310 of file optimizer.cpp.
getDataIdentifiers()
virtual QStringList GlobalSearch::Optimizer::getDataIdentifiers () inline virtual
Returns
All strings that identify valid generic data sets.
Definition at line 217 of file optimizer.h.
Referenced by readDataFromSettings(), and writeDataToSettings().
getIDString()
virtual QString GlobalSearch::Optimizer::getIDString () const inline virtual
Returns
A string identifying the Optimizer
Definition at line 96 of file optimizer.h.
References m_idString.
Referenced by readDataFromSettings(), GlobalSearch::OptBase::readOptimizerTemplatesFromSettings(), writeDataToSettings(), and GlobalSearch::OptBase::writeOptimizerTemplatesToSettings().
getInterpretedTemplates()
QHash< QString, QString > GlobalSearch::Optimizer::getInterpretedTemplates (Structure * s) virtual
Get a QHash of the interpreted templates.
Parameters
s The structure whose templates are to be interpreted.
Returns
A QHash of the template filename to its contents.
Definition at line 150 of file optimizer.cpp.
References GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::OptBase::getTemplate(), getTemplateFileNames(), GlobalSearch::QueueInterface::getTemplateFileNames(), GlobalSearch::OptBase::interpretTemplate(), GlobalSearch::Structure::lock(), m_opt, GlobalSearch::OptBase::optimizer(), GlobalSearch::OptBase::queueInterface(), and GlobalSearch::QueueInterface::stopJob().
Referenced by GlobalSearch::QueueInterface::writeInputFiles().
getTemplateFileNames()
virtual QStringList GlobalSearch::Optimizer::getTemplateFileNames () const inline virtual
Returns
All filenames that the optimizer can store templates for.
Definition at line 191 of file optimizer.h.
References m_templates.
Referenced by getInterpretedTemplates(), GlobalSearch::AbstractEditTab::getTemplateNames(), GlobalSearch::OptBase::readOptimizerTemplatesFromSettings(), and GlobalSearch::OptBase::writeOptimizerTemplatesToSettings().
isReadyToSearch()
virtual bool GlobalSearch::Optimizer::isReadyToSearch (QString * err) inline virtual
Check that all mandatory internal variables are set. Check this before starting a search.
Parameters
err String to be overwritten with an error message
Returns
true if all variables are initialized, false otherwise. If false, err will be overwritten with a user-friendly error message.
Definition at line 108 of file optimizer.h.
isTemplateFileName()
bool GlobalSearch::Optimizer::isTemplateFileName (const char * name) const inline
Check if a name is a template file name.
Parameters
name The template file name.
Returns
True if "name" is a template file name. False otherwise.
Definition at line 200 of file optimizer.h.
References m_templates.
load()
bool GlobalSearch::Optimizer::load (Structure * structure) virtual
Update the Structure from the files in the Structure's local file path.
Parameters
structure Structure to be updated.
Returns
True if successful, false otherwise.
See also
update
read
Definition at line 263 of file optimizer.cpp.
References GlobalSearch::Structure::fileName(), GlobalSearch::Structure::lock(), m_opt, m_outputFilenames, read(), and GlobalSearch::OptBase::warning().
localRunCommand
QString GlobalSearch::Optimizer::localRunCommand () const inline slot
Command line used in local execution
Details given in m_localRunCommand.
See also
stdinFilename
stdoutFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 246 of file optimizer.h.
References m_localRunCommand.
Referenced by GlobalSearch::LocalQueueInterface::startJob(), and GlobalSearch::OptBase::writeOptimizerTemplatesToSettings().
read()
bool GlobalSearch::Optimizer::read (Structure * structure, const QString & filename) virtual
Update the Structure from the specified filename.
Parameters
structure Structure to be updated
filename Filename to read
Returns
True if successful, false otherwise.
See also
update
load
Definition at line 284 of file optimizer.cpp.
References GlobalSearch::Structure::getIDString(), m_idString, and GlobalSearch::Formats::read().
Referenced by load(), and update().
readDataFromSettings()
void GlobalSearch::Optimizer::readDataFromSettings (const QString & filename = "") protected virtual
Parameters
filename Scheme or state file from which to load all generic data values in m_data
Definition at line 106 of file optimizer.cpp.
References getDataIdentifiers(), GlobalSearch::OptBase::getIDString(), getIDString(), m_opt, and GlobalSearch::OptBase::optimizerIndex().
Referenced by readSettings().
readSettings()
void GlobalSearch::Optimizer::readSettings (const QString & filename = "") virtual
Read optimizer data from file (.scheme or .state). If called without an argument, this function does nothing, i.e. it will not read optimizer data from the system config file.
Parameters
filename Scheme or state file to load data from.
See also
writeSettings
Definition at line 97 of file optimizer.cpp.
References readDataFromSettings().
Referenced by Optimizer().
setData
bool GlobalSearch::Optimizer::setData (const QString & identifier, const QVariant & data) virtual slot
Set a generic data entry.
Parameters
identifier A valid data identifier
data QVariant of data
Returns
True if successful, false otherwise.
See also
getData
getDataIdentifiers
Definition at line 302 of file optimizer.cpp.
setLocalRunCommand()
void GlobalSearch::Optimizer::setLocalRunCommand (const QString & s) inline
Set the local run command.
Details given in m_localRunCommand.
Definition at line 253 of file optimizer.h.
References m_localRunCommand.
Referenced by GlobalSearch::OptBase::readOptimizerTemplatesFromSettings().
stderrFilename()
QString GlobalSearch::Optimizer::stderrFilename () const inline
Filename for standard error
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stdoutFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 298 of file optimizer.h.
References m_stderrFilename.
stdinFilename()
QString GlobalSearch::Optimizer::stdinFilename () const inline
Filename for standard input
Details given in m_localRunCommand.
See also
localRunCommand
stdoutFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 268 of file optimizer.h.
References m_stdinFilename.
stdoutFilename()
QString GlobalSearch::Optimizer::stdoutFilename () const inline
Filename for standard output
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 283 of file optimizer.h.
References m_stdoutFilename.
update()
bool GlobalSearch::Optimizer::update (Structure * structure) virtual
Copy the files from the Structure's remote path to the local path, and then update the Structure based on the optimization results.
Parameters
structure Structure to be updated.
Returns
True if successful, false otherwise.
See also
load
read
Definition at line 224 of file optimizer.cpp.
References GlobalSearch::Structure::fileName(), GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::Structure::getIDString(), GlobalSearch::Structure::lock(), m_opt, m_outputFilenames, GlobalSearch::QueueInterface::prepareForStructureUpdate(), GlobalSearch::OptBase::queueInterface(), read(), GlobalSearch::Structure::setJobID(), GlobalSearch::Structure::stopOptTimer(), and GlobalSearch::OptBase::warning().
writeDataToSettings()
void GlobalSearch::Optimizer::writeDataToSettings (const QString & filename = "") protected virtual
Parameters
filename Scheme or state file in which to write all generic data values in m_data
Definition at line 133 of file optimizer.cpp.
References getDataIdentifiers(), GlobalSearch::OptBase::getIDString(), getIDString(), m_opt, and GlobalSearch::OptBase::optimizerIndex().
Referenced by writeSettings().
writeSettings()
void GlobalSearch::Optimizer::writeSettings (const QString & filename = "") virtual
Write optimizer data to file (.scheme or .state). If called without an argument, this function does nothing, i.e. it will not write optimizer data to the system config file.
Parameters
filename Scheme or state file to write data to.
See also
readSettings
Definition at line 124 of file optimizer.cpp.
References writeDataToSettings().
Friends And Related Symbol Documentation
OptimizerConfigDialog
friend class OptimizerConfigDialog friend
Definition at line 56 of file optimizer.h.
Member Data Documentation
m_completionFilename
QString GlobalSearch::Optimizer::m_completionFilename protected
File to check if optimization has complete successfully.
See also
m_completionString
Definition at line 346 of file optimizer.h.
Referenced by checkForSuccessfulOutput(), and checkIfOutputFileExists().
m_completionStrings
QStringList GlobalSearch::Optimizer::m_completionStrings protected
String to search for in m_completionFilename when checking if optimization has complete successfully.
See also
m_completionFilename.
Definition at line 353 of file optimizer.h.
Referenced by checkForSuccessfulOutput().
m_data
QHash<QString, QVariant> GlobalSearch::Optimizer::m_data
Definition at line 58 of file optimizer.h.
m_idString
QString GlobalSearch::Optimizer::m_idString protected
Unique identification string for this Optimizer.
Definition at line 450 of file optimizer.h.
Referenced by getIDString(), Optimizer(), and read().
m_localRunCommand
QString GlobalSearch::Optimizer::m_localRunCommand protected
Commandline instruction to run this program locally
Three common scenarios:
VASP-esque: $ vasp Runs in working directory reading from predefined input filenames (ie. POSCAR). Set m_localRunCommand="vasp", and m_stdinFilename=m_stdoutFilename=m_stderrFilename="";
GULP-esque: $ gulp < job.gin 1>job.got 2>job.err
Runs in working directory using redirection to specify input/output. Set m_localRunCommand="gulp", m_stdinFilename="job.gin", m_stdoutFilename="job.got", m_stderrFilename="job.err".
MOPAC-esque: $ mopac job
Runs in working directory, specifying either an input filename or a base name. In both cases, put the entire command line into m_localRunCommand, ="mopac job", m_stdinFilename=m_stdoutFilename=m_stderrFilename=""
Stdin/out/err is not used (="") by default.
See also
localRunCommand
stdinFilename
stdoutFilename
stderrFilename
m_stdinFilename
m_stdoutFilename
m_stderrFilename
Definition at line 395 of file optimizer.h.
Referenced by localRunCommand(), and setLocalRunCommand().
m_opt
OptBase* GlobalSearch::Optimizer::m_opt protected
Cached pointer to the associated OptBase instance
Definition at line 445 of file optimizer.h.
Referenced by checkForSuccessfulOutput(), checkIfOutputFileExists(), dialog(), getInterpretedTemplates(), load(), readDataFromSettings(), update(), and writeDataToSettings().
m_outputFilenames
QStringList GlobalSearch::Optimizer::m_outputFilenames protected
List of filenames to check when updating structure (will be checked in order of index).
Definition at line 359 of file optimizer.h.
Referenced by load(), and update().
m_stderrFilename
QString GlobalSearch::Optimizer::m_stderrFilename protected
Filename for standard error
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stdoutFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stdoutFilename
Definition at line 440 of file optimizer.h.
Referenced by Optimizer(), and stderrFilename().
m_stdinFilename
QString GlobalSearch::Optimizer::m_stdinFilename protected
Filename for standard input
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stdoutFilename
stderrFilename
m_localRunCommand
m_stdoutFilename
m_stderrFilename
Definition at line 410 of file optimizer.h.
Referenced by Optimizer(), and stdinFilename().
m_stdoutFilename
QString GlobalSearch::Optimizer::m_stdoutFilename protected
Filename for standard output
Details given in m_localRunCommand.
See also
localRunCommand
stdinFilename
stdoutFilename
stderrFilename
m_localRunCommand
m_stdinFilename
m_stderrFilename
Definition at line 425 of file optimizer.h.
Referenced by Optimizer(), and stdoutFilename().
m_templates
QStringList GlobalSearch::Optimizer::m_templates protected
Store generic data types. This is not commonly used, see XtalOpt's VASPOptimizer for an example where it is used to store information about pseudopotentials. The names of templates that this optimizer utilizes.
Definition at line 340 of file optimizer.h.
Referenced by getTemplateFileNames(), and isTemplateFileName().
The documentation for this class was generated from the following files:
src/globalsearch/optimizer.h
src/globalsearch/optimizer.cpp