XtalOpt - API:GlobalSearch::Tracker Class Reference
GlobalSearch::Tracker Class Reference
The Tracker contains a thread-safe list of unique Structures.
#include <globalsearch/tracker.h>
Signals
void newStructureAdded (GlobalSearch::Structure *s)
void structureCountChanged (int c)
Public Member Functions
Tracker (QObject *parent=0)
virtual ~Tracker () override
void lockForRead ()
void lockForWrite ()
void unlock ()
QReadWriteLock * rwLock ()
QList< Structure * > * list ()
Structure * at (int i)
bool append (QList< Structure * > s)
bool append (Structure *s)
bool popFirst (Structure *&s)
bool remove (Structure *s)
bool contains (Structure *s)
int size ()
void reset ()
void deleteAllStructures ()
Detailed Description
The Tracker contains a thread-safe list of unique Structures.
Author
David C. Lonie
In simplest terms, the Tracker class is a list of Structures. It provides convenience functions and signals to facilitate access.
The Tracker can be used for storage of all Structures generated in a search, or as a FIFO buffer for pending operations by using the append() and popFirst() functions.
If you wish to not use the convenience functions, it is possible to access the list of Structures through list() and the mutex through rwLock(), lockForRead(), lockForWrite(), and unlock().
Definition at line 41 of file tracker.h.
Constructor & Destructor Documentation
Tracker()
GlobalSearch::Tracker::Tracker (QObject * parent = 0)
Constructor.
Parameters
parent The object parent.
Definition at line 27 of file tracker.cpp.
~Tracker()
GlobalSearch::Tracker::~Tracker () override virtual
Destructor.
Definition at line 32 of file tracker.cpp.
References lockForWrite().
Member Function Documentation
append() [1/2]
bool GlobalSearch::Tracker::append (QList< Structure * > s)
Parameters
s A list of Structures to append to the Tracker
Returns
true if all Structures were not contained in the list, false if any were already present.
Note
If the Structure is already present, it will not be added again.
The Structures are compared using pointer values
Definition at line 37 of file tracker.cpp.
References append().
Referenced by append(), GlobalSearch::QueueManager::appendToJobStartTracker(), GlobalSearch::QueueManager::checkPopulation(), and GlobalSearch::QueueManager::unlockForNaming().
append() [2/2]
bool GlobalSearch::Tracker::append (Structure * s)
Parameters
s A Structures to append to the Tracker
Returns
true if the Structure was not contained in the list, false if it were already present.
Note
If the Structure is already present, it will not be added again.
The Structures are compared using pointer values
Definition at line 47 of file tracker.cpp.
References newStructureAdded(), and structureCountChanged().
at()
Structure * GlobalSearch::Tracker::at (int i) inline
Parameters
i The index of the Structure desired
Returns
A pointer to the Structure at index i
Definition at line 87 of file tracker.h.
Referenced by GlobalSearch::QueueManager::checkPopulation().
contains()
bool GlobalSearch::Tracker::contains (Structure * s)
Test if a Structure is in the Tracker's list.
Parameters
s The Structure to check.
Returns
True if operation was successful, false if not (i.e. Structure was not in list).
Definition at line 77 of file tracker.cpp.
Referenced by GlobalSearch::OptBase::_finishHardnessCalculation().
deleteAllStructures()
void GlobalSearch::Tracker::deleteAllStructures ()
Remove and delete from memory all Structures from the list.
Definition at line 94 of file tracker.cpp.
References GlobalSearch::Structure::lock(), and structureCountChanged().
Referenced by GlobalSearch::OptBase::reset(), and GlobalSearch::AbstractDialog::resumeSession_().
list()
QList< Structure * > * GlobalSearch::Tracker::list () inline
Returns
The Tracker's Structure list
Definition at line 81 of file tracker.h.
Referenced by GlobalSearch::QueueManager::checkExit(), GlobalSearch::QueueManager::checkPopulation(), GlobalSearch::QueueManager::getAllDuplicateStructures(), GlobalSearch::QueueManager::getAllOptimizedStructures(), GlobalSearch::QueueManager::getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit(), GlobalSearch::QueueManager::getAllRunningStructures(), GlobalSearch::QueueManager::getAllStructures(), GlobalSearch::QueueManager::getAllSupercellStructures(), GlobalSearch::QueueManager::lockForNaming(), and GlobalSearch::OptBase::save().
lockForRead()
void GlobalSearch::Tracker::lockForRead () inline
Sets a read lock on the Tracker's mutex.
Definition at line 61 of file tracker.h.
Referenced by GlobalSearch::QueueManager::getAllDuplicateStructures(), GlobalSearch::QueueManager::getAllOptimizedStructures(), GlobalSearch::QueueManager::getAllRunningStructures(), GlobalSearch::QueueManager::getAllStructures(), GlobalSearch::QueueManager::getAllSupercellStructures(), and GlobalSearch::QueueManager::lockForNaming().
lockForWrite()
void GlobalSearch::Tracker::lockForWrite () inline
Sets a write lock on the Tracker's mutex.
Definition at line 66 of file tracker.h.
Referenced by GlobalSearch::QueueManager::addManualStructureRequest(), GlobalSearch::QueueManager::appendToJobStartTracker(), GlobalSearch::OptBase::reset(), GlobalSearch::AbstractDialog::resumeSession_(), GlobalSearch::QueueManager::unlockForNaming(), and ~Tracker().
newStructureAdded
void GlobalSearch::Tracker::newStructureAdded (GlobalSearch::Structure * s) signal
Signal emitted when a new Structure is added to the Tracker.
Parameters
s A Pointer to the new Structure.
Referenced by append(), and GlobalSearch::OptBase::OptBase().
popFirst()
bool GlobalSearch::Tracker::popFirst (Structure *& s)
Remove and return the first Structure in the Tracker's list. Useful for creating a FIFO buffer.
Parameters
s Becomes the Structure at index 0 of the Tracker's list.
Returns
True if operation was successful, false if not (i.e. the list is empty).
Definition at line 58 of file tracker.cpp.
References structureCountChanged().
Referenced by GlobalSearch::QueueManager::startJob().
remove()
bool GlobalSearch::Tracker::remove (Structure * s)
Remove a Structure in the Tracker's list.
Parameters
s The Structure to remove.
Returns
True if operation was successful, false if not (i.e. Structure was not in list).
Note
This does not delete the Structure from memory.
Definition at line 68 of file tracker.cpp.
References structureCountChanged().
Referenced by GlobalSearch::QueueManager::checkPopulation().
reset()
void GlobalSearch::Tracker::reset ()
Remove all Structures from the list.
Note
This does not delete the Structures from memory.
Definition at line 88 of file tracker.cpp.
References structureCountChanged().
Referenced by GlobalSearch::OptBase::reset().
rwLock()
QReadWriteLock * GlobalSearch::Tracker::rwLock () inline
Returns
The Tracker's read-write mutex
Definition at line 76 of file tracker.h.
Referenced by GlobalSearch::OptBase::_finishHardnessCalculation(), GlobalSearch::QueueManager::checkExit(), GlobalSearch::QueueManager::checkPopulation(), GlobalSearch::QueueManager::getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit(), GlobalSearch::OptBase::resubmitUnfinishedHardnessCalcs(), and GlobalSearch::OptBase::save().
size()
int GlobalSearch::Tracker::size ()
Returns
The number of Structures in the Tracker's list.
Definition at line 83 of file tracker.cpp.
Referenced by GlobalSearch::QueueManager::checkPopulation().
structureCountChanged
void GlobalSearch::Tracker::structureCountChanged (int c) signal
Signal emitted when then number of Structures in the Tracker changes.
Parameters
c The number of new Structure in the Tracker.
Referenced by append(), deleteAllStructures(), popFirst(), remove(), and reset().
unlock()
void GlobalSearch::Tracker::unlock () inline
Unlock the Tracker's mutex.
Definition at line 71 of file tracker.h.
Referenced by GlobalSearch::QueueManager::addManualStructureRequest(), GlobalSearch::QueueManager::appendToJobStartTracker(), GlobalSearch::QueueManager::getAllDuplicateStructures(), GlobalSearch::QueueManager::getAllOptimizedStructures(), GlobalSearch::QueueManager::getAllRunningStructures(), GlobalSearch::QueueManager::getAllStructures(), GlobalSearch::QueueManager::getAllSupercellStructures(), GlobalSearch::OptBase::reset(), GlobalSearch::AbstractDialog::resumeSession_(), and GlobalSearch::QueueManager::unlockForNaming().
The documentation for this class was generated from the following files:
src/globalsearch/tracker.h
src/globalsearch/tracker.cpp