XtalOpt - API:GlobalSearch::QueueManager Class Reference
GlobalSearch::QueueManager Class Reference
The QueueManager monitors the running jobs and updates Structure status.
#include <globalsearch/queuemanager.h>
Public Slots
void reset ()
void killStructure (Structure *s)
void appendToJobStartTracker (Structure *s)
void addManualStructureRequest (int requests=1)
QList< Structure * > getAllRunningStructures ()
QList< Structure * > getAllOptimizedStructures ()
QList< Structure * > getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit ()
QList< Structure * > getAllDuplicateStructures ()
QList< Structure * > getAllSupercellStructures ()
QList< Structure * > getAllStructures ()
QList< Structure * > lockForNaming ()
void unlockForNaming (Structure *s=0)
Signals
void readyForFeatureCalculations (GlobalSearch::Structure *s)
void movedToQMThread ()
void structureStarted (GlobalSearch::Structure *s)
void structureSubmitted (GlobalSearch::Structure *s)
void structureKilled (GlobalSearch::Structure *s)
void structureUpdated (GlobalSearch::Structure *s)
void structureFinished (GlobalSearch::Structure *s)
void needNewStructure ()
void newStatusOverview (int optimized, int running, int failing)
Public Member Functions
QueueManager (QThread *thread, OptBase *parent)
virtual ~QueueManager ()
Protected Slots
void updateStructureFeatureStatus (Structure *s)
void checkLoop ()
void addStructureToSubmissionQueue (GlobalSearch::Structure *s, int optStep)
void addStructureToSubmissionQueue (GlobalSearch::Structure *s)
void moveToQMThread ()
void setupConnections ()
Protected Member Functions
void updateQueue ()
void updateStructure (Structure *s)
void startJob ()
void stopJob (Structure *s)
void checkPopulation ()
void checkExit ()
void checkRunning ()
void handleOptimizedStructure (Structure *s)
void handleStepOptimizedStructure (Structure *s)
void handleWaitingForOptimizationStructure (Structure *s)
void handleInProcessStructure (Structure *s)
void handleEmptyStructure (Structure *s)
void handleUpdatingStructure (Structure *s)
void handleErrorStructure (Structure *s)
void handleSubmittedStructure (Structure *s)
void handleKilledStructure (Structure *s)
void handleRemovedStructure (Structure *s)
void handleDuplicateStructure (Structure *s)
void handleSupercellStructure (Structure *s)
void handleRestartStructure (Structure *s)
void handleRetainFeature (Structure *s)
void handleDismissFeature (Structure *s)
void handleFailFeature (Structure *s)
Protected Attributes
OptBase * m_opt
Cached pointer to main optbase class.
QThread * m_thread
Pointer to the thread where the queuemanager lives.
Tracker * m_tracker
Convenience pointer to m_opt->tracker()
Tracker m_runningTracker
Tracks which structures are currently running.
Tracker m_jobStartTracker
Tracks which structures are queued to be submitted.
Tracker m_newStructureTracker
int m_requestedStructures
Number of structure requests pending.
bool m_isDestroying
Boolean set to true while the destructor is running.
QDateTime * m_lastSubmissionTimeStamp
Used to throttle job submissions.
Detailed Description
The QueueManager monitors the running jobs and updates Structure status.
Author
David C. Lonie
The QueueManager creates a local queue and monitoring system control the submission of Structures to an optimization engine or queue.
For basic usage, connect the needNewStructure() signal to slot that will generate a new Structure and submit it the following way:
// lockForNaming() returns a list of all structures that the main
// tracker is aware of. It also locks a naming mutex to prevent
// simultaneous naming of Structures, avoiding duplicate
// Structure indices, ID numbers, etc.
QList<Structure*> allStructures = m_queue->lockForNaming();
// Check the Structures in allStructures to determine the next
// available name. The follow code uses a generation and ID number
// for an evolutionary/genetic algorithm. Other methods may only set
// the ID number. (note that the generation number is set already
// in the following example).
Structure *structure;
uint id = 1;
for (int j = 0; j < allStructures.size(); j++) {
structure = allStructures.at(j);
structure->lock().lockForRead();
if (structure->getGeneration() == generation &&
    structure->getIDNumber() >= id) {
  id = structure->getIDNumber() + 1;
}
structure->lock().unlock();
}
// Assign data to structure (created elsewhere)
QWriteLocker locker (newStructure->lock());
newStructure->setIDNumber(id);
newStructure->setGeneration(generation);
newStructure->setParents(parents);
// Determine, create, and assign paths
QString id_s, gen_s, locpath_s, rempath_s;
id_s.sprintf("%05d",structure->getIDNumber());
gen_s.sprintf("%05d",structure->getGeneration());
locpath_s = filePath + "/" + gen_s + "x" + id_s + "/";
rempath_s = rempath + "/" + gen_s + "x" + id_s + "/";
QDir dir (locpath_s);
if (!dir.exists()) {
if (!dir.mkpath(locpath_s)) {
  // Output error
}
}
newStructure->setFileName(locpath_s);
newStructure->setRempath(rempath_s);
newStructure->setCurrentOptStep(0);
newStructure->findSpaceGroup();
// unlockForNaming(Structure*) unlocks the naming mutex and
// begins processing the structure that is passed.
m_queue->unlockForNaming(newStructure);
Most functions in this class do not need to be called as they are automatically called when needed. Check the source if in doubt.
Definition at line 93 of file queuemanager.h.
Constructor & Destructor Documentation
QueueManager()
GlobalSearch::QueueManager::QueueManager (QThread * thread, OptBase * parent) explicit
Constructor.
Parameters
thread A QThread instance to run in
parent The OptBase class the QueueManager uses
Definition at line 66 of file queuemanager.cpp.
References moveToQMThread().
~QueueManager()
GlobalSearch::QueueManager::~QueueManager () virtual
Destructor.
Definition at line 74 of file queuemanager.cpp.
References m_isDestroying, m_lastSubmissionTimeStamp, and m_requestedStructures.
Member Function Documentation
addManualStructureRequest
void GlobalSearch::QueueManager::addManualStructureRequest (int requests = 1) slot
Add a structure request. This must be called every time a structure is added via unlockForNaming(), and must be called first. This will not actually request the structure, it is only used for internal bookkeeping.
Note
The mutex of m_tracker is locked while incrementing the request counter.
Definition at line 1412 of file queuemanager.cpp.
References GlobalSearch::Tracker::lockForWrite(), m_requestedStructures, m_tracker, and GlobalSearch::Tracker::unlock().
addStructureToSubmissionQueue [1/2]
void GlobalSearch::QueueManager::addStructureToSubmissionQueue (GlobalSearch::Structure * s) inline protected slot
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Writes the input files for the optimization process and queues the Structure to be submitted for optimization at its current optStep.
Parameters
s The Structure to be submitted
Definition at line 316 of file queuemanager.h.
References addStructureToSubmissionQueue().
addStructureToSubmissionQueue [2/2]
void GlobalSearch::QueueManager::addStructureToSubmissionQueue (GlobalSearch::Structure * s, int optStep) protected slot
Writes the input files for the optimization process and queues the Structure to be submitted for optimization.
Parameters
s The Structure to be submitted
optStep The optStep to perform. s->currentOptStep is used if optStep==0.
Definition at line 1145 of file queuemanager.cpp.
Referenced by addStructureToSubmissionQueue(), and setupConnections().
appendToJobStartTracker
void GlobalSearch::QueueManager::appendToJobStartTracker (Structure * s) slot
Appends a Structure to m_jobStartTracker. This should not be used unless resuming a session, and then only for structures that are marked Structure::WaitingForOptimization.
All other cases should use prepareStructureForSubmission(Structure*)
Parameters
s The Structure to be appended
See also
prepareStructureForSubmission
Definition at line 1419 of file queuemanager.cpp.
References GlobalSearch::Tracker::append(), GlobalSearch::Tracker::lockForWrite(), m_jobStartTracker, and GlobalSearch::Tracker::unlock().
checkExit()
void GlobalSearch::QueueManager::checkExit () protected
Check the conditions for soft/hard exit. For a soft exit, checks for no running/pending jobs and quit with a delay. For a hard exit, the acting function will be called for an immediate quit.
Definition at line 435 of file queuemanager.cpp.
References GlobalSearch::OptBase::cutoff, GlobalSearch::Structure::Duplicate, GlobalSearch::Structure::FeatureDismiss, GlobalSearch::Structure::FeatureFail, GlobalSearch::Structure::getStatus(), GlobalSearch::Structure::Killed, GlobalSearch::Tracker::list(), GlobalSearch::Structure::lock(), GlobalSearch::OptBase::m_hardExit, m_opt, GlobalSearch::OptBase::m_softExit, m_tracker, GlobalSearch::Structure::Optimized, GlobalSearch::OptBase::performTheExit(), GlobalSearch::Structure::Removed, GlobalSearch::Tracker::rwLock(), GlobalSearch::Structure::Supercell, and GlobalSearch::OptBase::warning().
Referenced by checkLoop().
checkLoop
void GlobalSearch::QueueManager::checkLoop () protected slot
This is called automatically when the QueueManager is started. This function sets up a simple event loop that will run checkPopulation and checkRunning regularly.
Definition at line 197 of file queuemanager.cpp.
References checkExit(), checkLoop(), checkPopulation(), checkRunning(), GlobalSearch::OptBase::isStarting, m_opt, m_thread, GlobalSearch::OptBase::readOnly, GlobalSearch::OptBase::readRuntimeOptions(), and GlobalSearch::OptBase::usingGUI().
Referenced by checkLoop(), and setupConnections().
checkPopulation()
void GlobalSearch::QueueManager::checkPopulation () protected
Check all Structures in the main Tracker and assign them to other trackers as needed (runningTracker, etc.).
If more structures are needed, they are requested in this function by emitting needNewStructure().
This function also submits new structures to the optimization engine if needed.
Also emits newStatusOverview for a summary of the queue's status.
See also
newStatusOverview
needNewStructure
Definition at line 219 of file queuemanager.cpp.
References GlobalSearch::Tracker::append(), GlobalSearch::Tracker::at(), GlobalSearch::OptBase::contStructs, GlobalSearch::OptBase::cutoff, GlobalSearch::Structure::Duplicate, GlobalSearch::Structure::FeatureCalculation, GlobalSearch::Structure::FeatureDismiss, GlobalSearch::Structure::FeatureFail, GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::Structure::getFailCount(), GlobalSearch::Structure::getStatus(), GlobalSearch::Structure::InProcess, GlobalSearch::Structure::Killed, GlobalSearch::OptBase::limitRunningJobs, GlobalSearch::Tracker::list(), GlobalSearch::Structure::lock(), m_jobStartTracker, m_lastSubmissionTimeStamp, m_newStructureTracker, m_opt, m_requestedStructures, m_runningTracker, m_tracker, needNewStructure(), newStatusOverview(), GlobalSearch::Structure::Optimized, GlobalSearch::OptBase::queueInterface(), GlobalSearch::Tracker::remove(), GlobalSearch::Structure::Removed, GlobalSearch::Tracker::rwLock(), GlobalSearch::Tracker::size(), startJob(), GlobalSearch::Structure::Submitted, GlobalSearch::Structure::Supercell, and GlobalSearch::OptBase::testingMode.
Referenced by checkLoop().
checkRunning()
void GlobalSearch::QueueManager::checkRunning () protected
Monitors the Structures in getAllRunningStructures() and updates their statuses if they've changed.
Note
Do note call this function directly; it is called automatically by the checkLoop function
Definition at line 332 of file queuemanager.cpp.
References GlobalSearch::Structure::Duplicate, GlobalSearch::Structure::Empty, GlobalSearch::Structure::Error, GlobalSearch::Structure::FeatureCalculation, GlobalSearch::Structure::FeatureDismiss, GlobalSearch::Structure::FeatureFail, GlobalSearch::Structure::FeatureRetain, getAllRunningStructures(), GlobalSearch::Structure::getStatus(), handleDismissFeature(), handleDuplicateStructure(), handleEmptyStructure(), handleErrorStructure(), handleFailFeature(), handleInProcessStructure(), handleKilledStructure(), handleRemovedStructure(), handleRestartStructure(), handleRetainFeature(), handleStepOptimizedStructure(), handleSubmittedStructure(), handleSupercellStructure(), handleUpdatingStructure(), handleWaitingForOptimizationStructure(), GlobalSearch::Structure::InProcess, GlobalSearch::Structure::Killed, GlobalSearch::Structure::lock(), m_thread, GlobalSearch::Structure::Optimized, GlobalSearch::Structure::Removed, GlobalSearch::Structure::Restart, GlobalSearch::Structure::StepOptimized, GlobalSearch::Structure::Submitted, GlobalSearch::Structure::Supercell, GlobalSearch::Structure::Updating, and GlobalSearch::Structure::WaitingForOptimization.
Referenced by checkLoop().
getAllDuplicateStructures
QList< Structure * > GlobalSearch::QueueManager::getAllDuplicateStructures () slot
Returns
All Structures in m_tracker with status Structure::Duplicate.
Definition at line 1289 of file queuemanager.cpp.
References GlobalSearch::Structure::Duplicate, GlobalSearch::Structure::getStatus(), GlobalSearch::Tracker::list(), GlobalSearch::Structure::lock(), GlobalSearch::Tracker::lockForRead(), m_tracker, and GlobalSearch::Tracker::unlock().
Referenced by GlobalSearch::OptBase::resubmitUnfinishedHardnessCalcs().
getAllOptimizedStructures
QList< Structure * > GlobalSearch::QueueManager::getAllOptimizedStructures () slot
Returns
All Structures in m_tracker with status Structure::Optimized.
Definition at line 1238 of file queuemanager.cpp.
References GlobalSearch::Structure::getStatus(), GlobalSearch::Tracker::list(), GlobalSearch::Structure::lock(), GlobalSearch::Tracker::lockForRead(), m_tracker, GlobalSearch::Structure::Optimized, and GlobalSearch::Tracker::unlock().
Referenced by GlobalSearch::OptBase::resubmitUnfinishedHardnessCalcs().
getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit
QList< Structure * > GlobalSearch::QueueManager::getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit () slot
Returns
All Structures in m_tracker with status Structure::Optimized or Structure::Supercell. Note that duplicates of a supercell at a particular formula unit are not included. Hence the "OneSupercellCopy." This function was chosen because of its usefulness in some parts of the program.
Definition at line 1255 of file queuemanager.cpp.
References GlobalSearch::Structure::getStatus(), GlobalSearch::Structure::getSupercellString(), GlobalSearch::Tracker::list(), GlobalSearch::Structure::lock(), m_tracker, GlobalSearch::Structure::Optimized, GlobalSearch::Tracker::rwLock(), and GlobalSearch::Structure::Supercell.
getAllRunningStructures
QList< Structure * > GlobalSearch::QueueManager::getAllRunningStructures () slot
Returns
All Structures in m_runningTracker
Definition at line 1227 of file queuemanager.cpp.
References GlobalSearch::Tracker::list(), GlobalSearch::Tracker::lockForRead(), m_newStructureTracker, m_runningTracker, and GlobalSearch::Tracker::unlock().
Referenced by checkRunning().
getAllStructures
QList< Structure * > GlobalSearch::QueueManager::getAllStructures () slot
Returns
All Structures in m_tracker and m_startPendingTracker
Definition at line 1321 of file queuemanager.cpp.
References GlobalSearch::Tracker::list(), GlobalSearch::Tracker::lockForRead(), m_newStructureTracker, m_tracker, and GlobalSearch::Tracker::unlock().
Referenced by GlobalSearch::OptBase::performTheExit().
getAllSupercellStructures
QList< Structure * > GlobalSearch::QueueManager::getAllSupercellStructures () slot
Returns
All Structures in m_tracker with status Structure::Supercell.
Definition at line 1305 of file queuemanager.cpp.
References GlobalSearch::Structure::getStatus(), GlobalSearch::Tracker::list(), GlobalSearch::Structure::lock(), GlobalSearch::Tracker::lockForRead(), m_tracker, GlobalSearch::Structure::Supercell, and GlobalSearch::Tracker::unlock().
Referenced by GlobalSearch::OptBase::resubmitUnfinishedHardnessCalcs().
handleDismissFeature()
void GlobalSearch::QueueManager::handleDismissFeature (Structure * s) protected
Perform actions on a structure dismissed by a filtering feature
Parameters
s Structure whose features/aflow-hardness is calculated
Definition at line 780 of file queuemanager.cpp.
Referenced by checkRunning().
handleDuplicateStructure()
void GlobalSearch::QueueManager::handleDuplicateStructure (Structure * s) protected
Perform actions on the Duplicate Structure s.
Parameters
s Structure of interest
Definition at line 1020 of file queuemanager.cpp.
Referenced by checkRunning().
handleEmptyStructure()
void GlobalSearch::QueueManager::handleEmptyStructure (Structure * s) protected
Perform actions on the Empty Structure s.
Parameters
s Structure of interest
Definition at line 851 of file queuemanager.cpp.
Referenced by checkRunning().
handleErrorStructure()
void GlobalSearch::QueueManager::handleErrorStructure (Structure * s) protected
Perform actions on the Error'd Structure s.
Parameters
s Structure of interest
Definition at line 861 of file queuemanager.cpp.
Referenced by checkRunning().
handleFailFeature()
void GlobalSearch::QueueManager::handleFailFeature (Structure * s) protected
Perform actions on a structure failed in feature calculation
Parameters
s Structure whose features/aflow-hardness is calculated
Definition at line 745 of file queuemanager.cpp.
Referenced by checkRunning().
handleInProcessStructure()
void GlobalSearch::QueueManager::handleInProcessStructure (Structure * s) protected
Perform actions on the InProcess Structure s.
Parameters
s Structure of interest
Definition at line 484 of file queuemanager.cpp.
Referenced by checkRunning().
handleKilledStructure()
void GlobalSearch::QueueManager::handleKilledStructure (Structure * s) protected
Perform actions on the Killed Structure s.
Parameters
s Structure of interest
Definition at line 982 of file queuemanager.cpp.
Referenced by checkRunning(), and handleRemovedStructure().
handleOptimizedStructure()
void GlobalSearch::QueueManager::handleOptimizedStructure (Structure * s) protected
Perform actions on the Optimized Structure s.
Parameters
s Structure of interest
Definition at line 541 of file queuemanager.cpp.
handleRemovedStructure()
void GlobalSearch::QueueManager::handleRemovedStructure (Structure * s) protected
Perform actions on the Removed Structure s.
Parameters
s Structure of interest
Definition at line 1015 of file queuemanager.cpp.
References handleKilledStructure().
Referenced by checkRunning().
handleRestartStructure()
void GlobalSearch::QueueManager::handleRestartStructure (Structure * s) protected
Perform actions on the Restart'ing Structure s.
Parameters
s Structure of interest
Definition at line 1080 of file queuemanager.cpp.
Referenced by checkRunning().
handleRetainFeature()
void GlobalSearch::QueueManager::handleRetainFeature (Structure * s) protected
Perform actions on a structure that has successfully finished feature/aflow-hardness calculations
Parameters
s Structure whose features/aflow-hardness is calculated
Definition at line 709 of file queuemanager.cpp.
Referenced by checkRunning().
handleStepOptimizedStructure()
void GlobalSearch::QueueManager::handleStepOptimizedStructure (Structure * s) protected
Perform actions on the StepOptimized Structure s.
Parameters
s Structure of interest
Definition at line 574 of file queuemanager.cpp.
Referenced by checkRunning().
handleSubmittedStructure()
void GlobalSearch::QueueManager::handleSubmittedStructure (Structure * s) protected
Perform actions on the Submitted Structure s.
Parameters
s Structure of interest
Definition at line 935 of file queuemanager.cpp.
Referenced by checkRunning().
handleSupercellStructure()
void GlobalSearch::QueueManager::handleSupercellStructure (Structure * s) protected
Perform actions on the Supercell Structure s.
Parameters
s Structure of interest
Definition at line 1050 of file queuemanager.cpp.
Referenced by checkRunning().
handleUpdatingStructure()
void GlobalSearch::QueueManager::handleUpdatingStructure (Structure * s) protected
Perform actions on the Updating Structure s.
Parameters
s Structure of interest
Definition at line 856 of file queuemanager.cpp.
Referenced by checkRunning().
handleWaitingForOptimizationStructure()
void GlobalSearch::QueueManager::handleWaitingForOptimizationStructure (Structure * s) protected
Perform actions on the WaitingForOptimization Structure s.
Parameters
s Structure of interest
Definition at line 846 of file queuemanager.cpp.
Referenced by checkRunning().
killStructure
void GlobalSearch::QueueManager::killStructure (Structure * s) slot
Stops any running optimization processes associated with a structure and sets its status to Structure::Killed.
The structureKilled signal is emitted as well.
Parameters
s The Structure to kill.
See also
structureKilled
Definition at line 1127 of file queuemanager.cpp.
References GlobalSearch::Structure::getStatus(), GlobalSearch::Structure::Killed, GlobalSearch::Structure::lock(), GlobalSearch::Structure::Optimized, GlobalSearch::Structure::Removed, GlobalSearch::Structure::setStatus(), stopJob(), GlobalSearch::Structure::stopOptTimer(), and structureKilled().
lockForNaming
QList< Structure * > GlobalSearch::QueueManager::lockForNaming () slot
Locks the m_tracker and m_newStructure for reading.
Returns
All Structures in getAllStructures()
Definition at line 1332 of file queuemanager.cpp.
References GlobalSearch::Tracker::list(), GlobalSearch::Tracker::lockForRead(), m_newStructureTracker, and m_tracker.
movedToQMThread
void GlobalSearch::QueueManager::movedToQMThread () signal
Emitted when the QueueManager has been moved to it's final thread and is ready to accept connections.
Referenced by moveToQMThread().
moveToQMThread
void GlobalSearch::QueueManager::moveToQMThread () protected slot
Move this to the QThread specified in the constructor and setup connections in that thread's event loop.
Definition at line 120 of file queuemanager.cpp.
References m_thread, movedToQMThread(), and setupConnections().
Referenced by QueueManager().
needNewStructure
void GlobalSearch::QueueManager::needNewStructure () signal
Emitted when the number of unoptimized Structures drops below OptBase::contStructs. This is connected to OptBase::generateNewStructure() by default.
Referenced by checkPopulation(), and setupConnections().
newStatusOverview
void GlobalSearch::QueueManager::newStatusOverview (int optimized, int running, int failing) signal
Emitted when checkPopulation() is called to provide a short summary of the queuemanager's status.
Parameters
optimized Number of optimized structures
running Number of running structures (e.g. submitted for optimization)
failing Number of structures with a getFailCount() > 0
Referenced by checkPopulation().
readyForFeatureCalculations
void GlobalSearch::QueueManager::readyForFeatureCalculations (GlobalSearch::Structure * s) signal
Emitted when a structure has successfully finished all optimization steps and is ready for feature calculation
Parameters
s Structure
Referenced by GlobalSearch::OptBase::OptBase(), and setupConnections().
reset
void GlobalSearch::QueueManager::reset () slot
Reset all trackers in trackerList
Definition at line 167 of file queuemanager.cpp.
References m_jobStartTracker, m_newStructureTracker, m_runningTracker, and m_tracker.
Referenced by GlobalSearch::OptBase::reset().
setupConnections
void GlobalSearch::QueueManager::setupConnections () protected slot
Called by moveToQMThread(), this function installs connections in the owning thread's event loop.
Definition at line 130 of file queuemanager.cpp.
References addStructureToSubmissionQueue(), checkLoop(), m_opt, needNewStructure(), readyForFeatureCalculations(), structureFinished(), structureKilled(), structureStarted(), structureSubmitted(), structureUpdated(), and updateStructureFeatureStatus().
Referenced by moveToQMThread().
startJob()
void GlobalSearch::QueueManager::startJob () protected
Submits the first Structure in m_jobStartTracker for submission. This should not be called directly, instead call prepareStructureForSubmission(Structure*).
See also
prepareStructureForSubmission
Definition at line 1188 of file queuemanager.cpp.
References GlobalSearch::Structure::Error, GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::Structure::getGeneration(), GlobalSearch::Structure::getIDNumber(), GlobalSearch::Structure::getIDString(), GlobalSearch::Structure::lock(), m_jobStartTracker, m_opt, GlobalSearch::Tracker::popFirst(), GlobalSearch::OptBase::queueInterface(), GlobalSearch::Structure::setStatus(), GlobalSearch::QueueInterface::startJob(), structureSubmitted(), GlobalSearch::Structure::Submitted, GlobalSearch::OptBase::usingGUI(), and GlobalSearch::OptBase::warning().
Referenced by checkPopulation().
stopJob()
void GlobalSearch::QueueManager::stopJob (Structure * s) protected
Kills the optimization process for the indicated Structure.
Parameters
s The Structure to stop optimizing.
Definition at line 1222 of file queuemanager.cpp.
References GlobalSearch::Structure::getCurrentOptStep(), m_opt, GlobalSearch::OptBase::queueInterface(), and GlobalSearch::QueueInterface::stopJob().
Referenced by killStructure().
structureFinished
void GlobalSearch::QueueManager::structureFinished (GlobalSearch::Structure * s) signal
Emitted when a Structure has completed all optimization steps.
Parameters
s The Structure that has been updated
Referenced by setupConnections().
structureKilled
void GlobalSearch::QueueManager::structureKilled (GlobalSearch::Structure * s) signal
Emitted when a Structure has been killed through killStructure(Structure*)
Parameters
s The Structure that has been killed
See also
killStructure
Referenced by killStructure(), and setupConnections().
structureStarted
void GlobalSearch::QueueManager::structureStarted (GlobalSearch::Structure * s) signal
Emitted when a Structure is accepted into the queuemanager (e.g. after submission through unlockForNaming(Structure*)
Parameters
s The Structure that has been accepted
See also
lockForNaming
unlockForNaming
Referenced by setupConnections().
structureSubmitted
void GlobalSearch::QueueManager::structureSubmitted (GlobalSearch::Structure * s) signal
Emitted when a Structure is submitted for optimization
Parameters
s The Structure that has been submitted
Referenced by setupConnections(), and startJob().
structureUpdated
void GlobalSearch::QueueManager::structureUpdated (GlobalSearch::Structure * s) signal
Emitted when a Structure has changed status. Useful for updating progress tables, plots, etc
Parameters
s The Structure that has been updated
Referenced by GlobalSearch::OptBase::OptBase(), and setupConnections().
unlockForNaming
void GlobalSearch::QueueManager::unlockForNaming (Structure * s = 0) slot
Unlocks both the main and startPending trackers.
Parameters
s Optional new stucture to be added to the queuemanager and tracker.
Definition at line 1342 of file queuemanager.cpp.
References GlobalSearch::Tracker::append(), GlobalSearch::Structure::getIDString(), GlobalSearch::OptBase::isStarting, GlobalSearch::Tracker::lockForWrite(), m_isDestroying, m_newStructureTracker, m_opt, m_requestedStructures, m_tracker, and GlobalSearch::Tracker::unlock().
updateQueue()
void GlobalSearch::QueueManager::updateQueue () protected
Update the data from the remote PBS queue.
updateStructure()
void GlobalSearch::QueueManager::updateStructure (Structure * s) protected
Called on Structures that are Structure::StepOptimized, this function will update the Structure with the results of the optimization and pass it along to prepareStructureForNextOptStep.
Parameters
s The step optimized structure
See also
prepareStructureForNextOptStep
updateStructureFeatureStatus
void GlobalSearch::QueueManager::updateStructureFeatureStatus (Structure * s) protected slot
Check for the status of finished feature/aflow-hardness calculations, and label the structure accordingly for further processing with appropriate handler.
Parameters
s Structure whose features/aflow-hardness is calculated
Definition at line 659 of file queuemanager.cpp.
References GlobalSearch::Structure::FeatureDismiss, GlobalSearch::Structure::FeatureFail, GlobalSearch::Structure::FeatureRetain, GlobalSearch::Structure::FS_Dismiss, GlobalSearch::Structure::FS_NotCalculated, GlobalSearch::Structure::FS_Retain, GlobalSearch::Structure::lock(), GlobalSearch::OptBase::m_calculateFeatures, GlobalSearch::OptBase::m_calculateHardness, m_opt, GlobalSearch::Structure::setStatus(), and GlobalSearch::Structure::vickersHardness().
Referenced by setupConnections().
Member Data Documentation
m_isDestroying
bool GlobalSearch::QueueManager::m_isDestroying protected
Boolean set to true while the destructor is running.
Definition at line 582 of file queuemanager.h.
Referenced by unlockForNaming(), and ~QueueManager().
m_jobStartTracker
Tracker GlobalSearch::QueueManager::m_jobStartTracker protected
Tracks which structures are queued to be submitted.
Definition at line 573 of file queuemanager.h.
Referenced by appendToJobStartTracker(), checkPopulation(), reset(), and startJob().
m_lastSubmissionTimeStamp
QDateTime* GlobalSearch::QueueManager::m_lastSubmissionTimeStamp protected
Used to throttle job submissions.
Definition at line 585 of file queuemanager.h.
Referenced by checkPopulation(), and ~QueueManager().
m_newStructureTracker
Tracker GlobalSearch::QueueManager::m_newStructureTracker protected
Tracks structures that have been returned from m_opt but have not yet been accepted into m_tracker.
Definition at line 576 of file queuemanager.h.
Referenced by checkPopulation(), getAllRunningStructures(), getAllStructures(), lockForNaming(), reset(), and unlockForNaming().
m_opt
OptBase* GlobalSearch::QueueManager::m_opt protected
Cached pointer to main optbase class.
Definition at line 335 of file queuemanager.h.
Referenced by checkExit(), checkLoop(), checkPopulation(), setupConnections(), startJob(), stopJob(), unlockForNaming(), and updateStructureFeatureStatus().
m_requestedStructures
int GlobalSearch::QueueManager::m_requestedStructures protected
Number of structure requests pending.
Definition at line 579 of file queuemanager.h.
Referenced by addManualStructureRequest(), checkPopulation(), unlockForNaming(), and ~QueueManager().
m_runningTracker
Tracker GlobalSearch::QueueManager::m_runningTracker protected
Tracks which structures are currently running.
Definition at line 571 of file queuemanager.h.
Referenced by checkPopulation(), getAllRunningStructures(), and reset().
m_thread
QThread* GlobalSearch::QueueManager::m_thread protected
Pointer to the thread where the queuemanager lives.
Definition at line 338 of file queuemanager.h.
Referenced by checkLoop(), checkRunning(), and moveToQMThread().
m_tracker
Tracker* GlobalSearch::QueueManager::m_tracker protected
Convenience pointer to m_opt->tracker()
Definition at line 341 of file queuemanager.h.
Referenced by addManualStructureRequest(), checkExit(), checkPopulation(), getAllDuplicateStructures(), getAllOptimizedStructures(), getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit(), getAllStructures(), getAllSupercellStructures(), lockForNaming(), reset(), and unlockForNaming().
The documentation for this class was generated from the following files:
src/globalsearch/queuemanager.h
src/globalsearch/queuemanager.cpp