XtalOpt - API:GlobalSearch::LocalQueueInterface Class Reference
GlobalSearch::LocalQueueInterface Class Reference
Interface for running jobs locally.
#include <globalsearch/local.h>
Public Slots
virtual bool writeFiles (Structure *s, const QHash< QString, QString > &files) const override
bool logErrorDirectory (Structure *s) const
virtual bool startJob (Structure *s) override
virtual bool stopJob (Structure *s) override
virtual QueueInterface::QueueStatus getStatus (Structure *s) const override
virtual bool prepareForStructureUpdate (Structure *s) const override
virtual bool runACommand (const QString &workdir, const QString &command, QString *sout, QString *serr, int *ercd) const override
virtual bool copyAFileRemoteToLocal (const QString &rem_file, const QString &loc_file) override
virtual bool copyAFileLocalToRemote (const QString &loc_file, const QString &rem_file) override
virtual bool checkIfFileExists (Structure *s, const QString &filename, bool *exists) override
virtual bool fetchFile (Structure *s, const QString &filename, QString *contents) const override
virtual bool grepFile (Structure *s, const QString &matchText, const QString &filename, QStringList *matches=0, int *exitcode=0, const bool caseSensitive=true) const override
virtual QDialog * dialog () override
Public Slots inherited from GlobalSearch::QueueInterface
virtual void readSettings (const QString &filename="")
virtual void writeSettings (const QString &filename="")
virtual bool writeInputFiles (Structure *s) const
virtual bool writeFiles (Structure *s, const QHash< QString, QString > &files) const =0
virtual bool startJob (Structure *s)=0
virtual bool stopJob (Structure *s)=0
virtual QueueInterface::QueueStatus getStatus (Structure *s) const =0
virtual bool prepareForStructureUpdate (Structure *s) const =0
virtual bool runACommand (const QString &workdir, const QString &command, QString *sout, QString *serr, int *ercd) const =0
virtual bool copyAFileRemoteToLocal (const QString &rem_file, const QString &loc_file)=0
virtual bool copyAFileLocalToRemote (const QString &loc_file, const QString &rem_file)=0
virtual bool checkIfFileExists (Structure *s, const QString &filename, bool *exists)=0
virtual bool fetchFile (Structure *s, const QString &filename, QString *contents) const =0
virtual bool grepFile (Structure *s, const QString &matchText, const QString &filename, QStringList *matches=0, int *exitcode=0, const bool caseSensitive=true) const =0
QString getIDString () const
Public Member Functions
LocalQueueInterface (OptBase *parent, const QString &settingFile="")
virtual ~LocalQueueInterface () override
virtual bool isReadyToSearch (QString *err) override
Public Member Functions inherited from GlobalSearch::QueueInterface
QueueInterface (OptBase *parent, const QString &settingFile="")
virtual ~QueueInterface () override
QStringList getTemplateFileNames () const
bool isTemplateFileName (const char *name) const
Optimizer * getCurrentOptimizer (Structure *s) const
bool hasDialog ()
virtual QDialog * dialog ()
Protected Attributes
QHash< unsigned long, LocalQueueProcess * > m_processes
Protected Attributes inherited from GlobalSearch::QueueInterface
OptBase * m_opt
Cached pointer to the parent OptBase class.
QString m_idString
String identifying the type of queue interface.
QStringList m_templates
bool m_hasDialog
Whether this QueueInterface has a configuration dialog.
QDialog * m_dialog
Pointer to configuration dialog (may be nullptr)
Friends
class LocalQueueInterfaceConfigDialog
Additional Inherited Members
Public Types inherited from GlobalSearch::QueueInterface
enum QueueStatus {
Unknown = -1 , Success , Error , Queued ,
Running , CommunicationError , Started , Pending
}
Detailed Description
Interface for running jobs locally.
Author
David C. Lonie
Definition at line 65 of file local.h.
Constructor & Destructor Documentation
LocalQueueInterface()
GlobalSearch::LocalQueueInterface::LocalQueueInterface (OptBase * parent, const QString & settingFile = "") explicit
Constructor
Parameters
parent OptBase parent
settingFile Filename from which to initialize settings.
Definition at line 37 of file local.cpp.
References GlobalSearch::QueueInterface::m_hasDialog, and GlobalSearch::QueueInterface::m_idString.
~LocalQueueInterface()
GlobalSearch::LocalQueueInterface::~LocalQueueInterface () override virtual
Destructor
Definition at line 49 of file local.cpp.
References m_processes.
Member Function Documentation
checkIfFileExists
bool GlobalSearch::LocalQueueInterface::checkIfFileExists (Structure * s, const QString & filename, bool * exists) override virtual slot
Check if the file filename exists in the working directory of Structure s and store the result in exists.
Note
This function uses the argument exists to report whether or not the file exists. The return value indicates whether the file check was performed without errors (e.g. network errors).
Returns
True if the test encountered no errors, false otherwise.
Definition at line 408 of file local.cpp.
References GlobalSearch::Structure::fileName().
copyAFileLocalToRemote
bool GlobalSearch::LocalQueueInterface::copyAFileLocalToRemote (const QString & loc_file, const QString & rem_file) override virtual slot
This is a dummy function! If called while the run is 'local', it does nothing!
Parameters
loc_file Full path to the file to be copied (a local path)
rem_file Full path to the destination file (a remote path)
Definition at line 401 of file local.cpp.
copyAFileRemoteToLocal
bool GlobalSearch::LocalQueueInterface::copyAFileRemoteToLocal (const QString & rem_file, const QString & loc_file) override virtual slot
This is a dummy function! If called while the run is 'local', it does nothing!
Parameters
rem_file Full path to the file to be copied (a remote path)
loc_file Full path to the destination file (a local path)
Definition at line 394 of file local.cpp.
fetchFile
bool GlobalSearch::LocalQueueInterface::fetchFile (Structure * s, const QString & filename, QString * contents) const override virtual slot
Retrieve the contents of the file filename for Structure s as a QString contents.
Returns
True on success, false otherwise.
Definition at line 416 of file local.cpp.
References GlobalSearch::Structure::fileName().
getStatus
QueueInterface::QueueStatus GlobalSearch::LocalQueueInterface::getStatus (Structure * s) const override virtual slot
Returns
The queue status of Structure s.
Definition at line 270 of file local.cpp.
References GlobalSearch::Optimizer::checkForSuccessfulOutput(), GlobalSearch::Optimizer::checkIfOutputFileExists(), GlobalSearch::QueueInterface::Error, GlobalSearch::QueueInterface::getCurrentOptimizer(), GlobalSearch::Structure::getIDString(), GlobalSearch::Structure::getJobID(), GlobalSearch::Structure::getStatus(), GlobalSearch::Structure::lock(), GlobalSearch::QueueInterface::m_opt, m_processes, GlobalSearch::QueueInterface::Pending, GlobalSearch::QueueInterface::Running, GlobalSearch::QueueInterface::Started, GlobalSearch::Structure::Submitted, GlobalSearch::QueueInterface::Success, GlobalSearch::QueueInterface::Unknown, and GlobalSearch::OptBase::warning().
grepFile
bool GlobalSearch::LocalQueueInterface::grepFile (Structure * s, const QString & matchText, const QString & filename, QStringList * matches = 0, int * exitcode = 0, const bool caseSensitive = true) const override virtual slot
Grep through the file filename for Structure s's working directory, looking for matchText. The list of matches is returned in the QStringList matches and the exit status is returned as exitcode.
Possible exitcodes:
0: Matches were found, execution successful
1: No matches found, execution successful
2: Execution unsuccessful
Parameters
s Structure of interest
matchText Text to match
filename Name of file to grep
matches List of matches (return)
exitcode Exit code of grep (see details) (return)
caseSensitive If true, match case. Otherwise, perform case-insensitive search (e.g. grep -i) Default is true.
Returns
True on success, false otherwise.
Note
There are two types of failure possible here: Either the exitcode can be 2 or the function can return false. If the exitcode is 2, then grep failed to execute. If false, then there was a failure in the interface code, likely a communication error with a remote server.
On local queue interface, grep is not actually used and the exit code behavior is emulated.
Definition at line 429 of file local.cpp.
References GlobalSearch::Structure::fileName().
isReadyToSearch()
bool GlobalSearch::LocalQueueInterface::isReadyToSearch (QString * err) override virtual
Check that all mandatory internal variables are set. Check this before starting a search.
Parameters
err String to be overwritten with an error message
Returns
true if all variables are initialized, false otherwise. If false, err will be overwritten with a user-friendly error message.
Reimplemented from GlobalSearch::QueueInterface.
Definition at line 65 of file local.cpp.
References GlobalSearch::OptBase::filePath, and GlobalSearch::QueueInterface::m_opt.
logErrorDirectory
bool GlobalSearch::LocalQueueInterface::logErrorDirectory (Structure * s) const slot
Saves a copy of the error directory that caused this structure to fail. Saves it in <local_path>/errorDirs
Parameters
structure Structure of interest
Returns
True on success, false otherwise
Definition at line 211 of file local.cpp.
References GlobalSearch::Structure::fileName(), GlobalSearch::OptBase::filePath, GlobalSearch::Structure::getGeneration(), GlobalSearch::Structure::getIDNumber(), and GlobalSearch::QueueInterface::m_opt.
Referenced by stopJob().
prepareForStructureUpdate
bool GlobalSearch::LocalQueueInterface::prepareForStructureUpdate (Structure * s) const override virtual slot
Perform any work needed before calling Optimizer::update. This function mainly exists for RemoteQueue classes to copy files back from the server, but may be used for other purposes. It is guaranteed to be called by Optimizer before updating.
Parameters
s The structure that is to be updated.
Returns
True on success, false otherwise.
Definition at line 352 of file local.cpp.
runACommand
bool GlobalSearch::LocalQueueInterface::runACommand (const QString & workdir, const QString & command, QString * sout, QString * serr, int * ercd) const override virtual slot
Runs a command (e.g., bash command or script) in a local path.
Parameters
workdir Workind directory for the command
command The command
sout The stdout string
serr The stderr string
ercd The exit error code
Returns
For a local run, always returns True.
Definition at line 358 of file local.cpp.
References GlobalSearch::QueueInterface::m_opt, and GlobalSearch::OptBase::warning().
startJob
bool GlobalSearch::LocalQueueInterface::startJob (Structure * s) override virtual slot
Start a job for Structure s.
Note
Ensure that writeFiles is called before attempting to start the job.
Returns
True on success, false otherwise.
Definition at line 163 of file local.cpp.
References GlobalSearch::Structure::fileName(), GlobalSearch::QueueInterface::getCurrentOptimizer(), GlobalSearch::Structure::getIDString(), GlobalSearch::Structure::getJobID(), GlobalSearch::Optimizer::localRunCommand(), GlobalSearch::QueueInterface::m_opt, m_processes, GlobalSearch::Structure::setJobID(), GlobalSearch::Structure::startOptTimer(), and GlobalSearch::OptBase::warning().
stopJob
bool GlobalSearch::LocalQueueInterface::stopJob (Structure * s) override virtual slot
Stop any currently running jobs for Structure s.
Returns
True on success, false otherwise.
Definition at line 239 of file local.cpp.
References GlobalSearch::Structure::Error, GlobalSearch::Structure::getJobID(), GlobalSearch::Structure::getStatus(), GlobalSearch::Structure::lock(), logErrorDirectory(), GlobalSearch::OptBase::m_logErrorDirs, GlobalSearch::QueueInterface::m_opt, m_processes, GlobalSearch::Structure::Restart, GlobalSearch::Structure::setJobID(), and GlobalSearch::Structure::stopOptTimer().
writeFiles
bool GlobalSearch::LocalQueueInterface::writeFiles (Structure * s, const QHash< QString, QString > & files) const override virtual slot
Write the input files in the hash files to the appropriate location for Structure s.
Parameters
s Structure of interest
files Key: filename, Value: text.
Note
The filenames in files must not be absolute, but relative to the structure's working directory.
Returns
True on success, false otherwise.
Definition at line 103 of file local.cpp.
References GlobalSearch::Structure::clearCopyFiles(), GlobalSearch::Structure::copyFiles(), GlobalSearch::OptBase::error(), GlobalSearch::Structure::fileName(), and GlobalSearch::QueueInterface::m_opt.
Friends And Related Symbol Documentation
LocalQueueInterfaceConfigDialog
friend class LocalQueueInterfaceConfigDialog friend
Definition at line 70 of file local.h.
Member Data Documentation
m_processes
QHash<unsigned long, LocalQueueProcess*> GlobalSearch::LocalQueueInterface::m_processes protected
Look up hash for mapping jobID's to processes. Key: PID, Value: QProcess handle
Definition at line 260 of file local.h.
Referenced by getStatus(), startJob(), stopJob(), and ~LocalQueueInterface().
The documentation for this class was generated from the following files:
src/globalsearch/queueinterfaces/local.h
src/globalsearch/queueinterfaces/local.cpp