XtalOpt - API:GlobalSearch::Structure Class Reference
GlobalSearch::Structure Class Reference
Generic molecule object.
#include <globalsearch/structure.h>
Public Types
enum FeatStatus { FS_NotCalculated = 0 , FS_Retain , FS_Dismiss , FS_Fail }
enum State {
Optimized = 0 , StepOptimized , WaitingForOptimization , InProcess ,
Empty , Updating , Error , Submitted ,
Killed , Removed , Duplicate , Supercell ,
Restart , FeatureDismiss , FeatureFail , FeatureRetain ,
FeatureCalculation
}
Public Slots
virtual void setupConnections ()
virtual void enableAutoHistogramGeneration (bool)
virtual void requestHistogramGeneration ()
virtual void generateDefaultHistogram ()
virtual void structureChanged ()
static bool compareIADDistributions (const std::vector< double > &d, const std::vector< double > &f1, const std::vector< double > &f2, double decay, double smear, double *error)
static bool compareIADDistributions (const QList< double > &d, const QList< double > &f1, const QList< double > &f2, double decay, double smear, double *error)
static bool compareIADDistributions (const QList< QVariant > &d, const QList< QVariant > &f1, const QList< QVariant > &f2, double decay, double smear, double *error)
virtual void writeSettings (const QString &filename)
Signals
void featureOutputExists ()
Public Member Functions
Structure (QObject *parent=0)
Structure (const Structure &other)
Structure (Structure &&other) noexcept
Structure (const GlobalSearch::Molecule &other)
virtual ~Structure () override
Structure & operator= (const Structure &other)
Structure & operator= (Structure &&other) noexcept
Structure & operator= (const GlobalSearch::Molecule &other)
int getStrucFeatNumber () const
double getStrucFeatValues (int i) const
FeatStatus getStrucFeatStatus () const
int getStrucFeatFailCt () const
void setStrucFeatValues (double v)
void setStrucFeatStatus (FeatStatus v)
void setStrucFeatFailCt (int i)
void resetStrucFeat ()
void setStrucFeatValuesVec (QList< double > v)
QList< double > getStrucFeatValuesVec ()
void resetStrucHistFeat ()
int getStrucHistFeatNumber ()
QList< double > getStrucHistFeatValues (int i)
FeatStatus getStrucHistFeatStatus (int i)
int getStrucHistFeatFailCt (int i)
void setStrucHistFeatValues (QList< double > v)
void setStrucHistFeatStatus (FeatStatus v)
void setStrucHistFeatFailCt (int v)
bool hasEnthalpy () const
bool hasParentStructure () const
int getFixCount () const
double getEnergy () const
double getEnthalpy () const
double getEnthalpyPerFU () const
double getEnthalpyPerAtom () const
double getPV () const
uint getRank () const
uint getJobID () const
uint getGeneration () const
uint getIDNumber () const
int getIndex () const
QReadWriteLock & lock ()
QString getDuplicateString () const
QString getSupercellString () const
QString getParents () const
QString getRempath () const
QString fileName () const
State getStatus () const
uint getCurrentOptStep ()
uint getFailCount ()
uint getFormulaUnits () const
Structure * getParentStructure () const
QDateTime getOptTimerStart () const
QDateTime getOptTimerEnd () const
QString getIDString () const
virtual QString getResultsHeader (bool includeHardness, int features_num) const
void updateAndAddFeaturesToHistory (Structure *s)
virtual QString getResultsEntry (bool includeHardness, int features_num, int optstep) const
virtual bool getNearestNeighborDistances (QList< double > *list) const
virtual bool getShortestInteratomicDistance (double &shortest) const
virtual bool getNearestNeighborDistance (const double x, const double y, const double z, double &shortest) const
virtual bool getNearestNeighborDistance (const GlobalSearch::Atom &atom, double &shortest) const
QList< GlobalSearch::Atom > getNeighbors (const double x, const double y, const double z, const double cutoff, QList< double > *distances=0) const
QList< GlobalSearch::Atom > getNeighbors (const GlobalSearch::Atom &atom, const double cutoff, QList< double > *distances=0) const
virtual void getDefaultHistogram (QList< double > *dist, QList< double > *freq) const
virtual void getDefaultHistogram (QList< QVariant > *dist, QList< QVariant > *freq) const
virtual bool isHistogramGenerationPending () const
virtual bool generateIADHistogram (QList< double > *distance, QList< double > *frequency, double min=0.0, double max=10.0, double step=0.01, const GlobalSearch::Atom &atom=Atom()) const
virtual bool generateIADHistogram (QList< QVariant > *distance, QList< QVariant > *frequency, double min=0.0, double max=10.0, double step=0.01, const GlobalSearch::Atom &atom=Atom()) const
virtual bool addAtomRandomly (uint atomicNumber, double minIAD=0.0, double maxIAD=0.0, int maxAttempts=1000)
void perceiveBonds ()
QList< QString > getSymbols () const
QList< uint > getNumberOfAtomsAlpha () const
QList< Vector3 > getAtomCoordsFrac () const
QString getOptElapsed () const
int getOptElapsedSeconds () const
double getOptElapsedHours () const
virtual QHash< QString, QVariant > getFingerprint () const
bool hasChangedSinceDupChecked ()
bool wasPrimitiveChecked () const
bool wasSupercellGenerationChecked () const
bool skippedOptimization () const
std::vector< std::string > copyFiles () const
void appendCopyFile (const std::string &f)
void clearCopyFiles ()
void setReusePreoptBonding (bool b)
bool reusePreoptBonding ()
void clearPreoptBonding ()
void setPreoptBonding (const std::vector< Bond > &v)
const std::vector< Bond > & getPreoptBonding () const
double bulkModulus () const
double shearModulus () const
double vickersHardness () const
void setBulkModulus (double d)
void setShearModulus (double d)
void setVickersHardness (double d)
virtual void readSettings (const QString &filename, const bool readCurrentInfo=false)
virtual void updateAndSkipHistory (const QList< unsigned int > &atomicNums, const QList< Vector3 > &coords, const double energy=0, const double enthalpy=0, const Matrix3 &cell=Matrix3::Zero())
virtual void updateAndAddToHistory (const QList< unsigned int > &atomicNums, const QList< Vector3 > &coords, const double energy=0, const double enthalpy=0, const Matrix3 &cell=Matrix3::Zero())
virtual void deleteFromHistory (unsigned int index)
virtual void retrieveHistoryEntry (unsigned int index, QList< unsigned int > *atomicNums, QList< Vector3 > *coords, double *energy, double *enthalpy, Matrix3 *cell)
virtual unsigned int sizeOfHistory ()
void setFixCount (int fixCount)
void setEnergy (double energy)
void setEnthalpy (double enthalpy)
void setPV (double pv)
void resetEnthalpy ()
void resetEnergy ()
void setRank (uint rank)
void setJobID (uint id)
void setGeneration (uint gen)
void setIDNumber (uint id)
void setIndex (int index)
void setParents (const QString &p)
void setRempath (const QString &p)
void setFileName (const QString &p)
void setStatus (State status)
void setCurrentOptStep (uint i)
void setFailCount (uint count)
void setParentStructure (Structure *structure)
void resetFailCount ()
void addFailure ()
void setDuplicateString (const QString &s)
void setSupercellString (const QString &s)
void setChangedSinceDupChecked (bool b)
void setPrimitiveChecked (bool b)
void setSupercellGenerationChecked (bool b)
void setSkippedOptimization (bool b)
void startOptTimer ()
void stopOptTimer ()
void setOptTimerStart (const QDateTime &d)
void setOptTimerEnd (const QDateTime &d)
virtual void load (QTextStream &in)
Static Public Member Functions
static QList< uint > countStructuresOfEachFormulaUnit (QList< Structure * > *structures, int maxFU)
static void sortByEnthalpy (QList< Structure * > *structures)
static void sortByVickersHardness (QList< Structure * > *structures)
static void rankByEnthalpy (const QList< Structure * > &structures)
static void sortAndRankByEnthalpy (QList< Structure * > *structures)
Protected Slots
void writeStructureSettings (const QString &filename)
void readStructureSettings (const QString &filename, const bool readCurrentInfo=false)
void writeCurrentStructureInfo (const QString &filename)
void readCurrentStructureInfo (const QString &filename)
Protected Attributes
std::atomic< FeatStatus > m_strucFeatStatus
QList< double > m_strucFeatValues
int m_strucFeatFailCt
QList< FeatStatus > m_hist_strucFeatStatus
QList< QList< double > > m_hist_strucFeatValues
QList< int > m_hist_strucFeatFailCt
Detailed Description
Generic molecule object.
Author
David C. Lonie
The Structure class provides a generic data object for storing information about a molecule. It derives from GlobalSearch::Molecule, adding new functionality to help with common tasks during a global structure search.
Definition at line 45 of file structure.h.
Member Enumeration Documentation
FeatStatus
enum GlobalSearch::Structure::FeatStatus
Enum possible feature calculation outcomes for a structure
Enumerator
FS_NotCalculated
Features are not calculated
FS_Retain
Features are calculated, structure should be kept
FS_Dismiss
Features calculated, structure dismissed by a filtration feature
FS_Fail
Feature calculations failed (bad output file, ...)
Definition at line 97 of file structure.h.
State
enum GlobalSearch::Structure::State
Enum containing possible optimization statuses.
See also
setStatus
getStatus
Enumerator
Optimized
Structure has completed all optimization steps
StepOptimized
Structure has completed an optimization step but may still have some to complete. getCurrentOptStep() shows the step that has just completed.
WaitingForOptimization
Structure is waiting to start an optimization step. getCurrentOptStep() shows the step it will start next.
InProcess
Structure is currently queued or running an optimization step on the PBS server (if applicable).
Empty
Structure has just been generated, and has not yet been initialized
Updating
The Structure has completed it's current optimization step, and the results of the calculation are being transferred and applied.
Error
The optimization is failing.
Submitted
The Structure has been submitted to the PBS server, but has not appeared in the queue yet.
Killed
The Structure has been killed before finishing all optimization steps.
Removed
The Structure has been killed after finishing all optimization steps.
Duplicate
The Structure has been found to be a duplicate of another. The other structure's information can be found in getDuplicateString().
Supercell
The Structure has been found to be a supercell of another. The other structure's information can be found in getSupercellString().
Restart
The Structure is about to restart it's current optimization step.
FeatureDismiss
Structure marked as dismissed in feature calculations.
FeatureFail
Feature calculations for the structure have failed.
FeatureRetain
All feature/hardness calculations for structure are successfully finished.
FeatureCalculation
Structure is in the process of feature calculations
Definition at line 114 of file structure.h.
Constructor & Destructor Documentation
Structure() [1/4]
GlobalSearch::Structure::Structure (QObject * parent = 0)
Constructor.
Parameters
parent The object parent.
Definition at line 37 of file structure.cpp.
References Empty, resetFailCount(), and setStatus().
Structure() [2/4]
GlobalSearch::Structure::Structure (const Structure & other)
Copy constructor.
Definition at line 53 of file structure.cpp.
Structure() [3/4]
GlobalSearch::Structure::Structure (Structure && other) noexcept
Move constructor. Calls the move assignment operator.
Definition at line 66 of file structure.cpp.
Structure() [4/4]
GlobalSearch::Structure::Structure (const GlobalSearch::Molecule & other)
Explicit copy constructor for Molecules.
Definition at line 71 of file structure.cpp.
~Structure()
GlobalSearch::Structure::~Structure () override virtual
Destructor.
Definition at line 97 of file structure.cpp.
Member Function Documentation
addAtomRandomly()
bool GlobalSearch::Structure::addAtomRandomly (uint atomicNumber, double minIAD = 0.0, double maxIAD = 0.0, int maxAttempts = 1000) virtual
Add an atom to a random position in the Structure. If no other atoms exist in the Structure, the new atom is placed at (0,0,0).
Returns
true if the atom was sucessfully added within the specified interatomic distances.
Parameters
atomicNumber Atomic number of atom to add.
minIAD Smallest interatomic distance allowed (nullptr or omit for no limit)
maxIAD Largest interatomic distance allowed (nullptr or omit for no limit)
maxAttempts Maximum number of tries before giving up.
Definition at line 805 of file structure.cpp.
References getNearestNeighborDistance().
addFailure()
void GlobalSearch::Structure::addFailure () inline
Increase the number of times this Structure has failed the current optimization step by one.
See also
resetFailCount
setFailCount
getFailCount
Definition at line 1294 of file structure.h.
References getFailCount(), and setFailCount().
appendCopyFile()
void GlobalSearch::Structure::appendCopyFile (const std::string & f) inline
Append a file to be copied to this structure's working directory. This will only append the file if it does not already exist, so it is safe to append the same file multiple times.
Parameters
f The name of the file to be copied.
Definition at line 801 of file structure.h.
Referenced by GlobalSearch::OptBase::interpretKeyword_base().
bulkModulus()
double GlobalSearch::Structure::bulkModulus () const inline
Get the bulk modulus as calculated by Aflow machine learning.
Returns
The bulk modulus (or -1.0 if it hasn't been set).
Definition at line 862 of file structure.h.
Referenced by writeStructureSettings().
clearCopyFiles()
void GlobalSearch::Structure::clearCopyFiles () inline
Clears the list of files to be copied to a structure's working dir.
Definition at line 812 of file structure.h.
Referenced by GlobalSearch::LocalQueueInterface::writeFiles().
clearPreoptBonding()
void GlobalSearch::Structure::clearPreoptBonding () inline
Clear pre-optimization bonding information.
Definition at line 837 of file structure.h.
Referenced by updateAndAddToHistory().
compareIADDistributions [1/3]
bool GlobalSearch::Structure::compareIADDistributions (const QList< double > & d, const QList< double > & f1, const QList< double > & f2, double decay, double smear, double * error) static slot
Compare two IAD histograms.
Given two histograms over the same range with the same step, this function calculates an error value to measure the differences between the two. A boxcar smoothing is performed using a width of "smear", and an optional weight can be applied. The weight is a standard exponential decay with a halflife of "decay".
Parameters
d List of distances
f1 First list of frequencies
f2 Second list of frequencies
decay Exponential decay parameter for lowering weight of large IADs
smear Boxcar smoothing width in Angstroms
error Return error value
Returns
Whether or not the operation could be performed.
Definition at line 1283 of file structure.cpp.
References compareIADDistributions().
compareIADDistributions [2/3]
bool GlobalSearch::Structure::compareIADDistributions (const QList< QVariant > & d, const QList< QVariant > & f1, const QList< QVariant > & f2, double decay, double smear, double * error) static slot
Compare two IAD histograms.
Given two histograms over the same range with the same step, this function calculates an error value to measure the differences between the two. A boxcar smoothing is performed using a width of "smear", and an optional weight can be applied. The weight is a standard exponential decay with a halflife of "decay".
Parameters
d List of distances
f1 First list of frequencies
f2 Second list of frequencies
decay Exponential decay parameter for lowering weight of large IADs
smear Boxcar smoothing width in Angstroms
error Return error value
Returns
Whether or not the operation could be performed.
Definition at line 1302 of file structure.cpp.
References compareIADDistributions().
compareIADDistributions [3/3]
bool GlobalSearch::Structure::compareIADDistributions (const std::vector< double > & d, const std::vector< double > & f1, const std::vector< double > & f2, double decay, double smear, double * error) static slot
Compare two IAD histograms.
Given two histograms over the same range with the same step, this function calculates an error value to measure the differences between the two. A boxcar smoothing is performed using a width of "smear", and an optional weight can be applied. The weight is a standard exponential decay with a halflife of "decay".
Parameters
d List of distances
f1 First list of frequencies
f2 Second list of frequencies
decay Exponential decay parameter for lowering weight of large IADs
smear Boxcar smoothing width in Angstroms
error Return error value
Returns
Whether or not the operation could be performed.
Definition at line 1211 of file structure.cpp.
Referenced by compareIADDistributions(), and compareIADDistributions().
copyFiles()
std::vector< std::string > GlobalSearch::Structure::copyFiles () const inline
Get the extra files to be copied to the working dir.
Returns
A vector of the names (including paths) of files to be copied to the structure's working directory.
Definition at line 792 of file structure.h.
Referenced by GlobalSearch::LocalQueueInterface::writeFiles().
countStructuresOfEachFormulaUnit()
QList< uint > GlobalSearch::Structure::countStructuresOfEachFormulaUnit (QList< Structure * > * structures, int maxFU) static
Definition at line 1591 of file structure.cpp.
deleteFromHistory()
void GlobalSearch::Structure::deleteFromHistory (unsigned int index) virtual
Parameters
index Index of entry to remove from structure's history.
Definition at line 766 of file structure.cpp.
References sizeOfHistory().
enableAutoHistogramGeneration
void GlobalSearch::Structure::enableAutoHistogramGeneration (bool b) virtual slot
Set whether the default histogram generation should be performed (default is off)
Definition at line 91 of file structure.cpp.
featureOutputExists
void GlobalSearch::Structure::featureOutputExists () signal
Emitted when a feature's output file is found for a structure
fileName()
QString GlobalSearch::Structure::fileName () const inline
Returns
The file name.
See also
setFilename
Definition at line 364 of file structure.h.
Referenced by GlobalSearch::LocalQueueInterface::checkIfFileExists(), GlobalSearch::LocalQueueInterface::fetchFile(), GlobalSearch::OptBase::finishFeatureCalculations(), GlobalSearch::LocalQueueInterface::grepFile(), GlobalSearch::OptBase::interpretKeyword_base(), GlobalSearch::Optimizer::load(), GlobalSearch::LocalQueueInterface::logErrorDirectory(), GlobalSearch::OptBase::save(), GlobalSearch::OptBase::startFeatureCalculations(), GlobalSearch::LocalQueueInterface::startJob(), GlobalSearch::Optimizer::update(), GlobalSearch::LocalQueueInterface::writeFiles(), and writeStructureSettings().
generateDefaultHistogram
void GlobalSearch::Structure::generateDefaultHistogram () virtual slot
Generate default histogram data (0:10 A, 0.01 A step)
See also
isHistogramGenerationPending()
getDefaultHistogram()
Definition at line 1040 of file structure.cpp.
References generateIADHistogram().
Referenced by requestHistogramGeneration().
generateIADHistogram() [1/2]
bool GlobalSearch::Structure::generateIADHistogram (QList< double > * distance, QList< double > * frequency, double min = 0.0, double max = 10.0, double step = 0.01, const GlobalSearch::Atom & atom = Atom()) const virtual
Generate data for a histogram of the distances between all atoms, or between one atom and all others.
If the parameter atom is specified, the resulting data will represent the distance distribution between that atom and all others. If omitted (or nullptr), a histogram of all interatomic distances is calculated.
Useful for estimating the coordination number of an atom from a plot.
Warning
This algorithm is not thoroughly tested and should not be relied upon. It is merely an estimation.
Returns
true if the operation makes sense for this Structure, false otherwise (i.e. fewer than one atom present)
Parameters
distance List of distance values for the histogram bins.
frequency Number of Atoms within the corresponding distance bin.
min Value of starting histogram distance.
max Value of ending histogram distance.
step Increment between bins.
atom Optional: Atom to calculate distances from.
See also
getShortestInteratomicDistance
requestHistogramGeneration
getNearestNeighborDistance
Definition at line 1064 of file structure.cpp.
References generateIADHistogram().
Referenced by generateDefaultHistogram(), and generateIADHistogram().
generateIADHistogram() [2/2]
bool GlobalSearch::Structure::generateIADHistogram (QList< QVariant > * distance, QList< QVariant > * frequency, double min = 0.0, double max = 10.0, double step = 0.01, const GlobalSearch::Atom & atom = Atom()) const virtual
Generate data for a histogram of the distances between all atoms, or between one atom and all others.
If the parameter atom is specified, the resulting data will represent the distance distribution between that atom and all others. If omitted (or nullptr), a histogram of all interatomic distances is calculated.
Useful for estimating the coordination number of an atom from a plot.
Warning
This algorithm is not thoroughly tested and should not be relied upon. It is merely an estimation.
Returns
true if the operation makes sense for this Structure, false otherwise (i.e. fewer than one atom present)
Parameters
distance List of distance values for the histogram bins.
frequency Number of Atoms within the corresponding distance bin.
min Value of starting histogram distance.
max Value of ending histogram distance.
step Increment between bins.
atom Optional: Atom to calculate distances from.
See also
getShortestInteratomicDistance
requestHistogramGeneration
getNearestNeighborDistance
Definition at line 1135 of file structure.cpp.
getAtomCoordsFrac()
QList< Vector3 > GlobalSearch::Structure::getAtomCoordsFrac () const
Returns
Fractional atom coordinates. The atoms are ordered in the same ordering you would get from getSymbols().
Definition at line 1355 of file structure.cpp.
References getSymbols().
getCurrentOptStep()
uint GlobalSearch::Structure::getCurrentOptStep () inline
Returns
The current optimization step of the Structure.
See also
setCurrentOptStep
Definition at line 375 of file structure.h.
Referenced by GlobalSearch::Optimizer::checkForSuccessfulOutput(), GlobalSearch::Optimizer::checkIfOutputFileExists(), GlobalSearch::QueueManager::checkPopulation(), GlobalSearch::OptBase::finishFeatureCalculations(), GlobalSearch::QueueInterface::getCurrentOptimizer(), GlobalSearch::Optimizer::getInterpretedTemplates(), GlobalSearch::OptBase::interpretKeyword_base(), readStructureSettings(), GlobalSearch::OptBase::save(), GlobalSearch::OptBase::startFeatureCalculations(), GlobalSearch::QueueManager::startJob(), GlobalSearch::QueueManager::stopJob(), GlobalSearch::Optimizer::update(), GlobalSearch::QueueInterface::writeInputFiles(), and writeStructureSettings().
getDefaultHistogram() [1/2]
void GlobalSearch::Structure::getDefaultHistogram (QList< double > * dist, QList< double > * freq) const virtual
Get the default histogram data.
Definition at line 1046 of file structure.cpp.
getDefaultHistogram() [2/2]
void GlobalSearch::Structure::getDefaultHistogram (QList< QVariant > * dist, QList< QVariant > * freq) const virtual
Get the default histogram data.
Definition at line 1057 of file structure.cpp.
getDuplicateString()
QString GlobalSearch::Structure::getDuplicateString () const inline
Returns
A string naming the Structure that this Structure is a duplicate of.
See also
setDuplicateString
Definition at line 342 of file structure.h.
getEnergy()
double GlobalSearch::Structure::getEnergy () const inline
Return the energy value of the structure in eV.
Returns
The energy of the structure in eV.
See also
setEnthalpy
hasEnthalpy
setPV
getPV
setEnergy
getEnergy
Definition at line 234 of file structure.h.
Referenced by getEnthalpy(), and writeCurrentStructureInfo().
getEnthalpy()
double GlobalSearch::Structure::getEnthalpy () const inline
Return the enthalpy value of the structure in eV.
Note
If the enthalpy is not set but the energy is set, this function assumes that the system is at zero-pressure and returns the energy.
Returns
The enthalpy of the structure in eV.
See also
setEnthalpy
hasEnthalpy
setPV
getPV
setEnergy
getEnergy
Definition at line 250 of file structure.h.
References getEnergy().
Referenced by getFingerprint(), getResultsEntry(), rankByEnthalpy(), sortByEnthalpy(), and writeCurrentStructureInfo().
getEnthalpyPerAtom()
double GlobalSearch::Structure::getEnthalpyPerAtom () const inline
Definition at line 262 of file structure.h.
getEnthalpyPerFU()
double GlobalSearch::Structure::getEnthalpyPerFU () const inline
Definition at line 257 of file structure.h.
getFailCount()
uint GlobalSearch::Structure::getFailCount () inline
Returns
The number of times this Structure has failed the current optimization step.
See also
setFailCount
addFailure
resetFailCount
Definition at line 383 of file structure.h.
Referenced by addFailure(), GlobalSearch::QueueManager::checkPopulation(), and writeStructureSettings().
getFingerprint()
QHash< QString, QVariant > GlobalSearch::Structure::getFingerprint () const virtual
A "fingerprint" hash of the structure. Returns "enthalpy" key with the enthalpy value as a double wrapped in a QVariant. May be extended in derived classes.
Used for checking if two Structures are similar enough to be marked as duplicates.
Returns
A hash of key/value pairs containing data that is representative of the Structure.
Definition at line 1456 of file structure.cpp.
References getEnthalpy().
getFixCount()
int GlobalSearch::Structure::getFixCount () const inline
Return the number of times the structure has had the atoms moved to fix the structure to pass the IAD check.
See also
setFixCount
Definition at line 222 of file structure.h.
getFormulaUnits()
uint GlobalSearch::Structure::getFormulaUnits () const
Definition at line 1579 of file structure.cpp.
getGeneration()
uint GlobalSearch::Structure::getGeneration () const inline
Returns the generation number of the structure. Only useful for genetic/evolutionary algorithms.
Returns
Generation number
See also
setGeneration
getIDNumber
getIndex
setIDNumber
setIndex
getIDString
Definition at line 303 of file structure.h.
Referenced by GlobalSearch::OptBase::_finishHardnessCalculation(), GlobalSearch::OptBase::calculateHardness(), GlobalSearch::Optimizer::checkForSuccessfulOutput(), getIDString(), getResultsEntry(), GlobalSearch::OptBase::interpretKeyword_base(), GlobalSearch::LocalQueueInterface::logErrorDirectory(), GlobalSearch::QueueManager::startJob(), and writeStructureSettings().
getIDNumber()
uint GlobalSearch::Structure::getIDNumber () const inline
Returns an ID number associated with the Structure.
Note
If a generation number is used as well, this may not be unique.
Returns
Identification number
See also
setGeneration
getGeneration
getIndex
setIDNumber
setIndex
getIDString
Definition at line 317 of file structure.h.
Referenced by GlobalSearch::OptBase::_finishHardnessCalculation(), GlobalSearch::OptBase::calculateHardness(), GlobalSearch::Optimizer::checkForSuccessfulOutput(), getIDString(), getResultsEntry(), GlobalSearch::OptBase::interpretKeyword_base(), GlobalSearch::LocalQueueInterface::logErrorDirectory(), GlobalSearch::QueueManager::startJob(), and writeStructureSettings().
getIDString()
QString GlobalSearch::Structure::getIDString () const inline
Returns a unique identification string. Defaults to [generation]x[IDNumber]. Handy for debugging/error output.
Returns
Unique identification string.
See also
setGeneration
getGeneration
setIndex
getIndex
setIDNumber
getIDNumber
Definition at line 428 of file structure.h.
References getGeneration(), and getIDNumber().
Referenced by GlobalSearch::OptBase::finishFeatureCalculations(), GlobalSearch::LocalQueueInterface::getStatus(), GlobalSearch::Optimizer::read(), GlobalSearch::OptBase::startFeatureCalculations(), GlobalSearch::QueueManager::startJob(), GlobalSearch::LocalQueueInterface::startJob(), GlobalSearch::QueueManager::unlockForNaming(), and GlobalSearch::Optimizer::update().
getIndex()
int GlobalSearch::Structure::getIndex () const inline
Returns a unique ID number associated with the Structure. This is typically assigned in order of introduction to a tracker.
Returns
Unique identification number
See also
setGeneration
getGeneration
getIndex
setIDNumber
getIDNumber
getIDString
Definition at line 330 of file structure.h.
Referenced by writeStructureSettings().
getJobID()
uint GlobalSearch::Structure::getJobID () const inline
Returns the Job ID of the Structure's current running optimization. Returns zero is not running.
Returns
Job ID of the structure's optimization process.
See also
setJobID
Definition at line 291 of file structure.h.
Referenced by GlobalSearch::LocalQueueInterface::getStatus(), GlobalSearch::LocalQueueInterface::startJob(), GlobalSearch::LocalQueueInterface::stopJob(), and writeStructureSettings().
getNearestNeighborDistance() [1/2]
bool GlobalSearch::Structure::getNearestNeighborDistance (const double x, const double y, const double z, double & shortest) const virtual
Find the distance to the nearest atom from a specified point.
Useful for checking if an atom will be too close to another atom before adding it.
Returns
true if the operation makes sense for this Structure, false otherwise (i.e. fewer than one atom present)
Parameters
x Cartesian coordinate
y Cartesian coordinate
z Cartesian coordinate
shortest An empty double to be overwritten with the nearest neighbor distance.
See also
getShortestInteratomicDistance
getNearestNeighborHistogram
getNeighbors
Definition at line 962 of file structure.cpp.
Referenced by addAtomRandomly(), getNearestNeighborDistance(), and getNearestNeighborDistances().
getNearestNeighborDistance() [2/2]
bool GlobalSearch::Structure::getNearestNeighborDistance (const GlobalSearch::Atom & atom, double & shortest) const virtual
Find the nearest neighbor distance of a specified atom.
Returns
true if the operation makes sense for this Structure, false otherwise (i.e. fewer than one atom present)
Parameters
atom Atom of interest
shortest An empty double to be overwritten with the nearest neighbor distance.
See also
getShortestInteratomicDistance
getNearestNeighborHistogram
getNeighbors
Definition at line 989 of file structure.cpp.
References getNearestNeighborDistance().
getNearestNeighborDistances()
bool GlobalSearch::Structure::getNearestNeighborDistances (QList< double > * list) const virtual
Find the smallest separation between all atoms in the Structure.
Returns
true if the operation makes sense for this Structure, false otherwise (i.e. fewer than two atoms present)
Parameters
list list of distances in Angstrom
See also
getNearestNeighborDistance
getNearestNeighborHistogram
getNeighbors
Definition at line 913 of file structure.cpp.
References getNearestNeighborDistance().
getNeighbors() [1/2]
QList< Atom > GlobalSearch::Structure::getNeighbors (const double x, const double y, const double z, const double cutoff, QList< double > * distances = 0) const
Returns
a list of all atoms within cutoff of (x,y,z) and, optionally, their distances.
Definition at line 997 of file structure.cpp.
Referenced by getNeighbors().
getNeighbors() [2/2]
QList< Atom > GlobalSearch::Structure::getNeighbors (const GlobalSearch::Atom & atom, const double cutoff, QList< double > * distances = 0) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
a list of all atoms within cutoff of atom and, optionally, their distances.
Definition at line 1022 of file structure.cpp.
References getNeighbors().
getNumberOfAtomsAlpha()
QList< uint > GlobalSearch::Structure::getNumberOfAtomsAlpha () const
Returns
A list of the number of species present that corresponds to the symbols listed in getSymbols().
See also
getSymbols
Definition at line 1336 of file structure.cpp.
References getSymbols().
getOptElapsed()
QString GlobalSearch::Structure::getOptElapsed () const
Returns
A string formated "HH:MM:SS" indicating the amount of time spent in the current optimization step
See also
setOptTimerStart
getOptTimerStart
setOptTimerEnd
getOptTimerEnd
startOptTimer
stopOptTimer
Definition at line 1375 of file structure.cpp.
References getOptElapsedSeconds().
getOptElapsedHours()
double GlobalSearch::Structure::getOptElapsedHours () const
Returns
Get the amount of hours elapsed as a double.
Definition at line 1396 of file structure.cpp.
References getOptElapsedSeconds().
getOptElapsedSeconds()
int GlobalSearch::Structure::getOptElapsedSeconds () const
Returns
Get the amount of seconds elapsed as an int.
Definition at line 1386 of file structure.cpp.
Referenced by getOptElapsed(), and getOptElapsedHours().
getOptTimerEnd()
QDateTime GlobalSearch::Structure::getOptTimerEnd () const inline
Returns
The time that the current optimization step ended.
See also
getOptTimerStart
startOptTimer
stopOptTimer
setOptTimerStart
setOptTimerEnd
getOptElapsed
Definition at line 416 of file structure.h.
Referenced by writeStructureSettings().
getOptTimerStart()
QDateTime GlobalSearch::Structure::getOptTimerStart () const inline
Returns
The time that the current optimization step started.
See also
getOptTimerEnd
startOptTimer
stopOptTimer
setOptTimerStart
setOptTimerEnd
getOptElapsed
Definition at line 406 of file structure.h.
Referenced by writeStructureSettings().
getParents()
QString GlobalSearch::Structure::getParents () const inline
Returns
a string describing the ancestory of the Structure.
See also
setParents
Definition at line 353 of file structure.h.
Referenced by writeStructureSettings().
getParentStructure()
Structure * GlobalSearch::Structure::getParentStructure () const inline
Returns
A pointer for the parent structure of a given structure
Definition at line 390 of file structure.h.
getPreoptBonding()
const std::vector< Bond > & GlobalSearch::Structure::getPreoptBonding () const inline
Get the vector of preoptimization bonding information. This will be used to assign bonds to be the same as that before optimization. Note that the pre-optimization atom ordering MUST be the same as the post-optimization atom ordering.
Returns
The vector of preoptimization bonding information.
Definition at line 855 of file structure.h.
Referenced by updateAndAddToHistory().
getPV()
double GlobalSearch::Structure::getPV () const inline
Returns the value PV term from an enthalpy calculation (H = U
PV) in eV.
Returns
The PV term in eV.
See also
getEnthalpy
setEnthalpy
hasEnthalpy
setPV
setEnergy
getEnergy
Definition at line 278 of file structure.h.
Referenced by writeCurrentStructureInfo().
getRank()
uint GlobalSearch::Structure::getRank () const inline
Returns an energetic ranking set by setRank(uint).
Returns
the energetic ranking.
See also
setRank
Definition at line 284 of file structure.h.
Referenced by getResultsEntry(), and writeStructureSettings().
getRempath()
QString GlobalSearch::Structure::getRempath () const inline
Returns
The path on the remote server to write this Structure for optimization.
See also
setRempath
Definition at line 359 of file structure.h.
Referenced by GlobalSearch::OptBase::finishFeatureCalculations(), GlobalSearch::OptBase::interpretKeyword_base(), GlobalSearch::OptBase::startFeatureCalculations(), and writeStructureSettings().
getResultsEntry()
QString GlobalSearch::Structure::getResultsEntry (bool includeHardness, int features_num, int optstep) const virtual
This function is changed for multi-objective case // SH
Returns
A structure-specific entry for a results printout
See also
getResultsHeader
OptBase::save
Definition at line 847 of file structure.cpp.
References Duplicate, Empty, Error, FeatureCalculation, FeatureDismiss, FeatureFail, FeatureRetain, getEnthalpy(), getGeneration(), getIDNumber(), getRank(), getStatus(), getStrucFeatNumber(), InProcess, Killed, Optimized, Removed, skippedOptimization(), StepOptimized, Submitted, Supercell, Updating, vickersHardness(), and WaitingForOptimization.
Referenced by GlobalSearch::OptBase::save().
getResultsHeader()
virtual QString GlobalSearch::Structure::getResultsHeader (bool includeHardness, int features_num) const inline virtual
Returns
A header line for a results printout
See also
getResultsEntry
OptBase::save
Definition at line 437 of file structure.h.
getShortestInteratomicDistance()
bool GlobalSearch::Structure::getShortestInteratomicDistance (double & shortest) const virtual
Return a list of nearest neighbor distances for each atom in the Structure
Returns
true if the operation makes sense for this Structure, false otherwise (i.e. fewer than two atoms present)
Parameters
shortest An empty double to be overwritten with the shortest interatomic distance.
See also
getNearestNeighborDistance
getNearestNeighborHistogram
getNeighbors
Definition at line 934 of file structure.cpp.
getStatus()
State GlobalSearch::Structure::getStatus () const inline
Returns
The current status of the Structure.
See also
setStatus
State
Definition at line 370 of file structure.h.
Referenced by GlobalSearch::QueueManager::checkExit(), GlobalSearch::QueueManager::checkPopulation(), GlobalSearch::QueueManager::checkRunning(), GlobalSearch::QueueManager::getAllDuplicateStructures(), GlobalSearch::QueueManager::getAllOptimizedStructures(), GlobalSearch::QueueManager::getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit(), GlobalSearch::QueueManager::getAllSupercellStructures(), getResultsEntry(), GlobalSearch::LocalQueueInterface::getStatus(), GlobalSearch::QueueManager::killStructure(), GlobalSearch::LocalQueueInterface::stopJob(), and writeStructureSettings().
getStrucFeatFailCt()
int GlobalSearch::Structure::getStrucFeatFailCt () const inline
Definition at line 173 of file structure.h.
getStrucFeatNumber()
int GlobalSearch::Structure::getStrucFeatNumber () const inline
Multi-objective read/write functions for a structure
Definition at line 170 of file structure.h.
Referenced by getResultsEntry(), and writeStructureSettings().
getStrucFeatStatus()
FeatStatus GlobalSearch::Structure::getStrucFeatStatus () const inline
Definition at line 172 of file structure.h.
getStrucFeatValues()
double GlobalSearch::Structure::getStrucFeatValues (int i) const inline
Definition at line 171 of file structure.h.
getStrucFeatValuesVec()
QList< double > GlobalSearch::Structure::getStrucFeatValuesVec () inline
Definition at line 181 of file structure.h.
getStrucHistFeatFailCt()
int GlobalSearch::Structure::getStrucHistFeatFailCt (int i) inline
Definition at line 189 of file structure.h.
getStrucHistFeatNumber()
int GlobalSearch::Structure::getStrucHistFeatNumber () inline
Definition at line 186 of file structure.h.
getStrucHistFeatStatus()
FeatStatus GlobalSearch::Structure::getStrucHistFeatStatus (int i) inline
Definition at line 188 of file structure.h.
getStrucHistFeatValues()
QList< double > GlobalSearch::Structure::getStrucHistFeatValues (int i) inline
Definition at line 187 of file structure.h.
getSupercellString()
QString GlobalSearch::Structure::getSupercellString () const inline
Returns
A string naming the Structure that this Structure is a supercell of.
See also
setSupercellString
Definition at line 348 of file structure.h.
Referenced by GlobalSearch::QueueManager::getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit().
getSymbols()
QList< QString > GlobalSearch::Structure::getSymbols () const
Returns
An alphabetized list of the atomic symbols for the atomic species present in the Structure.
See also
getNumberOfAtomsAlpha
Definition at line 1321 of file structure.cpp.
Referenced by getAtomCoordsFrac(), getNumberOfAtomsAlpha(), and GlobalSearch::OptBase::interpretKeyword_base().
hasChangedSinceDupChecked()
bool GlobalSearch::Structure::hasChangedSinceDupChecked () inline
Structure can track if it has changed since it was last checked in a duplicate finding routine. This is useful for cutting down on the number of comparisons needed.
Must call setupConnections() before using this function.
See also
setChangedSinceDupChecked()
Definition at line 722 of file structure.h.
hasEnthalpy()
bool GlobalSearch::Structure::hasEnthalpy () const inline
Whether the Structure has an enthalpy value set.
Returns
true if enthalpy has been set, false otherwise
See also
setEnthalpy
getEnthalpy
setPV
getPV
setEnergy
getEnergy
Definition at line 203 of file structure.h.
hasParentStructure()
bool GlobalSearch::Structure::hasParentStructure () const inline
Return whether or not this structure has a parent structure saved.
Returns
Returns true if a parent structure is saved, and false if a parent structure is not saved.
Definition at line 209 of file structure.h.
Referenced by writeStructureSettings().
isHistogramGenerationPending()
virtual bool GlobalSearch::Structure::isHistogramGenerationPending () const inline virtual
Returns
True is histogram generation is pending.
Definition at line 562 of file structure.h.
load()
void GlobalSearch::Structure::load (QTextStream & in) virtual
Load data into Structure.
Attention
Do not use this function in new code, as it has been replaced by readSettings. Old code should be rewritten to use readSettings as well.
Deprecated:
Use readSettings instead, and call this only as a backup for outdates .state files
Parameters
in QTextStream containing load data.
See also
readSettings
Definition at line 1401 of file structure.cpp.
References InProcess, setCurrentOptStep(), setFailCount(), setGeneration(), setIDNumber(), setIndex(), setJobID(), setOptTimerEnd(), setOptTimerStart(), setParents(), setRank(), setRempath(), and setStatus().
Referenced by operator=(), and readStructureSettings().
lock()
QReadWriteLock & GlobalSearch::Structure::lock () inline
Provides locking. Should be used before reading or writing to the structure.
Definition at line 336 of file structure.h.
Referenced by GlobalSearch::OptBase::_finishHardnessCalculation(), GlobalSearch::QueueManager::checkExit(), GlobalSearch::QueueManager::checkPopulation(), GlobalSearch::QueueManager::checkRunning(), GlobalSearch::Tracker::deleteAllStructures(), GlobalSearch::OptBase::finishFeatureCalculations(), GlobalSearch::QueueManager::getAllDuplicateStructures(), GlobalSearch::QueueManager::getAllOptimizedStructures(), GlobalSearch::QueueManager::getAllOptimizedStructuresAndOneSupercellCopyForEachFormulaUnit(), GlobalSearch::QueueManager::getAllSupercellStructures(), GlobalSearch::Optimizer::getInterpretedTemplates(), GlobalSearch::LocalQueueInterface::getStatus(), GlobalSearch::QueueManager::killStructure(), GlobalSearch::Optimizer::load(), rankByEnthalpy(), GlobalSearch::OptBase::save(), sortByEnthalpy(), sortByVickersHardness(), GlobalSearch::OptBase::startFeatureCalculations(), GlobalSearch::QueueManager::startJob(), GlobalSearch::LocalQueueInterface::stopJob(), GlobalSearch::Optimizer::update(), and GlobalSearch::QueueManager::updateStructureFeatureStatus().
operator=() [1/3]
Structure & GlobalSearch::Structure::operator= (const GlobalSearch::Molecule & other)
Assignment operator. Makes a new structure with all Molecule specific information copied from other.
Definition at line 190 of file structure.cpp.
operator=() [2/3]
Structure & GlobalSearch::Structure::operator= (const Structure & other)
Assignment operator. Makes a new structure with all Structure specific information copied from other.
Definition at line 101 of file structure.cpp.
References load().
operator=() [3/3]
Structure & GlobalSearch::Structure::operator= (Structure && other) noexcept
Move assignment operator.
Definition at line 144 of file structure.cpp.
perceiveBonds()
void GlobalSearch::Structure::perceiveBonds ()
Use the atoms' covalent radii to automatically generate bonds.
Definition at line 658 of file structure.cpp.
rankByEnthalpy()
void GlobalSearch::Structure::rankByEnthalpy (const QList< Structure * > & structures) static
Rank the listed structures by their enthalpies
Parameters
structures List of structures to assign ranks
See also
sortEnthalpies
sortAndRankByEnthalpy
setRank
getRank
Definition at line 1529 of file structure.cpp.
References getEnthalpy(), and lock().
readCurrentStructureInfo
void GlobalSearch::Structure::readCurrentStructureInfo (const QString & filename) protected slot
Read current data concerning a structure from a file. Data includes enthalpy, energy, cell vectors, and atom info
Parameters
filename Filename to read data from.
See also
writeSettings
readSettings
Definition at line 598 of file structure.cpp.
References setEnergy(), setEnthalpy(), and setPV().
Referenced by readStructureSettings().
readSettings()
virtual void GlobalSearch::Structure::readSettings (const QString & filename, const bool readCurrentInfo = false) inline virtual
Read supplementary data about this Structure from a file. All data that is not stored in the readable optimizer output file should be read here.
If reimplementing this in a derived class, call readStructureSettings(filename) to read inherited data.
Parameters
filename Filename to read data from.
readCurrentInfo Update the current info of the structure? Note: readCurrentInfo will also set a unit cell. The code may need to be changed slightly for reading current info for non-periodic structures
See also
readStructureSettings
writeSettings
Definition at line 1050 of file structure.h.
References readStructureSettings().
readStructureSettings
void GlobalSearch::Structure::readStructureSettings (const QString & filename, const bool readCurrentInfo = false) protected slot
Read data concerning the Structure class from a file.
Parameters
filename Filename to read data from.
readCurrentInfo Update the current info of the structure? Note: this will also set a unit cell. The code may need to be changed slightly for reading current info for non-periodic structures
See also
writeSettings
readSettings
Definition at line 351 of file structure.cpp.
References getCurrentOptStep(), load(), readCurrentStructureInfo(), setBulkModulus(), setCurrentOptStep(), setFailCount(), setFileName(), setGeneration(), setIDNumber(), setIndex(), setJobID(), setOptTimerEnd(), setOptTimerStart(), setParents(), setPreoptBonding(), setPrimitiveChecked(), setRank(), setRempath(), setReusePreoptBonding(), setShearModulus(), setSkippedOptimization(), setStatus(), setSupercellGenerationChecked(), and setVickersHardness().
Referenced by readSettings().
requestHistogramGeneration
void GlobalSearch::Structure::requestHistogramGeneration () virtual slot
Request that histogram data be regenerated. This is connected to Molecule::update() and calls generateDefaultHistogram(). This function is throttled to only run every 250 ms.
Definition at line 1031 of file structure.cpp.
References generateDefaultHistogram().
resetEnergy()
void GlobalSearch::Structure::resetEnergy () inline
Reset the Structure's energy to zero
See also
setEnergy
getEnergy
Definition at line 1181 of file structure.h.
resetEnthalpy()
void GlobalSearch::Structure::resetEnthalpy () inline
Reset the Structure's enthalpy and PV term to zero and clear hasEnthalpy()
See also
setEnthalpy
getEnthalpy
hasEnthalpy
setPV
getPV
Definition at line 1170 of file structure.h.
resetFailCount()
void GlobalSearch::Structure::resetFailCount () inline
Reset the number of times this Structure has failed the current optimization step.
See also
addFailure
setFailCount
getFailCount
Definition at line 1285 of file structure.h.
References setFailCount().
Referenced by Structure().
resetStrucFeat()
void GlobalSearch::Structure::resetStrucFeat () inline
Definition at line 178 of file structure.h.
resetStrucHistFeat()
void GlobalSearch::Structure::resetStrucHistFeat () inline
Definition at line 183 of file structure.h.
retrieveHistoryEntry()
void GlobalSearch::Structure::retrieveHistoryEntry (unsigned int index, QList< unsigned int > * atomicNums, QList< Vector3 > * coords, double * energy, double * enthalpy, Matrix3 * cell) virtual
This function is used to retrieve data from the structure's history. All non-zero pointers will be modified to contain the information at the specified index of the history.
Parameters
index Entry in history to return
atomicNums Pointer to a list that will be filled with atomic numbers. Can be zero if this is not needed.
coords Pointer to a list that will be filled with cartesian atomic coordinates. Can be zero if this is not needed.
energy Pointer to a double that will contain the entry's energy in eV. Can be zero if this is not needed.
enthalpy Pointer to a double that will contain the entry's enthalpy in eV. Can be zero if this is not needed.
cell Pointer to an Eigen::Matrix3f filled with the unit cell vectors (row vectors). Can be zero if this is not needed.
Note
If the system is not periodic, the cell matrix will be a zero matrix. Use Matrix3::isZero() to test for a valid cell.
Definition at line 779 of file structure.cpp.
References sizeOfHistory().
reusePreoptBonding()
bool GlobalSearch::Structure::reusePreoptBonding () inline
Whether or not to re-use the bonding information from before the optimization occurred. The atom order after optimization MUST be the same as the input atom order for optimization.
Returns
True if we are to use pre-optimization bonding. False if we should not.
Definition at line 832 of file structure.h.
Referenced by updateAndAddToHistory(), and writeStructureSettings().
setBulkModulus()
void GlobalSearch::Structure::setBulkModulus (double d) inline
Set the bulk modulus (usually calculated via aflow machine learning).
Parameters
d The bulk modulus.
Definition at line 884 of file structure.h.
Referenced by GlobalSearch::OptBase::_finishHardnessCalculation(), and readStructureSettings().
setChangedSinceDupChecked()
void GlobalSearch::Structure::setChangedSinceDupChecked (bool b) inline
Structure can track if it has changed since it was last checked in a duplicate finding routine. This is useful for cutting down on the number of comparisons needed.
Must call setupConnections() before using this function.
See also
hasChangedSinceDupChecked()
Definition at line 1316 of file structure.h.
setCurrentOptStep()
void GlobalSearch::Structure::setCurrentOptStep (uint i) inline
Parameters
i The current optimization step of the Structure.
See also
getCurrentOptStep
Definition at line 1261 of file structure.h.
Referenced by load(), and readStructureSettings().
setDuplicateString()
void GlobalSearch::Structure::setDuplicateString (const QString & s) inline
Parameters
s A string naming the Structure that this Structure is a duplicate of.
See also
getDuplicateString
Definition at line 1300 of file structure.h.
setEnergy()
void GlobalSearch::Structure::setEnergy (double energy) inline
Set the energy in eV.
Parameters
energy The Structure's energy in eV.
See also
getEnergy
Definition at line 1143 of file structure.h.
Referenced by readCurrentStructureInfo().
setEnthalpy()
void GlobalSearch::Structure::setEnthalpy (double enthalpy) inline
Set the enthalpy of the Structure.
Parameters
enthalpy The Structure's enthalpy
See also
getEnthalpy
Definition at line 1149 of file structure.h.
Referenced by readCurrentStructureInfo().
setFailCount()
void GlobalSearch::Structure::setFailCount (uint count) inline
Parameters
count The number of times this Structure has failed the current optimization step.
See also
addFailure
getFailCount
resetFailCount
Definition at line 1269 of file structure.h.
Referenced by addFailure(), load(), readStructureSettings(), and resetFailCount().
setFileName()
void GlobalSearch::Structure::setFileName (const QString & p) inline
Parameters
p The file name.
See also
fileName
Definition at line 1250 of file structure.h.
Referenced by readStructureSettings().
setFixCount()
void GlobalSearch::Structure::setFixCount (int fixCount) inline
Set the number of times the structures has had the atoms moved to pass the IAD check.
See also
getFixCount
Definition at line 1137 of file structure.h.
setGeneration()
void GlobalSearch::Structure::setGeneration (uint gen) inline
Set the generation number of the Structure.
Parameters
gen The generation number.
See also
setGeneration
getGeneration
setIndex
getIndex
setIDNumber
getIDNumber
getIDString
Definition at line 1205 of file structure.h.
Referenced by load(), and readStructureSettings().
setIDNumber()
void GlobalSearch::Structure::setIDNumber (uint id) inline
Set the ID number associated with the Structure.
Note
If a generation number is used as well, this may not be unique.
Returns
Identification number
See also
setGeneration
getGeneration
setIndex
getIndex
getIDNumber
getIDString
Definition at line 1219 of file structure.h.
Referenced by load(), and readStructureSettings().
setIndex()
void GlobalSearch::Structure::setIndex (int index) inline
Set a unique ID number associated with the Structure. This is typically assigned in order of introduction to a tracker.
Note
If a generation number is used as well, this may not be unique.
Parameters
index Identification number
See also
setGeneration
getGeneration
getIndex
setIDNumber
getIDNumber
getIDString
Definition at line 1234 of file structure.h.
Referenced by load(), readStructureSettings(), and GlobalSearch::OptBase::save().
setJobID()
void GlobalSearch::Structure::setJobID (uint id) inline
Set the Job ID of the current optimization process.
Parameters
id The current optimization process's Job ID.
See also
getJobID
Definition at line 1193 of file structure.h.
Referenced by load(), readStructureSettings(), GlobalSearch::LocalQueueInterface::startJob(), GlobalSearch::LocalQueueInterface::stopJob(), and GlobalSearch::Optimizer::update().
setOptTimerEnd()
void GlobalSearch::Structure::setOptTimerEnd (const QDateTime & d) inline
Parameters
d The time that the current optimization process stopped.
See also
setOptTimerStart
getOptTimerStart
getOptTimerEnd
startOptTimer
stopOptTimer
getOptElapsed
Definition at line 1401 of file structure.h.
Referenced by load(), and readStructureSettings().
setOptTimerStart()
void GlobalSearch::Structure::setOptTimerStart (const QDateTime & d) inline
Parameters
d The time that the current optimization process started.
See also
getOptTimerStart
setOptTimerEnd
getOptTimerEnd
startOptTimer
stopOptTimer
getOptElapsed
Definition at line 1389 of file structure.h.
Referenced by load(), and readStructureSettings().
setParents()
void GlobalSearch::Structure::setParents (const QString & p) inline
Parameters
p A string describing the ancestory of the Structure.
See also
getParents
Definition at line 1239 of file structure.h.
Referenced by load(), and readStructureSettings().
setParentStructure()
void GlobalSearch::Structure::setParentStructure (Structure * structure) inline
Set the parent structure for this structure
Definition at line 1273 of file structure.h.
setPreoptBonding()
void GlobalSearch::Structure::setPreoptBonding (const std::vector< Bond > & v) inline
Set the preopt bonding information to be used when updating the structure.
Parameters
v The vector of bonding information via atom indices.
Definition at line 845 of file structure.h.
Referenced by readStructureSettings().
setPrimitiveChecked()
void GlobalSearch::Structure::setPrimitiveChecked (bool b) inline
Structure tracks if it has been primitive-checked or not. Primitive checking involves running the primitive reduction function to see if a smaller FU primitive structure can be made.
See also
wasPrimitiveChecked()
Definition at line 1325 of file structure.h.
Referenced by readStructureSettings().
setPV()
void GlobalSearch::Structure::setPV (double pv) inline
Set the PV term of the Structure's enthalpy (see getPV()).
Parameters
pv The PV term
See also
getPV
Definition at line 1160 of file structure.h.
Referenced by readCurrentStructureInfo().
setRank()
void GlobalSearch::Structure::setRank (uint rank) inline
Set the Structure's energetic ranking.
Parameters
rank The Structure's energetic ranking.
See also
getRank
Definition at line 1187 of file structure.h.
Referenced by load(), and readStructureSettings().
setRempath()
void GlobalSearch::Structure::setRempath (const QString & p) inline
Parameters
p The path on the remote server to write this Structure for optimization.
See also
getRempath
Definition at line 1245 of file structure.h.
Referenced by load(), and readStructureSettings().
setReusePreoptBonding()
void GlobalSearch::Structure::setReusePreoptBonding (bool b) inline
Whether or not to re-use the bonding information from before the optimization occurred. The atom order after optimization MUST be the same as the input atom order for optimization.
Parameters
b True if we are to use pre-optimization bonding. False if we should not.
Definition at line 822 of file structure.h.
Referenced by readStructureSettings().
setShearModulus()
void GlobalSearch::Structure::setShearModulus (double d) inline
Set the shear modulus (usually calculated via aflow machine learning).
Parameters
d The shear modulus.
Definition at line 891 of file structure.h.
Referenced by GlobalSearch::OptBase::_finishHardnessCalculation(), and readStructureSettings().
setSkippedOptimization()
void GlobalSearch::Structure::setSkippedOptimization (bool b) inline
If the structure was created by primitive reduction, then it does not proceed through the optimizer. This bool indicates if it was created by primitive reduction.
See also
skippedOptimization()
Definition at line 1345 of file structure.h.
Referenced by readStructureSettings().
setStatus()
void GlobalSearch::Structure::setStatus (State status) inline
Parameters
status The current status of the Structure.
See also
getStatus
State
Definition at line 1256 of file structure.h.
Referenced by GlobalSearch::QueueManager::killStructure(), load(), readStructureSettings(), GlobalSearch::QueueManager::startJob(), Structure(), and GlobalSearch::QueueManager::updateStructureFeatureStatus().
setStrucFeatFailCt()
void GlobalSearch::Structure::setStrucFeatFailCt (int i) inline
Definition at line 176 of file structure.h.
setStrucFeatStatus()
void GlobalSearch::Structure::setStrucFeatStatus (FeatStatus v) inline
Definition at line 175 of file structure.h.
setStrucFeatValues()
void GlobalSearch::Structure::setStrucFeatValues (double v) inline
Definition at line 174 of file structure.h.
setStrucFeatValuesVec()
void GlobalSearch::Structure::setStrucFeatValuesVec (QList< double > v) inline
Definition at line 180 of file structure.h.
setStrucHistFeatFailCt()
void GlobalSearch::Structure::setStrucHistFeatFailCt (int v) inline
Definition at line 192 of file structure.h.
setStrucHistFeatStatus()
void GlobalSearch::Structure::setStrucHistFeatStatus (FeatStatus v) inline
Definition at line 191 of file structure.h.
setStrucHistFeatValues()
void GlobalSearch::Structure::setStrucHistFeatValues (QList< double > v) inline
Definition at line 190 of file structure.h.
setSupercellGenerationChecked()
void GlobalSearch::Structure::setSupercellGenerationChecked (bool b) inline
Structure tracks if it has been supercell-generation checked or not. Supercell generation checking involves checking to see if a supercell should be generated from this structure and placed into a higher FU gene pool.
See also
wasSupercellGenerationChecked()
Definition at line 1334 of file structure.h.
Referenced by readStructureSettings().
setSupercellString()
void GlobalSearch::Structure::setSupercellString (const QString & s) inline
Parameters
s A string naming the Structure that this Structure is a supercell of.
See also
getSupercellString
Definition at line 1306 of file structure.h.
setupConnections
void GlobalSearch::Structure::setupConnections () virtual slot
Connect slots/signals within the molecule. This must be called AFTER moving the Structure to it's final thread.
Definition at line 84 of file structure.cpp.
References structureChanged().
setVickersHardness()
void GlobalSearch::Structure::setVickersHardness (double d) inline
Set the Vickers hardness (usually calculated via aflow machine learning and the Chen model).
Parameters
d The Vickers hardness.
Definition at line 899 of file structure.h.
Referenced by GlobalSearch::OptBase::_finishHardnessCalculation(), and readStructureSettings().
shearModulus()
double GlobalSearch::Structure::shearModulus () const inline
Get the shear modulus as calculated by Aflow machine learning.
Returns
The shear modulus (or -1.0 if it hasn't been set).
Definition at line 869 of file structure.h.
Referenced by writeStructureSettings().
sizeOfHistory()
virtual unsigned int GlobalSearch::Structure::sizeOfHistory () inline virtual
Returns
Number of history entries available
Definition at line 1130 of file structure.h.
Referenced by deleteFromHistory(), and retrieveHistoryEntry().
skippedOptimization()
bool GlobalSearch::Structure::skippedOptimization () const inline
If the structure was created by primitive reduction, then it does not proceed through the optimizer. This bool indicates if it was created by primitive reduction.
See also
setSkippedOptimization()
Definition at line 750 of file structure.h.
Referenced by getResultsEntry(), GlobalSearch::OptBase::save(), and writeStructureSettings().
sortAndRankByEnthalpy()
void GlobalSearch::Structure::sortAndRankByEnthalpy (QList< Structure * > * structures) static
Sort and rank the listed structures by their enthalpies
Parameters
structures List of structures to sort and assign rank
See also
sortByEnthalpy
rankEnthalpies
setRank
getRank
Definition at line 1567 of file structure.cpp.
References sortByEnthalpy().
Referenced by GlobalSearch::OptBase::save().
sortByEnthalpy()
void GlobalSearch::Structure::sortByEnthalpy (QList< Structure * > * structures) static
Sort the listed structures by their enthalpies
Parameters
structures List of structures to sort
See also
rankEnthalpies
sortAndRankByEnthalpy
Definition at line 1463 of file structure.cpp.
References getEnthalpy(), and lock().
Referenced by sortAndRankByEnthalpy().
sortByVickersHardness()
void GlobalSearch::Structure::sortByVickersHardness (QList< Structure * > * structures) static
Sort the listed structures by their vickers hardnesses
Parameters
structures List of structures to sort
Definition at line 1492 of file structure.cpp.
References lock(), and vickersHardness().
startOptTimer()
void GlobalSearch::Structure::startOptTimer () inline
Record the current time as when the current optimization process started.
See also
setOptTimerStart
getOptTimerStart
setOptTimerEnd
getOptTimerEnd
stopOptTimer
getOptElapsed
Definition at line 1357 of file structure.h.
Referenced by GlobalSearch::LocalQueueInterface::startJob().
stopOptTimer()
void GlobalSearch::Structure::stopOptTimer () inline
Record the current time as when the current optimization process stopped.
See also
setOptTimerStart
getOptTimerStart
setOptTimerEnd
getOptTimerEnd
startOptTimer
getOptElapsed
Definition at line 1373 of file structure.h.
Referenced by GlobalSearch::QueueManager::killStructure(), GlobalSearch::LocalQueueInterface::stopJob(), and GlobalSearch::Optimizer::update().
structureChanged
void GlobalSearch::Structure::structureChanged () virtual slot
After calling setupConnections(), this will be called when the structure is update, atoms moved, added, etc...
Definition at line 676 of file structure.cpp.
Referenced by setupConnections().
updateAndAddFeaturesToHistory()
void GlobalSearch::Structure::updateAndAddFeaturesToHistory (Structure * s)
Add features info to history of the structure
Parameters
s Structure whose feature-related info is added to history
Definition at line 714 of file structure.cpp.
updateAndAddToHistory()
void GlobalSearch::Structure::updateAndAddToHistory (const QList< unsigned int > & atomicNums, const QList< Vector3 > & coords, const double energy = 0, const double enthalpy = 0, const Matrix3 & cell = Matrix3::Zero()) virtual
Update the coordinates, enthalpy and/or energy, and optionally unit cell of the structure, appending the data to the structure's history.
Parameters
atomicNums List of atomic numbers
coords List of cartesian coordinates
energy in eV
enthalpy in eV
cell Matrix of cell vectors (row vectors)
Definition at line 721 of file structure.cpp.
References clearPreoptBonding(), getPreoptBonding(), and reusePreoptBonding().
updateAndSkipHistory()
void GlobalSearch::Structure::updateAndSkipHistory (const QList< unsigned int > & atomicNums, const QList< Vector3 > & coords, const double energy = 0, const double enthalpy = 0, const Matrix3 & cell = Matrix3::Zero()) virtual
Update the coordinates, enthalpy and/or energy, and optionally unit cell of the structure, without adding the data to the structure's history.
Parameters
atomicNums List of atomic numbers
coords List of cartesian coordinates
energy in eV
enthalpy in eV
cell Matrix of cell vectors (row vectors)
Definition at line 681 of file structure.cpp.
vickersHardness()
double GlobalSearch::Structure::vickersHardness () const inline
Get the Vickers hardness as calculated with the Chen model involving the bulk and shear moduli from Aflow.
Returns
The Vickers hardness (or -1.0 if it hasn't been set).
Definition at line 877 of file structure.h.
Referenced by getResultsEntry(), sortByVickersHardness(), GlobalSearch::QueueManager::updateStructureFeatureStatus(), and writeStructureSettings().
wasPrimitiveChecked()
bool GlobalSearch::Structure::wasPrimitiveChecked () const inline
Structure tracks if it has been primitive-checked or not. Primitive checking involves running the primitive reduction function to see if a smaller FU primitive structure can be made.
See also
setPrimitiveChecked()
Definition at line 730 of file structure.h.
Referenced by writeStructureSettings().
wasSupercellGenerationChecked()
bool GlobalSearch::Structure::wasSupercellGenerationChecked () const inline
Structure tracks if it has been supercell-generation checked or not. Supercell generation checking involves checking to see if a supercell should be generated from this structure and placed into a higher FU gene pool.
See also
setSupercellGenerationChecked()
Definition at line 739 of file structure.h.
Referenced by writeStructureSettings().
writeCurrentStructureInfo
void GlobalSearch::Structure::writeCurrentStructureInfo (const QString & filename) protected slot
Write current data for a structure to a file. Data includes enthalpy, energy, cell vectors, and atom info
Parameters
filename Filename to write data to.
See also
writeStructureSettings
readStructureSettings
Definition at line 547 of file structure.cpp.
References getEnergy(), getEnthalpy(), and getPV().
Referenced by writeStructureSettings().
writeSettings
virtual void GlobalSearch::Structure::writeSettings (const QString & filename) inline virtual slot
Write supplementary data about this Structure to a file. All data that is not stored in the readable optimizer output file should be written here.
If reimplementing this in a derived class, call writeStructureSettings(filename) to write inherited data.
Parameters
filename Filename to write data to.
See also
writeStructureSettings
readSettings
Definition at line 1030 of file structure.h.
References writeStructureSettings().
Referenced by GlobalSearch::OptBase::save().
writeStructureSettings
void GlobalSearch::Structure::writeStructureSettings (const QString & filename) protected slot
Write data from the Structure class to a file.
Parameters
filename Filename to write data to.
See also
writeSettings
readSettings
Definition at line 196 of file structure.cpp.
References bulkModulus(), fileName(), getCurrentOptStep(), getFailCount(), getGeneration(), getIDNumber(), getIndex(), getJobID(), getOptTimerEnd(), getOptTimerStart(), getParents(), getRank(), getRempath(), getStatus(), getStrucFeatNumber(), hasParentStructure(), reusePreoptBonding(), shearModulus(), skippedOptimization(), vickersHardness(), wasPrimitiveChecked(), wasSupercellGenerationChecked(), and writeCurrentStructureInfo().
Referenced by writeSettings().
Member Data Documentation
m_hist_strucFeatFailCt
QList<int> GlobalSearch::Structure::m_hist_strucFeatFailCt protected
Definition at line 1463 of file structure.h.
m_hist_strucFeatStatus
QList<FeatStatus> GlobalSearch::Structure::m_hist_strucFeatStatus protected
Definition at line 1461 of file structure.h.
m_hist_strucFeatValues
QList<QList<double> > GlobalSearch::Structure::m_hist_strucFeatValues protected
Definition at line 1462 of file structure.h.
m_strucFeatFailCt
int GlobalSearch::Structure::m_strucFeatFailCt protected
Definition at line 1459 of file structure.h.
m_strucFeatStatus
std::atomic<FeatStatus> GlobalSearch::Structure::m_strucFeatStatus protected
Definition at line 1457 of file structure.h.
m_strucFeatValues
QList<double> GlobalSearch::Structure::m_strucFeatValues protected
Definition at line 1458 of file structure.h.
The documentation for this class was generated from the following files:
src/globalsearch/structure.h
src/globalsearch/structure.cpp