XtalOpt - API:GlobalSearch::ZMatrixFormat Class Reference
GlobalSearch::ZMatrixFormat Class Reference
Static Public Member Functions
static bool read (Structure *s, std::istream &in)
static bool write (const Structure &s, std::ostream &out)
static std::vector< ZMatrixEntry > generateZMatrixEntries (const Structure *s)
static bool writeSiestaZMatrix (Structure &s, std::ostream &out, bool fixR, bool fixA, bool fixT)
static void reorderAtomsToMatchZMatrix (Structure &s)
Detailed Description
Definition at line 65 of file zmatrixformat.h.
Member Function Documentation
generateZMatrixEntries()
std::vector< ZMatrixEntry > GlobalSearch::ZMatrixFormat::generateZMatrixEntries (const Structure * s) static
Chooses numberings for atoms to be part of the z-matrix, and sets rInd, angleInd, and dihedralInd for each entry. See the ZMatrixEntry struct definition above for more details about the return type. Carbons will preferentially be first, and hydrogens will preferentially be last. If the structure contains multiple molecules, the first atom of each molecule can be identified because it will have -1 for rInd, angleInd, and dihedralInd. Note: these indices are zero-based. If you write the output to a z-matrix file, you should add 1 to all (except ind) because the actual z-matrix format is 1-based.
Definition at line 683 of file zmatrixformat.cpp.
References GlobalSearch::Molecule::areBonded(), GlobalSearch::Molecule::atomicNumbers(), and GlobalSearch::Molecule::bondedAtoms().
Referenced by reorderAtomsToMatchZMatrix(), and writeSiestaZMatrix().
read()
bool GlobalSearch::ZMatrixFormat::read (Structure * s, std::istream & in) static
Definition at line 290 of file zmatrixformat.cpp.
reorderAtomsToMatchZMatrix()
void GlobalSearch::ZMatrixFormat::reorderAtomsToMatchZMatrix (Structure & s) static
Reorder the atoms so that they match the ordering for the z-matrix ordering.
Parameters
s The Structure whose atoms are to be reordered.
Definition at line 889 of file zmatrixformat.cpp.
References generateZMatrixEntries(), and GlobalSearch::Molecule::reorderAtoms().
write()
bool GlobalSearch::ZMatrixFormat::write (const Structure & s, std::ostream & out) static
Definition at line 615 of file zmatrixformat.cpp.
writeSiestaZMatrix()
bool GlobalSearch::ZMatrixFormat::writeSiestaZMatrix (Structure & s, std::ostream & out, bool fixR, bool fixA, bool fixT) static
Write a z-matrix using the specification in SIESTA (Spanish Initiative for Electronic Simulations with Thousands of Atoms) to out. One molecule block will be used for every set of bonded atoms. If Structure::reusePreoptBonding() is true, the atoms in s will be re-ordered according to the z-matrix ordering, and the pre-optimization bonding information will be stored.
A molecule wrap to the smallest bonds will always be performed on
Parameters
s.
s The structure for which to write the z-matrix.
out The output for the SIESTA z-matrix.
fixR Whether or not to fix all of the bond distances in the z-matrix
fixA Whether or not to fix all of the bond angles in the z-matrix
fixT Whether or not to fix all the torsions (dihedrals) in the z-matrix
Returns
True on success. False on failure.
An excerpt from the SIESTA manual with regard to the molecule z-matrix form:
@begin_excerpt
Nspecies i j k r a t ifr ifa ift Here the values Nspecies, i, j, k, ifr, ifa, and ift are integers and r, a, and t are double precision reals. For most atoms, Nspecies is the species number of the atom, r is distance to atom number i, a is the angle made by the present atom with atoms j and i, while t is the torsional angle made by the present atom with atoms k, j, and i. The values ifr, ifa and ift are integer flags that indicate whether r, a, and t, respectively, should be varied; 0 for fixed, 1 for varying. The first three atoms in a molecule are a special case. Because there are insufficient atoms defined to specify a distance/angle/torsion, the values are set differently. For atom 1, r, a, and t, are the Cartesian coordinates of the atom. For the second atom, r, a, and t are the coordinates in spherical form of the second atom relative to the first: first the radius, then the polar angle (angle between the z-axis and the displacement vector) and then the azimuthal angle (angle between the x-axis and the projection of the displacement vector on the x-y plane). Finally, for the third atom, the numbers take their normal form, but the torsional angle is defined relative to a notional atom 1 unit in the z-direction above the atom j.
@end_excerpt
An example: block Zmatrix
molecule 1 0 0 0 0.0 0.0 0.0 0 0 0 2 1 0 0 1.0 90.0 37.743919 1 0 0 2 1 2 0 1.0 1.0 90.0 1 1 0 endblock Zmatrix
Definition at line 474 of file zmatrixformat.cpp.
References GlobalSearch::Molecule::angle(), GlobalSearch::Molecule::atom(), GlobalSearch::Molecule::atomicNumber(), GlobalSearch::Molecule::dihedral(), GlobalSearch::Molecule::distance(), generateZMatrixEntries(), GlobalSearch::UnitCell::minimumImage(), GlobalSearch::Atom::pos(), GlobalSearch::Molecule::unitCell(), and GlobalSearch::Molecule::wrapMoleculesToSmallestBonds().
The documentation for this class was generated from the following files:
src/globalsearch/formats/zmatrixformat.h
src/globalsearch/formats/zmatrixformat.cpp