XtalOpt - API:GlobalSearch::CastepFormat Class Reference
GlobalSearch::CastepFormat Class Reference
Static Public Member Functions
static bool read (Structure *s, const QString &filename)
Detailed Description
Definition at line 30 of file castepformat.h.
Member Function Documentation
read()
bool GlobalSearch::CastepFormat::read (Structure * s, const QString & filename) static
The output we are looking for should look something like this:
BFGS: Final Configuration:
Unit Cell
Real Lattice(A) Reciprocal Lattice(1/A) 1.0352960 0.0311284 0.0112407 6.0183250 1.3284540 0.9861314 -0.4938210 2.2087554 0.0382761 -0.0859956 2.8236982 0.1008568 -0.5538192 -0.1445463 3.5746629 -0.0180041 -0.0344124 1.7535192
                 Lattice parameters(A)       Cell Angles
              a =    1.035825          alpha =   89.363425
              b =    2.263609          beta  =   98.243872
              c =    3.620197          gamma =  100.867480
          Current cell volume =    8.248807 A**3
                     -------------------------------
                               Cell Contents
                     -------------------------------
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      x  Element    Atom        Fractional coordinates of atoms  x
      x            Number           u          v          w      x
      x----------------------------------------------------------x
      x   H          1         -0.144690  -0.171910  -0.132545   x
      x   H          2          0.865522   0.331412   0.367463   x
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
BFGS: Final Enthalpy = -3.01566909E+001 eV
Definition at line 66 of file castepformat.cpp.
References GlobalSearch::UnitCell::toCartesian(), and GlobalSearch::Structure::updateAndAddToHistory().
Referenced by GlobalSearch::Formats::read().
The documentation for this class was generated from the following files:
src/globalsearch/formats/castepformat.h
src/globalsearch/formats/castepformat.cpp