XtalOpt - API:GlobalSearch::OBConvert Class Reference
GlobalSearch::OBConvert Class Reference
Static Public Member Functions
static bool convertFormat (const QString &inFormat, const QString &outFormat, const QByteArray &input, QByteArray &output, const QStringList &options=QStringList())
static bool executeOBabel (const QStringList &args, const QByteArray &input, QByteArray &output)
Detailed Description
Definition at line 30 of file obconvert.h.
Member Function Documentation
convertFormat()
bool GlobalSearch::OBConvert::convertFormat (const QString & inFormat, const QString & outFormat, const QByteArray & input, QByteArray & output, const QStringList & options = QStringList()) static
Convert a file from one format to another. Calls executeOBabel(). Read the description for executeOBabel() to see how the obabel executable is found and used.
Parameters
inFormat The input format.
outFormat The output format.
input The input to be sent to obabel through stdin.
output The stdout output that obabel returns.
options Any additional options you wish to pass to obabel.
Returns
Returns true if executeOBabel() ran successfully, and false if it did not.
Definition at line 26 of file obconvert.cpp.
References executeOBabel().
Referenced by GlobalSearch::GenerateXrd::generateXrdPattern().
executeOBabel()
bool GlobalSearch::OBConvert::executeOBabel (const QStringList & args, const QByteArray & input, QByteArray & output) static
Execute obabel and get output. Looks for obabel in three places:
The OBABEL_EXECUTABLE environment variable. If this is set, it will be used for the obabel executable.
The application directory path. If obabel is found in there, it will be used.
The application directory path + "/../bin/". If obabel is found there it will be used.
If obabel is not found in any of these places, an error will be printed and the function will return false.
Parameters
args The arguments to be used with the obabel executable.
input The input to be sent through stdin to obabel.
output The stdout output that obabel returns.
Returns
True if it ran without any errors. False if the executable wasn't found or obabel returned an error.
Definition at line 38 of file obconvert.cpp.
Referenced by convertFormat().
The documentation for this class was generated from the following files:
src/globalsearch/formats/obconvert.h
src/globalsearch/formats/obconvert.cpp