XtalOpt - API:GlobalSearch::GenerateXrd Class Reference
GlobalSearch::GenerateXrd Class Reference
Static Public Member Functions
static bool generateXrdPattern (const Structure &s, XrdData &results, double wavelength=1.5056, double peakwidth=0.52958, size_t numpoints=1000, double max2theta=162.0)
static bool executeGenXrdPattern (const QStringList &args, const QByteArray &input, QByteArray &output)
Detailed Description
Definition at line 33 of file generatexrd.h.
Member Function Documentation
executeGenXrdPattern()
bool GlobalSearch::GenerateXrd::executeGenXrdPattern (const QStringList & args, const QByteArray & input, QByteArray & output) static
This function executes the genXrdPattern executable with the given arguments and input, and it puts the output in output.
Parameters
args The list of arguments in addition to the executable.
input The stdin input for the program.
output The output from the program.
Returns
True if the program ran successfully. False if it failed.
Definition at line 33 of file generatexrd.cpp.
Referenced by generateXrdPattern().
generateXrdPattern()
bool GlobalSearch::GenerateXrd::generateXrdPattern (const Structure & s, XrdData & results, double wavelength = 1.5056, double peakwidth = 0.52958, size_t numpoints = 1000, double max2theta = 162.0) static
The primary function that is to be called in this class. This function takes a Structure object, converts it to a cif file, generates Xrd data from it, and stores it in results.
Parameters
s The Structure whose XRD is to be obtained.
results The resulting data (it is a vector of pairs of doubles). The first element in the pair is the 2theta value in degrees, and the second element in the pair is the intensity.
wavelength The wavelength of the x-ray in Angstroms.
peakwidth The broadening of the peak at the base (in degrees).
numpoints The number of 2theta points.
max2theta The max 2theta value in degrees.
Returns
True on success and false on failure.
Definition at line 103 of file generatexrd.cpp.
References GlobalSearch::OBConvert::convertFormat(), executeGenXrdPattern(), GlobalSearch::Structure::getGeneration(), and GlobalSearch::Structure::getIDNumber().
The documentation for this class was generated from the following files:
src/globalsearch/xrd/generatexrd.h
src/globalsearch/xrd/generatexrd.cpp