XtalOpt - API:GlobalSearch::AbstractTab Class Reference
GlobalSearch::AbstractTab Class Reference
The base class for UI tabs, preconfigured to work with dialogs derived from AbstractDialog.
#include <globalsearch/ui/abstracttab.h>
Public Slots
virtual void lockGUI ()
Signals
void moleculeChanged (GlobalSearch::Structure *)
void startingBackgroundProcessing ()
void finishedBackgroundProcessing ()
void initialized ()
Public Member Functions
AbstractTab (AbstractDialog *parent, OptBase *p)
virtual ~AbstractTab () override
QWidget * getTabWidget ()
virtual void readSettings (const QString &filename="")
virtual void writeSettings (const QString &filename="")
virtual void updateGUI ()
virtual void disconnectGUI ()
Protected Slots
virtual void initialize ()
void setBusyCursor ()
void clearBusyCursor ()
Protected Attributes
QWidget * m_tab_widget
The actual widget that will be made into a tab.
AbstractDialog * m_dialog
A pointer to the parent dialog.
OptBase * m_opt
A pointer to the associated OptBase class.
bool m_isInitialized
Set to true once initialized() completes.
std::atomic< bool > m_updateGuiInProgress {false}
Used to determine if a gui update is in progress.
Detailed Description
The base class for UI tabs, preconfigured to work with dialogs derived from AbstractDialog.
Author
David C. Lonie
Definition at line 35 of file abstracttab.h.
Constructor & Destructor Documentation
AbstractTab()
GlobalSearch::AbstractTab::AbstractTab (AbstractDialog * parent, OptBase * p) explicit
 Constructor
 Minimum constructor for derived tab:
DerivedTab::DerivedTab(AbstractDialog *parent,
                       OptBase *p) :
  AbstractTab(parent, p)
{
ui.setupUi(m_tab_widget);
initialize();
}
Definition at line 26 of file abstracttab.cpp.
References m_tab_widget.
~AbstractTab()
GlobalSearch::AbstractTab::~AbstractTab () override virtual
Destructor
Definition at line 59 of file abstracttab.cpp.
Member Function Documentation
clearBusyCursor
void GlobalSearch::AbstractTab::clearBusyCursor () protected slot
Resets the application's busy cursor. This should not be called directly, instead emit finishedBackgroundProcessing(), which is safe to use from a background thread.
See also
startingBackgroundProcessing()
finishedBackgroundProcessing()
Definition at line 71 of file abstracttab.cpp.
Referenced by initialize().
disconnectGUI()
virtual void GlobalSearch::AbstractTab::disconnectGUI () inline virtual
Used during benchmarking to disable any GUI update connections.
Definition at line 107 of file abstracttab.h.
Referenced by initialize().
finishedBackgroundProcessing
void GlobalSearch::AbstractTab::finishedBackgroundProcessing () signal
Emit this signal after user-requested processing has completed. This will reset the busy cursor in the application.
Referenced by initialize().
getTabWidget()
QWidget * GlobalSearch::AbstractTab::getTabWidget () inline
Returns
The widget for this tab.
Definition at line 65 of file abstracttab.h.
References m_tab_widget.
initialize
void GlobalSearch::AbstractTab::initialize () protected virtual slot
Create some default connections between the main dialog and this tab.
Definition at line 32 of file abstracttab.cpp.
References clearBusyCursor(), disconnectGUI(), finishedBackgroundProcessing(), initialized(), lockGUI(), m_dialog, m_isInitialized, moleculeChanged(), readSettings(), setBusyCursor(), startingBackgroundProcessing(), updateGUI(), and writeSettings().
Referenced by GlobalSearch::AbstractEditTab::initialize().
initialized
void GlobalSearch::AbstractTab::initialized () signal
Emitted when initialize completes
Referenced by initialize().
lockGUI
virtual void GlobalSearch::AbstractTab::lockGUI () inline virtual slot
Disable portions of the GUI that shouldn't be modified after the search has started.
Definition at line 72 of file abstracttab.h.
Referenced by initialize().
moleculeChanged
void GlobalSearch::AbstractTab::moleculeChanged (GlobalSearch::Structure *) signal
Emit to update the molecule displayed in the Avogadro GLWidget
Referenced by initialize().
readSettings()
virtual void GlobalSearch::AbstractTab::readSettings (const QString & filename = "") inline virtual
Load any parameters that this tab is responible for here.
Note
In most cases, this shouldn't be called directly, but rather call the same function in the parent dialog class.
Parameters
filename If specified, read from given file. Otherwise read from system config file.
Definition at line 81 of file abstracttab.h.
Referenced by initialize(), and GlobalSearch::AbstractEditTab::loadScheme().
setBusyCursor
void GlobalSearch::AbstractTab::setBusyCursor () protected slot
Sets the application's busy cursor. This should not be called directly, instead emit startingBackgroundProcessing(), which is safe to use from a background thread.
See also
startingBackgroundProcessing()
finishedBackgroundProcessing()
Definition at line 63 of file abstracttab.cpp.
Referenced by initialize().
startingBackgroundProcessing
void GlobalSearch::AbstractTab::startingBackgroundProcessing () signal
Emit this signal before beginning user-requested processing. This will set the busy cursor in the application.
Referenced by initialize().
updateGUI()
virtual void GlobalSearch::AbstractTab::updateGUI () inline virtual
Set any GUI elements from information in internal data structures.
Definition at line 102 of file abstracttab.h.
Referenced by initialize().
writeSettings()
virtual void GlobalSearch::AbstractTab::writeSettings (const QString & filename = "") inline virtual
Save any parameters that this tab is responible for here.
Note
In most cases, this shouldn't be called directly, but rather call the same function in the parent dialog class.
Parameters
filename If specified, write to given file. Otherwise write to system config file.
Definition at line 93 of file abstracttab.h.
Referenced by initialize(), and GlobalSearch::AbstractEditTab::saveScheme().
Member Data Documentation
m_dialog
AbstractDialog* GlobalSearch::AbstractTab::m_dialog protected
A pointer to the parent dialog.
Definition at line 164 of file abstracttab.h.
Referenced by initialize(), GlobalSearch::AbstractEditTab::initialize(), and GlobalSearch::AbstractEditTab::showHelp().
m_isInitialized
bool GlobalSearch::AbstractTab::m_isInitialized protected
Set to true once initialized() completes.
Definition at line 170 of file abstracttab.h.
Referenced by GlobalSearch::AbstractEditTab::getTemplateNames(), initialize(), GlobalSearch::AbstractEditTab::populateOptStepList(), GlobalSearch::AbstractEditTab::populateTemplates(), GlobalSearch::AbstractEditTab::updateEditWidget(), GlobalSearch::AbstractEditTab::updateGUIOptimizer(), and GlobalSearch::AbstractEditTab::updateGUIQueueInterface().
m_opt
OptBase* GlobalSearch::AbstractTab::m_opt protected
A pointer to the associated OptBase class.
Definition at line 167 of file abstracttab.h.
Referenced by GlobalSearch::AbstractEditTab::appendOptStep(), GlobalSearch::AbstractEditTab::getCurrentOptimizer(), GlobalSearch::AbstractEditTab::getCurrentQueueInterface(), GlobalSearch::AbstractEditTab::initialize(), GlobalSearch::AbstractEditTab::loadScheme(), GlobalSearch::AbstractEditTab::populateOptStepList(), GlobalSearch::AbstractEditTab::removeCurrentOptStep(), GlobalSearch::AbstractEditTab::saveCurrentTemplate(), GlobalSearch::AbstractEditTab::saveScheme(), GlobalSearch::AbstractEditTab::showHelp(), GlobalSearch::AbstractEditTab::updateEditWidget(), GlobalSearch::AbstractEditTab::updateGUI(), GlobalSearch::AbstractEditTab::updateOptimizer(), GlobalSearch::AbstractEditTab::updateQueueInterface(), and GlobalSearch::AbstractEditTab::updateUserValues().
m_tab_widget
QWidget* GlobalSearch::AbstractTab::m_tab_widget protected
The actual widget that will be made into a tab.
Definition at line 161 of file abstracttab.h.
Referenced by AbstractTab(), GlobalSearch::DefaultEditTab::DefaultEditTab(), and getTabWidget().
m_updateGuiInProgress
std::atomic<bool> GlobalSearch::AbstractTab::m_updateGuiInProgress {false} protected
Used to determine if a gui update is in progress.
Definition at line 173 of file abstracttab.h.
The documentation for this class was generated from the following files:
src/globalsearch/ui/abstracttab.h
src/globalsearch/ui/abstracttab.cpp