XtalOpt - API:GlobalSearch::Molecule Class Reference
GlobalSearch::Molecule Class Reference
A basic molecule class. Contains a vector of atoms and a unit cell.
#include <molecule.h>
Public Member Functions
Molecule (const std::vector< Atom > &atoms=std::vector< Atom >(), const UnitCell &uc=UnitCell())
Molecule (const Molecule &other)=default
Molecule (Molecule &&other)=default
Molecule & operator= (const Molecule &other)=default
Molecule & operator= (Molecule &&other)=default
Atom & addAtom (unsigned short atomicNum=0, const Vector3 &pos=Vector3(0.0, 0.0, 0.0))
Atom & addAtom (const Atom &atom)
void addMolecule (const Molecule &mol)
std::vector< Molecule > getIndividualMolecules () const
void setAtoms (const std::vector< Atom > &atoms)
bool removeAtom (size_t ind)
bool removeAtom (const Atom &atom)
void clearAtoms ()
Atom & atom (size_t ind)
const Atom & atom (size_t ind) const
std::vector< Atom > & atoms ()
const std::vector< Atom > & atoms () const
long long atomIndex (const Atom &atom) const
size_t numAtoms () const
std::vector< unsigned short > atomicNumbers () const
unsigned short atomicNumber (size_t ind) const
void swapAtoms (size_t ind1, size_t ind2)
void sortAtoms (std::vector< size_t > sortOrder)
void reorderAtoms (const std::vector< size_t > &newOrder)
double distance (const Vector3 &A, const Vector3 &B) const
double distance (size_t atomInd1, size_t atomInd2) const
double angle (size_t atomInd1, size_t atomInd2, size_t atomInd3) const
double dihedral (size_t atomInd1, size_t atomInd2, size_t atomInd3, size_t atomInd4) const
bool hasBonds () const
size_t numBonds () const
void addBond (size_t ind1, size_t ind2, unsigned short bondOrder=1)
void removeBond (size_t bondInd)
void removeBondBetweenAtoms (size_t ind1, size_t ind2)
void removeBondsFromAtom (size_t ind)
std::vector< Bond > & bonds ()
const std::vector< Bond > & bonds () const
Bond & bond (size_t bondInd)
const Bond & bond (size_t bondInd) const
long long bondBetweenAtoms (size_t atomInd1, size_t atomInd2) const
bool isBonded (size_t ind) const
bool areBonded (size_t ind1, size_t ind2) const
std::vector< size_t > bonds (size_t ind) const
std::vector< size_t > bondedAtoms (size_t ind) const
void wrapMoleculesToSmallestBonds ()
void clearBonds ()
bool hasUnitCell () const
void setUnitCell (const UnitCell &uc)
UnitCell & unitCell ()
const UnitCell & unitCell () const
void clear ()
Static Public Member Functions
static double angle (const Vector3 &A, const Vector3 &B, const Vector3 &C)
static double dihedral (const Vector3 &A, const Vector3 &B, const Vector3 &C, const Vector3 &D)
Detailed Description
A basic molecule class. Contains a vector of atoms and a unit cell.
Definition at line 33 of file molecule.h.
Constructor & Destructor Documentation
Molecule()
GlobalSearch::Molecule::Molecule (const std::vector< Atom > & atoms = std::vector<Atom>(), const UnitCell & uc = UnitCell()) inline explicit
Molecule constructor. Default set of atoms is empty. Default unit cell is invalid (everything is zero). An invalid unit cell implies that the molecule does not have a unit cell.
Parameters
atoms A vector of atoms that the molecule will have. Default is an empty vector.
uc The unit cell that the molecule will have. Default is an invalid unit cell (all zeros for cell parameters).
Definition at line 509 of file molecule.h.
Member Function Documentation
addAtom() [1/2]
Atom & GlobalSearch::Molecule::addAtom (const Atom & atom) inline
This function overloads addAtom. This adds a copy of the Atom object passed to it.
Parameters
atom A copy of the Atom object to be added.
Returns
A reference to the atom just created.
Definition at line 520 of file molecule.h.
References atom().
addAtom() [2/2]
Atom & GlobalSearch::Molecule::addAtom (unsigned short atomicNum = 0, const Vector3 & pos = Vector3(0.0, 0.0, 0.0)) inline
Add an atom. A reference to the newly added atom is returned and may be edited. The atomic number has a default value of 0, and the position has a default value of (0,0,0).
Parameters
atomicNum The atomic number of the atom. Default value is 0.
pos The 3-dimensional Cartesian coordinates of the atom in Angstroms. The default is (0,0,0).
Returns
A reference to the atom just created.
Definition at line 514 of file molecule.h.
Referenced by GlobalSearch::Structure::addAtomRandomly(), addMolecule(), getIndividualMolecules(), GlobalSearch::Structure::readCurrentStructureInfo(), and GlobalSearch::Structure::updateAndAddToHistory().
addBond()
void GlobalSearch::Molecule::addBond (size_t ind1, size_t ind2, unsigned short bondOrder = 1) inline
Create a bond using the atom indices. Does nothing if the index is out of range. There is a default bond order of 1.
Parameters
ind1 The index of the first atom in the bond.
ind2 The index of the second atom in the bond.
bondOrder The bond order of the bond.
Definition at line 611 of file molecule.h.
References areBonded().
Referenced by addMolecule(), getIndividualMolecules(), and GlobalSearch::Structure::perceiveBonds().
addMolecule()
void GlobalSearch::Molecule::addMolecule (const Molecule & mol)
Add another molecule to this molecule. All atoms will be added, and bonds of the newly added atoms will be preserved.
Parameters
mol The molecule to be added.
Definition at line 22 of file molecule.cpp.
References addAtom(), addBond(), atom(), atoms(), bond(), GlobalSearch::Bond::bondOrder(), bonds(), GlobalSearch::Bond::first(), numAtoms(), and GlobalSearch::Bond::second().
angle() [1/2]
double GlobalSearch::Molecule::angle (const Vector3 & A, const Vector3 & B, const Vector3 & C) static
Get the angle (in degrees) between three points (where the second point is the vertex).
Parameters
A The first point.
B The second point (the vertex of the angle).
C The third point.
Returns
The angle in degrees.
Definition at line 280 of file molecule.cpp.
Referenced by angle(), and GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
angle() [2/2]
double GlobalSearch::Molecule::angle (size_t atomInd1, size_t atomInd2, size_t atomInd3) const inline
Get the angle (in degrees) between three atoms (where the second atom is the vertex).
Parameters
atomInd1 The first atom index.
atomInd2 The second atom index (the vertex of the angle).
atomInd3 The third atom index.
Returns
The angle in degrees.
Definition at line 590 of file molecule.h.
References angle().
areBonded()
bool GlobalSearch::Molecule::areBonded (size_t ind1, size_t ind2) const
Are these two atoms bonded together?
Parameters
ind1 The index of the first atom.
ind2 The index of the second atom.
Returns
True if the atoms are bonded together. False otherwise.
Definition at line 201 of file molecule.cpp.
References bond(), GlobalSearch::Bond::first(), and GlobalSearch::Bond::second().
Referenced by addBond(), bondedAtoms(), GlobalSearch::ZMatrixFormat::generateZMatrixEntries(), getIndividualMolecules(), and wrapMoleculesToSmallestBonds().
atom() [1/2]
Atom & GlobalSearch::Molecule::atom (size_t ind) inline
Returns the atom at index ind. An assertion makes sure that ind is not beyond the bounds of the atom vector.
Parameters
ind The index of the atom to be returned.
Returns
A reference to the atom that is returned.
Definition at line 532 of file molecule.h.
Referenced by addAtom(), GlobalSearch::Structure::addAtomRandomly(), addMolecule(), atomIndex(), GlobalSearch::Structure::generateIADHistogram(), GlobalSearch::Structure::generateIADHistogram(), GlobalSearch::Structure::getNearestNeighborDistance(), GlobalSearch::Structure::getNeighbors(), removeAtom(), GlobalSearch::Structure::updateAndSkipHistory(), wrapMoleculesToSmallestBonds(), GlobalSearch::Structure::writeCurrentStructureInfo(), and GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
atom() [2/2]
const Atom & GlobalSearch::Molecule::atom (size_t ind) const inline
Returns a const reference to the atom at index ind. An assertion makes sure that ind is not beyond the bounds of the atom vector.
Parameters
ind The index of the atom to be returned.
Returns
A const reference to the atom that is returned.
Definition at line 538 of file molecule.h.
atomicNumber()
unsigned short GlobalSearch::Molecule::atomicNumber (size_t ind) const inline
Returns the atomic number of the atom at index ind. An assertion assures us that ind will not be beyond the bounds of the vector.
Parameters
ind The index of the atom whose atomic number we are obtaining.
Returns
The atomic number of the atom at index .
Definition at line 561 of file molecule.h.
Referenced by GlobalSearch::Structure::addAtomRandomly(), GlobalSearch::Structure::perceiveBonds(), GlobalSearch::Structure::writeCurrentStructureInfo(), and GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
atomicNumbers()
std::vector< unsigned short > GlobalSearch::Molecule::atomicNumbers () const inline
Returns a vector of atomic numbers of the molecule.
Returns
The vector of atomic numbers of the molecule.
Definition at line 553 of file molecule.h.
Referenced by GlobalSearch::ZMatrixFormat::generateZMatrixEntries().
atomIndex()
long long GlobalSearch::Molecule::atomIndex (const Atom & atom) const inline
Returns the index of the atom atom. Returns -1 if it was not found.
Parameters
atom The atom to find the index of.
Returns
The index of the atom. Returns -1 if it was not found.
Definition at line 544 of file molecule.h.
References atom().
Referenced by removeAtom().
atoms() [1/2]
std::vector< Atom > & GlobalSearch::Molecule::atoms () inline
Returns a reference to the atoms vector.
Returns
A reference to the vector of atoms.
Definition at line 168 of file molecule.h.
Referenced by addMolecule(), GlobalSearch::Structure::generateIADHistogram(), GlobalSearch::Structure::getAtomCoordsFrac(), getIndividualMolecules(), GlobalSearch::Structure::getNearestNeighborDistance(), GlobalSearch::Structure::getNearestNeighborDistances(), GlobalSearch::Structure::getNeighbors(), GlobalSearch::Structure::getNumberOfAtomsAlpha(), GlobalSearch::Structure::getShortestInteratomicDistance(), GlobalSearch::Structure::getSymbols(), GlobalSearch::OptBase::interpretKeyword_base(), GlobalSearch::Structure::perceiveBonds(), setAtoms(), and GlobalSearch::Structure::updateAndSkipHistory().
atoms() [2/2]
const std::vector< Atom > & GlobalSearch::Molecule::atoms () const inline
Returns a const reference to the atoms vector.
Returns
A const reference to the vector of atoms.
Definition at line 175 of file molecule.h.
bond() [1/2]
Bond & GlobalSearch::Molecule::bond (size_t bondInd) inline
Get the Bond at index bondInd.
Parameters
bondInd The index for which to get the bond.
Returns
A reference to the Bond object.
Definition at line 627 of file molecule.h.
Referenced by addMolecule(), areBonded(), isBonded(), removeAtom(), and swapAtoms().
bond() [2/2]
const Bond & GlobalSearch::Molecule::bond (size_t bondInd) const inline
Get the Bond at index bondInd. No edits are allowed here.
Parameters
bondInd The index for which to get the bond.
Returns
A const reference to the Bond object.
Definition at line 633 of file molecule.h.
bondBetweenAtoms()
long long GlobalSearch::Molecule::bondBetweenAtoms (size_t atomInd1, size_t atomInd2) const
If the two atoms are bonded together, return the index of the bond that is between them. If they are not bonded together, return -1.
Parameters
atomInd1 The first atom index of the two atoms bonded together.
atomInd2 The second atom index of the two atoms bonded together.
Returns
The index of the bond between the atoms or -1 if no bond exists.
Definition at line 178 of file molecule.cpp.
Referenced by getIndividualMolecules().
bondedAtoms()
std::vector< size_t > GlobalSearch::Molecule::bondedAtoms (size_t ind) const
Get the indices of the atoms that are bonded to the atom at index index.
Parameters
ind The index of the atom for which to get other bonded atoms.
Returns
The indices of the atoms bonded to the atom.
Definition at line 225 of file molecule.cpp.
References areBonded().
Referenced by GlobalSearch::ZMatrixFormat::generateZMatrixEntries().
bonds() [1/3]
std::vector< Bond > & GlobalSearch::Molecule::bonds () inline
Get the vector of bonds.
Returns
The vector of bonds.
Definition at line 369 of file molecule.h.
Referenced by addMolecule(), getIndividualMolecules(), and GlobalSearch::Structure::updateAndAddToHistory().
bonds() [2/3]
const std::vector< Bond > & GlobalSearch::Molecule::bonds () const inline
Get the vector of bonds. Const version.
Returns
The vector of bonds.
Definition at line 376 of file molecule.h.
bonds() [3/3]
std::vector< size_t > GlobalSearch::Molecule::bonds (size_t ind) const
Get the indices of the bonds connected to atom ind.
Parameters
ind The index of the atom for which to get bonds.
Returns
The indices of the bonds on the atom.
Definition at line 214 of file molecule.cpp.
clear()
void GlobalSearch::Molecule::clear () inline
Clear the bonds and atoms, and zero the unit cell.
Definition at line 488 of file molecule.h.
References GlobalSearch::UnitCell::clear().
clearAtoms()
void GlobalSearch::Molecule::clearAtoms () inline
Definition at line 137 of file molecule.h.
clearBonds()
void GlobalSearch::Molecule::clearBonds () inline
Remove all bonds.
Definition at line 454 of file molecule.h.
Referenced by GlobalSearch::Structure::perceiveBonds().
dihedral() [1/2]
double GlobalSearch::Molecule::dihedral (const Vector3 & A, const Vector3 & B, const Vector3 & C, const Vector3 & D) static
Get the dihedral angle (in degrees) created by four points where the first three points form a plane and the last three points form a plane.
Parameters
A The first point.
B The second point.
C The third point.
D The fourth point.
Returns
The dihedral angle in degrees.
Definition at line 288 of file molecule.cpp.
Referenced by dihedral(), and GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
dihedral() [2/2]
double GlobalSearch::Molecule::dihedral (size_t atomInd1, size_t atomInd2, size_t atomInd3, size_t atomInd4) const inline
Get the dihedral angle (in degrees) created by four atoms where the first three atoms form a plane and the last three atoms form a plane.
Parameters
atom1 The first atom index.
atom2 The second atom index.
atom3 The third atom index.
atom4 The fourth atom index.
Returns
The dihedral angle (in degrees).
Definition at line 600 of file molecule.h.
References dihedral().
distance() [1/2]
double GlobalSearch::Molecule::distance (const Vector3 & A, const Vector3 & B) const inline
Get the cartesian distance between two points. If we have a valid unit cell, we will take into account neighboring images. Otherwise, we will just perform a regular distance calculation.
Parameters
A The first point.
B The second point.
Returns
The distance.
Definition at line 576 of file molecule.h.
References GlobalSearch::UnitCell::distance(), and hasUnitCell().
Referenced by distance(), GlobalSearch::Structure::generateIADHistogram(), GlobalSearch::Structure::getNearestNeighborDistance(), GlobalSearch::Structure::getShortestInteratomicDistance(), GlobalSearch::Structure::perceiveBonds(), and GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
distance() [2/2]
double GlobalSearch::Molecule::distance (size_t atomInd1, size_t atomInd2) const inline
Get the cartesian distance between two atoms. If we have a valid unit cell, we will take into account neighboring atom images. Otherwise, we will just perform a regular distance calculation.
Parameters
atomInd1 The first atom index.
atomInd2 The second atom index.
Returns
The distance.
Definition at line 583 of file molecule.h.
References distance().
getIndividualMolecules()
std::vector< Molecule > GlobalSearch::Molecule::getIndividualMolecules () const
A Molecule class can contain multiple "molecules." This function is designed to separate these molecules by creating separate Molecules for every group of bonded atoms and returning them in a vector. The individual Molecules will all have the same unit cell as the parent Molecule.
Returns
The vector of indvidual molecules (groups of atoms bonded together).
Definition at line 35 of file molecule.cpp.
References addAtom(), addBond(), areBonded(), atoms(), bondBetweenAtoms(), bonds(), numAtoms(), setUnitCell(), and unitCell().
hasBonds()
bool GlobalSearch::Molecule::hasBonds () const inline
Does this molecule contain bonds? Returns true if !m_bonds.empty().
Returns
Whether or not the molecule contains bonds.
Definition at line 322 of file molecule.h.
Referenced by wrapMoleculesToSmallestBonds().
hasUnitCell()
bool GlobalSearch::Molecule::hasUnitCell () const inline
Do we have a unit cell? Returns true if the unit cell is valid. Returns false otherwise.
Returns
True if the unit cell is valid and false otherwise.
Definition at line 462 of file molecule.h.
References GlobalSearch::UnitCell::isValid().
Referenced by distance(), wrapMoleculesToSmallestBonds(), and GlobalSearch::Structure::writeCurrentStructureInfo().
isBonded()
bool GlobalSearch::Molecule::isBonded (size_t ind) const
Is the atom at index ind bonded?
Returns
True if it has at least one bond. False otherwise.
Definition at line 191 of file molecule.cpp.
References bond(), GlobalSearch::Bond::first(), and GlobalSearch::Bond::second().
numAtoms()
size_t GlobalSearch::Molecule::numAtoms () const inline
Returns the number of atoms in the molecule.
Returns
The number of atoms in the molecule.
Definition at line 191 of file molecule.h.
Referenced by GlobalSearch::Structure::addAtomRandomly(), addMolecule(), getIndividualMolecules(), GlobalSearch::OptBase::interpretKeyword_base(), GlobalSearch::Structure::rankByEnthalpy(), GlobalSearch::Structure::sortByEnthalpy(), GlobalSearch::Structure::updateAndSkipHistory(), wrapMoleculesToSmallestBonds(), and GlobalSearch::Structure::writeCurrentStructureInfo().
numBonds()
size_t GlobalSearch::Molecule::numBonds () const inline
How many bonds do we have?
Returns
The number of bonds in the molecule.
Definition at line 329 of file molecule.h.
removeAtom() [1/2]
bool GlobalSearch::Molecule::removeAtom (const Atom & atom)
Finds the atom equivalent to atom using operator==() and then removes that atom. Returns true if the atom was found and removed. Returns false if it was not.
Parameters
atom The atom to be removed.
Returns
True on success. False if the atom was not found.
Definition at line 114 of file molecule.cpp.
References atom(), atomIndex(), and removeAtom().
removeAtom() [2/2]
bool GlobalSearch::Molecule::removeAtom (size_t ind)
Remove the atom with index "ind". Returns true on success. Returns false if the index is out of range.
Parameters
ind The index of the atom to be removed.
Returns
True on success. False if ind is out of range.
Definition at line 99 of file molecule.cpp.
References GlobalSearch::Bond::atomIndexRemoved(), bond(), and removeBondsFromAtom().
Referenced by removeAtom().
removeBond()
void GlobalSearch::Molecule::removeBond (size_t bondInd) inline
Remove the bond at index bondInd. Does nothing if out of range.
Parameters
bondInd The index of the bond to be removed.
Definition at line 621 of file molecule.h.
Referenced by removeBondBetweenAtoms(), and removeBondsFromAtom().
removeBondBetweenAtoms()
void GlobalSearch::Molecule::removeBondBetweenAtoms (size_t ind1, size_t ind2)
Remove the bond between the two atoms. Does nothing if the atoms are not bonded or are not in the molecule.
Parameters
ind1 The index of the first atom in the bond.
ind2 The index of the second atom in the bond.
Definition at line 154 of file molecule.cpp.
References removeBond().
removeBondsFromAtom()
void GlobalSearch::Molecule::removeBondsFromAtom (size_t ind)
Remove all bonds connected to the atom
Parameters
ind.
ind The index of the atom for which to remove bonds.
Definition at line 167 of file molecule.cpp.
References removeBond().
Referenced by removeAtom().
reorderAtoms()
void GlobalSearch::Molecule::reorderAtoms (const std::vector< size_t > & newOrder)
Change the ordering of the atoms. The input, newOrder, should have a size equal to the number of atoms, and every number from 0 to numAtoms() - 1 should be in the vector. This function will automatically adjust the bonds as well so that the atoms remain bonded correctly.
Parameters
newOrder The new order for the atoms.
Definition at line 144 of file molecule.cpp.
References sortAtoms().
Referenced by GlobalSearch::ZMatrixFormat::reorderAtomsToMatchZMatrix().
setAtoms()
void GlobalSearch::Molecule::setAtoms (const std::vector< Atom > & atoms) inline
Set the atoms in the molecule. Any bonds will be cleared.
Parameters
atoms The atoms to be set in the molecule.
Definition at line 526 of file molecule.h.
References atoms().
setUnitCell()
void GlobalSearch::Molecule::setUnitCell (const UnitCell & uc) inline
Set the unit cell of the molecule.
Parameters
uc The new unit cell of the molecule.
Definition at line 469 of file molecule.h.
Referenced by getIndividualMolecules().
sortAtoms()
void GlobalSearch::Molecule::sortAtoms (std::vector< size_t > sortOrder)
Sort the atoms. The input, sortOrder, should have a size equal to the number of atoms, and every number from 0 to numAtoms() - 1 should be in the vector. This function will automatically adjust the bonds as well so that the atoms remain bonded correctly.
Parameters
sortOrder The sort order for the atoms.
Definition at line 125 of file molecule.cpp.
References swapAtoms().
Referenced by reorderAtoms().
swapAtoms()
void GlobalSearch::Molecule::swapAtoms (size_t ind1, size_t ind2) inline
Swap the indices of two atoms. This will also ensure that the atom indices in the bonds are properly changed.
Parameters
ind1 The index of the first atom to be swapped.
ind2 The index of the second atom to be swapped.
Definition at line 567 of file molecule.h.
References bond(), and GlobalSearch::Bond::swapIndices().
Referenced by sortAtoms().
unitCell() [1/2]
UnitCell & GlobalSearch::Molecule::unitCell () inline
Get a reference to the unit cell of the molcule.
Returns
The unit cell of the molecule.
Definition at line 476 of file molecule.h.
Referenced by GlobalSearch::Structure::addAtomRandomly(), GlobalSearch::Structure::getAtomCoordsFrac(), getIndividualMolecules(), GlobalSearch::PwscfFormat::read(), GlobalSearch::Structure::readCurrentStructureInfo(), GlobalSearch::Structure::updateAndAddToHistory(), GlobalSearch::Structure::updateAndSkipHistory(), wrapMoleculesToSmallestBonds(), GlobalSearch::Structure::writeCurrentStructureInfo(), and GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
unitCell() [2/2]
const UnitCell & GlobalSearch::Molecule::unitCell () const inline
Get a const reference to the unit cell of the molcule.
Returns
The unit cell of the molecule.
Definition at line 483 of file molecule.h.
wrapMoleculesToSmallestBonds()
void GlobalSearch::Molecule::wrapMoleculesToSmallestBonds ()
Wrap the atoms in an attempt to make all the bonds between atoms as short as possible in a unit cell. This will usually result in some atoms being located outside the unit cell, but it is very helpful for visualization.
Definition at line 238 of file molecule.cpp.
References areBonded(), atom(), hasBonds(), hasUnitCell(), numAtoms(), GlobalSearch::Atom::pos(), GlobalSearch::Atom::setPos(), and unitCell().
Referenced by GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
The documentation for this class was generated from the following files:
src/globalsearch/structures/molecule.h
src/globalsearch/structures/molecule.cpp