XtalOpt - API:GlobalSearch::UnitCell Class Reference
GlobalSearch::UnitCell Class Reference
A basic unit cell class. Contains a 3x3 matrix.
#include <unitcell.h>
Public Member Functions
UnitCell (const Matrix3 &m=Matrix3())
UnitCell (double a, double b, double c, double alpha, double beta, double gamma)
UnitCell (const UnitCell &other)=default
UnitCell (UnitCell &&other) noexcept
UnitCell & operator= (const UnitCell &other)=default
UnitCell & operator= (UnitCell &&other) noexcept
bool isValid () const
void setCellParameters (double a, double b, double c, double alpha, double beta, double gamma)
void setCellMatrix (const Matrix3 &mat)
Matrix3 cellMatrix () const
Matrix3 cellMatrixColForm () const
void setAVector (const Vector3 &v)
void setBVector (const Vector3 &v)
void setCVector (const Vector3 &v)
void setCellVectors (const Vector3 &a, const Vector3 &b, const Vector3 &c)
Vector3 aVector () const
Vector3 bVector () const
Vector3 cVector () const
double a () const
double b () const
double c () const
double alpha () const
double beta () const
double gamma () const
double volume () const
Vector3 toCartesian (const Vector3 &frac) const
Vector3 toFractional (const Vector3 &cart) const
Vector3 wrapCartesian (const Vector3 &cart) const
Vector3 wrapFractional (const Vector3 &frac) const
Vector3 minimumImage (const Vector3 &cart) const
double distance (const Vector3 &v1, const Vector3 &v2) const
void clear ()
Static Public Member Functions
static Vector3 minimumImageFractional (const Vector3 &frac)
Detailed Description
A basic unit cell class. Contains a 3x3 matrix.
Definition at line 33 of file unitcell.h.
Constructor & Destructor Documentation
UnitCell() [1/3]
GlobalSearch::UnitCell::UnitCell (const Matrix3 & m = Matrix3()) inline
Constructor. The default matrix is the zero matrix.
Parameters
m The matrix with which the cell matrix will be set. The default cell matrix is the zero matrix.
Definition at line 292 of file unitcell.h.
UnitCell() [2/3]
GlobalSearch::UnitCell::UnitCell (double a, double b, double c, double alpha, double beta, double gamma) inline
Constructor. This uses cell parameters to create the cell matrix. The A vector will lie along the x-axis. The B vector will lie in the positive y region of the x-y plane. The C vector will then be constrained.
Parameters
a The length (Angstroms) of vector A.
b The length (Angstroms) of vector B.
c The length (Angstroms) of vector C.
alpha The angle (degrees) between vectors B and C.
beta The angle (degrees) between vectors A and C.
gamma The angle (degrees) between vectors A and B.
Definition at line 296 of file unitcell.h.
References setCellParameters().
UnitCell() [3/3]
GlobalSearch::UnitCell::UnitCell (UnitCell && other) inline noexcept
Move constructor. Unfortunately, we must define it ourselves for it to be noexcept because Eigen::Matrix does not have a noexcept move constructor.
Definition at line 303 of file unitcell.h.
Member Function Documentation
a()
double GlobalSearch::UnitCell::a () const inline
Definition at line 168 of file unitcell.h.
alpha()
double GlobalSearch::UnitCell::alpha () const inline
Definition at line 177 of file unitcell.h.
aVector()
Vector3 GlobalSearch::UnitCell::aVector () const inline
Definition at line 159 of file unitcell.h.
b()
double GlobalSearch::UnitCell::b () const inline
Definition at line 171 of file unitcell.h.
beta()
double GlobalSearch::UnitCell::beta () const inline
Definition at line 180 of file unitcell.h.
bVector()
Vector3 GlobalSearch::UnitCell::bVector () const inline
Definition at line 162 of file unitcell.h.
c()
double GlobalSearch::UnitCell::c () const inline
Definition at line 174 of file unitcell.h.
cellMatrix()
Matrix3 GlobalSearch::UnitCell::cellMatrix () const inline
Get the cell matrix as row vectors.
Returns
The 3x3 cell matrix in row vector form.
Definition at line 119 of file unitcell.h.
Referenced by GlobalSearch::PwscfFormat::read(), and GlobalSearch::Structure::writeCurrentStructureInfo().
cellMatrixColForm()
Matrix3 GlobalSearch::UnitCell::cellMatrixColForm () const inline
Get the cell matrix as column vectors.
Returns
The 3x3 cell matrix in column vector form.
Definition at line 126 of file unitcell.h.
clear()
void GlobalSearch::UnitCell::clear () inline
Zeroes the unit cell.
Definition at line 258 of file unitcell.h.
Referenced by GlobalSearch::Molecule::clear().
cVector()
Vector3 GlobalSearch::UnitCell::cVector () const inline
Definition at line 165 of file unitcell.h.
distance()
double GlobalSearch::UnitCell::distance (const Vector3 & v1, const Vector3 & v2) const inline
Find the shortest distance between vectors v1 and v2.
Parameters
v1 The first vector.
v2 The second vector.
Returns
The shortest distance between the two vectors.
Definition at line 349 of file unitcell.h.
References minimumImage().
Referenced by GlobalSearch::Molecule::distance().
gamma()
double GlobalSearch::UnitCell::gamma () const inline
Definition at line 183 of file unitcell.h.
isValid()
bool GlobalSearch::UnitCell::isValid () const inline
Checks whether the cell is valid or not. If the volume is zero, the cell is considered invalid. Otherwise, it is considered valid.
Returns
True if the cell is valid. False if it is not.
Definition at line 89 of file unitcell.h.
Referenced by GlobalSearch::Molecule::hasUnitCell().
minimumImage()
Vector3 GlobalSearch::UnitCell::minimumImage (const Vector3 & cart) const inline
Find the minimum image of a Cartesian vector cart. A minimum image has all fractional coordinates between -0.5 and 0.5
Parameters
cart The Cartesian (Angstrom) vector whose minimum image we are finding.
Returns
The minimum image of the Cartesian vector cart.
Definition at line 344 of file unitcell.h.
References minimumImageFractional(), toCartesian(), and toFractional().
Referenced by distance(), and GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
minimumImageFractional()
Vector3 GlobalSearch::UnitCell::minimumImageFractional (const Vector3 & frac) static
Find the minimum fractional image of a fractional vector frac. A minimum image has all fractional coordinates between -0.5 and 0.5.
Parameters
frac The fractional vector whose minimum image we are finding.
Returns
The minimum image of the fractional vector frac.
Definition at line 57 of file unitcell.cpp.
Referenced by minimumImage().
operator=()
UnitCell & GlobalSearch::UnitCell::operator= (UnitCell && other) inline noexcept
Move assignment operator. Unfortunately, we must define it ourselves for it to be noexcept because Eigen::Matrix does not have a noexcept move assignment operator.
Definition at line 308 of file unitcell.h.
setAVector()
void GlobalSearch::UnitCell::setAVector (const Vector3 & v) inline
Set the A vector.
Parameters
v The vector with which to set A.
Definition at line 133 of file unitcell.h.
Referenced by setCellVectors().
setBVector()
void GlobalSearch::UnitCell::setBVector (const Vector3 & v) inline
Set the B vector.
Parameters
v The vector with which to set B.
Definition at line 140 of file unitcell.h.
Referenced by setCellVectors().
setCellMatrix()
void GlobalSearch::UnitCell::setCellMatrix (const Matrix3 & mat) inline
Set the cell matrix as row vectors.
Parameters
mat The 3x3 cell matrix to be set in row vector form.
Definition at line 112 of file unitcell.h.
Referenced by GlobalSearch::Structure::readCurrentStructureInfo(), GlobalSearch::Structure::updateAndAddToHistory(), and GlobalSearch::Structure::updateAndSkipHistory().
setCellParameters()
void GlobalSearch::UnitCell::setCellParameters (double a, double b, double c, double alpha, double beta, double gamma)
This uses cell parameters to create the cell matrix. The A vector will lie along the x-axis. The B vector will lie in the positive y region of the x-y plane. The C vector will then be constrained.
Parameters
a The length (Angstroms) of vector A.
b The length (Angstroms) of vector B.
c The length (Angstroms) of vector C.
alpha The angle (degrees) between vectors B and C.
beta The angle (degrees) between vectors A and C.
gamma The angle (degrees) between vectors A and B.
Definition at line 19 of file unitcell.cpp.
Referenced by UnitCell().
setCellVectors()
void GlobalSearch::UnitCell::setCellVectors (const Vector3 & a, const Vector3 & b, const Vector3 & c) inline
Set the cell vectors - a, b, and c.
Parameters
a The A vector.
b The B vector.
c The C vector.
Definition at line 316 of file unitcell.h.
References setAVector(), setBVector(), and setCVector().
setCVector()
void GlobalSearch::UnitCell::setCVector (const Vector3 & v) inline
Set the C vector.
Parameters
v The vector with which to set C.
Definition at line 147 of file unitcell.h.
Referenced by setCellVectors().
toCartesian()
Vector3 GlobalSearch::UnitCell::toCartesian (const Vector3 & frac) const inline
Converts the frac vector into a Cartesian vector.
Parameters
cart The fractional vector to be converted.
Returns
The Cartesian (Angstrom) vector.
Definition at line 329 of file unitcell.h.
Referenced by GlobalSearch::Structure::addAtomRandomly(), minimumImage(), GlobalSearch::CastepFormat::read(), GlobalSearch::PwscfFormat::read(), and wrapCartesian().
toFractional()
Vector3 GlobalSearch::UnitCell::toFractional (const Vector3 & cart) const inline
Converts the Cartesian vector into a fractional vector.
Parameters
cart The Cartesian vector (Angstroms) to be converted.
Returns
The vector with fractional units.
Definition at line 334 of file unitcell.h.
Referenced by minimumImage(), and wrapCartesian().
volume()
double GlobalSearch::UnitCell::volume () const inline
Definition at line 324 of file unitcell.h.
wrapCartesian()
Vector3 GlobalSearch::UnitCell::wrapCartesian (const Vector3 & cart) const inline
Wrap Cartesian coordinates to be within the unit cell.
Parameters
cart The Cartesian (Angstrom) coordinates to be wrapped.
Returns
The wrapped Cartesian coordinates.
Definition at line 339 of file unitcell.h.
References toCartesian(), toFractional(), and wrapFractional().
wrapFractional()
Vector3 GlobalSearch::UnitCell::wrapFractional (const Vector3 & frac) const
Wrap fractional coordinates to be within the unit cell.
Parameters
frac The fractional coordinates to be wrapped.
Returns
The wrapped fractional coordinates.
Definition at line 44 of file unitcell.cpp.
Referenced by wrapCartesian().
The documentation for this class was generated from the following files:
src/globalsearch/structures/unitcell.h
src/globalsearch/structures/unitcell.cpp