XtalOpt - API:GlobalSearch::AbstractDialog Class Reference
GlobalSearch::AbstractDialog Class Reference abstract
A basic dialog that is preconfigured for use with GlobalSearch.
#include <globalsearch/ui/abstractdialog.h>
Public Slots
virtual void disconnectGUI ()
virtual void lockGUI ()
virtual void updateGUI ()
virtual void writeSettings (const QString &filename="")
Signals
void tabsDisconnectGUI ()
void tabsLockGUI ()
void tabsWriteSettings (const QString &filename)
void tabsReadSettings (const QString &filename)
void tabsUpdateGUI ()
void moleculeChanged (GlobalSearch::Structure *)
void newLog (const QString &str)
void sig_updateStatus (int, int, int)
void sig_startProgressUpdate (const QString &, int, int)
void sig_stopProgressUpdate ()
void sig_updateProgressMinimum (int)
void sig_updateProgressMaximum (int)
void sig_updateProgressValue (int)
void sig_updateProgressLabel (const QString &)
void sig_repaintProgressBar ()
void sig_errorBox (const QString &)
void sig_messageBox (const QString &)
Public Member Functions
AbstractDialog (QWidget *parent=0, Qt::WindowFlags f=Qt::Window)
void initialize ()
virtual ~AbstractDialog () override
OptBase * getOptBase ()
virtual void readSettings (const QString &filename="")
virtual void saveSession ()=0
void updateStatus (int opt, int run, int fail)
void newDebug (const QString &s)
void newWarning (const QString &s)
void newError (const QString &s)
void newMessage (const QString &s)
void errorBox (const QString &s)
void messageBox (const QString &s)
Progressbar functions
These functions are used to display and control a progress notification system for log processes.
void startProgressUpdate (const QString &text, int min, int max)
void stopProgressUpdate ()
void updateProgressMinimum (int min)
void updateProgressMaximum (int max)
void updateProgressValue (int val)
void updateProgressLabel (const QString &text)
void repaintProgressBar ()
Protected Slots
virtual void startSearch ()=0
virtual void resumeSession ()
void updateStatus_ (int, int, int)
void startProgressUpdate_ (const QString &, int, int)
void stopProgressUpdate_ ()
void updateProgressMinimum_ (int)
void updateProgressMaximum_ (int)
void updateProgressValue_ (int)
void updateProgressLabel_ (const QString &)
void repaintProgressBar_ ()
void errorBox_ (const QString &s)
void messageBox_ (const QString &s)
Protected Member Functions
virtual void resumeSession_ (const QString &filename)
Protected Attributes
OptBase * m_opt
bool m_ownsOptBase
GlobalSearch::Molecule * m_molecule
QMutex * progMutex
QTimer * progTimer
QPushButton * ui_push_begin
QPushButton * ui_push_save
QPushButton * ui_push_resume
QPushButton * ui_push_hide
QLabel * ui_label_opt
QLabel * ui_label_run
QLabel * ui_label_fail
QLabel * ui_label_prog
QProgressBar * ui_progbar
QTabWidget * ui_tabs
Detailed Description
A basic dialog that is preconfigured for use with GlobalSearch.
Author
David C. Lonie
AbstractDialog is set up for use with an OptBase class. See the accompanying .ui file for a QtDesigner template.
To properly use this class, modify abstractdialog.ui in Qt Designer without changing the names of any existing elements. Do not add tabs, this will be done later programmatically.
Include a block like this in the derived class's constructor to setup the UI:
  // Initialize UI
  ui.setupUi(this);
  ui_push_begin   = ui.push_begin;
  ui_push_save    = ui.push_save;
  ui_push_resume  = ui.push_resume;
  ui_label_opt    = ui.label_opt;
  ui_label_run    = ui.label_run;
  ui_label_fail   = ui.label_fail;
  ui_label_prog   = ui.label_prog;
  ui_progbar      = ui.progbar;
  ui_tabs         = ui.tabs;
  // Tabs: be sure to include and define in derived header.
  // Initialize tabs (modify as needed)
  m_tab_init     = new TabInit(this, m_opt);
  m_tab_edit     = new TabEdit(this, m_opt);
  m_tab_opt      = new TabOpt(this, m_opt);
  m_tab_sys      = new TabSys(this, m_opt);
  m_tab_progress = new TabProgress(this, m_opt);
  m_tab_plot     = new TabPlot(this, m_opt);
  m_tab_log      = new TabLog(this, m_opt);
  // Populate tab widget (modify as needed)
  ui.tabs->clear();
  ui.tabs->addTab(m_tab_init->getTabWidget(),       tr("Cell &Initialization"));
  ui.tabs->addTab(m_tab_edit->getTabWidget(),     tr("Optimization
&Templates"));
  ui.tabs->addTab(m_tab_opt->getTabWidget(),      tr("&Optimization Settings"));
  ui.tabs->addTab(m_tab_sys->getTabWidget(),      tr("&System Settings"));
  ui.tabs->addTab(m_tab_progress->getTabWidget(), tr("&Progress"));
  ui.tabs->addTab(m_tab_plot->getTabWidget(),     tr("&Plot"));
  ui.tabs->addTab(m_tab_log->getTabWidget(),      tr("&Log"));
  // Select the first tab by default
  ui.tabs->setCurrentIndex(0);
  // Hide the progress bar/label
  ui.label_prog->setVisible(false);
  ui.progbar->setVisible(false);
It is also essential to call initialize() at the end of the derived constructor.
Definition at line 93 of file abstractdialog.h.
Constructor & Destructor Documentation
AbstractDialog()
GlobalSearch::AbstractDialog::AbstractDialog (QWidget * parent = 0, Qt::WindowFlags f = Qt::Window) explicit
Constructor.
When deriving, be sure to call initialize() after initializing m_opt and ui.
See also
initialize
Parameters
parent Parent object
f Window flags
Definition at line 40 of file abstractdialog.cpp.
References progMutex, and progTimer.
~AbstractDialog()
GlobalSearch::AbstractDialog::~AbstractDialog () override virtual
 Destructor. Deletes m_opt.
 Consider calling something along the lines of
  if (m_opt->saveOnExit) {
    m_opt->tracker()->lockForRead();
    writeSettings();
    saveSession();
    m_opt->tracker()->unlock();
  }
in the derived destructor.
Definition at line 114 of file abstractdialog.cpp.
References m_opt, and m_ownsOptBase.
Member Function Documentation
disconnectGUI
void GlobalSearch::AbstractDialog::disconnectGUI () virtual slot
Call this to disable GUI updates. Useful when benchmarking non-interactively.
Note
This call is passed on to all tabs.
Definition at line 120 of file abstractdialog.cpp.
References m_opt, sig_updateStatus(), tabsDisconnectGUI(), updateGUI(), and updateStatus_().
errorBox()
void GlobalSearch::AbstractDialog::errorBox (const QString & s) inline
Displays an error box with the indicated message. This function will block the GUI thread until user clicks "Ok".
Note
Do not use this function, but instead send call OptBase::error
Parameters
s Error message.
Definition at line 337 of file abstractdialog.h.
References sig_errorBox().
Referenced by newError().
errorBox_
void GlobalSearch::AbstractDialog::errorBox_ (const QString & s) protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
errorBox
getOptBase()
OptBase * GlobalSearch::AbstractDialog::getOptBase () inline
Returns
The associated OptBase derived class.
Definition at line 135 of file abstractdialog.h.
References m_opt.
initialize()
void GlobalSearch::AbstractDialog::initialize ()
Connect m_opt and the ui to the dialog. Call this in the derived class's constructor after initializing m_opt and the private ui_* member variables.
Definition at line 50 of file abstractdialog.cpp.
References lockGUI(), m_opt, messageBox_(), newDebug(), newError(), newMessage(), newWarning(), progTimer, GlobalSearch::OptBase::queue(), readSettings(), repaintProgressBar_(), resumeSession(), saveSession(), sig_messageBox(), sig_repaintProgressBar(), sig_startProgressUpdate(), sig_stopProgressUpdate(), sig_updateProgressLabel(), sig_updateProgressMaximum(), sig_updateProgressMinimum(), sig_updateProgressValue(), sig_updateStatus(), startProgressUpdate_(), startSearch(), stopProgressUpdate_(), tabsReadSettings(), tabsWriteSettings(), ui_label_prog, ui_progbar, ui_push_begin, ui_push_hide, ui_push_resume, ui_push_save, ui_tabs, updateGUI(), updateProgressLabel_(), updateProgressMaximum_(), updateProgressMinimum_(), updateProgressValue_(), updateStatus(), and updateStatus_().
lockGUI
void GlobalSearch::AbstractDialog::lockGUI () virtual slot
Called when the search session starts to disable GUI components that should only be modified during initialization.
Note
This call is passed on to all tabs.
Definition at line 129 of file abstractdialog.cpp.
References tabsLockGUI(), ui_push_begin, ui_push_resume, and ui_push_save.
Referenced by initialize().
messageBox()
void GlobalSearch::AbstractDialog::messageBox (const QString & s) inline
Displays a message box with the indicated message. This function will block the GUI thread until user clicks "Ok".
Note
Do not use this function, but instead send call OptBase::message
Parameters
s message.
Definition at line 348 of file abstractdialog.h.
References sig_messageBox().
Referenced by newMessage().
messageBox_
void GlobalSearch::AbstractDialog::messageBox_ (const QString & s) protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
messageBox
Referenced by initialize().
moleculeChanged
void GlobalSearch::AbstractDialog::moleculeChanged (GlobalSearch::Structure *) signal
Emitted to change/update the molecule displayed in the Avogadro main window.
newDebug()
void GlobalSearch::AbstractDialog::newDebug (const QString & s) inline
Called by OptBase::debug and sends a message to the log tab.
Note
Do not use this function, but instead send call OptBase::debug
Parameters
s The debugging message.
Definition at line 286 of file abstractdialog.h.
References newLog().
Referenced by initialize().
newError()
void GlobalSearch::AbstractDialog::newError (const QString & s) inline
Called by OptBase::error. Sends a message to the log tab and calls errorBox.
Note
Do not use this function, but instead send call OptBase::error
Parameters
s The error message.
Definition at line 307 of file abstractdialog.h.
References errorBox(), and newLog().
Referenced by initialize().
newLog
void GlobalSearch::AbstractDialog::newLog (const QString & str) signal
Emitted when there is a new log message ready.
See also
OptBase::debug
OptBase::warning
OptBase::error
Parameters
str Log message
Referenced by newDebug(), newError(), newMessage(), and newWarning().
newMessage()
void GlobalSearch::AbstractDialog::newMessage (const QString & s) inline
Called by OptBase::message. Sends a message to the log tab and calls messageBox.
Note
Do not use this function, but instead send call OptBase::message
Parameters
s The message.
Definition at line 322 of file abstractdialog.h.
References messageBox(), and newLog().
Referenced by initialize().
newWarning()
void GlobalSearch::AbstractDialog::newWarning (const QString & s) inline
Called by OptBase::warning and sends a message to the log tab.
Note
Do not use this function, but instead send call OptBase::warning
Parameters
s The warning message.
Definition at line 296 of file abstractdialog.h.
References newLog().
Referenced by initialize().
readSettings()
virtual void GlobalSearch::AbstractDialog::readSettings (const QString & filename = "") inline virtual
Read persistant settings or resume information. If the filename is omitted, settings are read from the configuration file. Otherwise, they are read from the provided file.
Note
This call is passed on to all tabs.
Parameters
filename Optional filename to holding resume information
Definition at line 180 of file abstractdialog.h.
References tabsReadSettings().
Referenced by initialize().
repaintProgressBar()
void GlobalSearch::AbstractDialog::repaintProgressBar () inline
Forces a redraw of the progress bar.
Note
This shouldn't need to be called, as it is handled automatically.
Definition at line 275 of file abstractdialog.h.
References sig_repaintProgressBar().
Referenced by startProgressUpdate_(), stopProgressUpdate_(), updateProgressLabel_(), updateProgressMaximum_(), updateProgressMinimum_(), and updateProgressValue_().
repaintProgressBar_
void GlobalSearch::AbstractDialog::repaintProgressBar_ () protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
repaintProgressBar
Definition at line 236 of file abstractdialog.cpp.
References ui_label_prog, and ui_progbar.
Referenced by initialize().
resumeSession
void GlobalSearch::AbstractDialog::resumeSession () protected virtual slot
Prompt user for a resume file and then call resumeSession_ in a background thread.
Definition at line 148 of file abstractdialog.cpp.
References GlobalSearch::OptBase::filePath, m_opt, and resumeSession_().
Referenced by initialize().
resumeSession_()
void GlobalSearch::AbstractDialog::resumeSession_ (const QString & filename) protected virtual
Resumes the session in file filename.
Definition at line 159 of file abstractdialog.cpp.
References GlobalSearch::Tracker::deleteAllStructures(), GlobalSearch::OptBase::emitReadOnlySessionStarted(), GlobalSearch::OptBase::emitSessionStarted(), GlobalSearch::OptBase::emitStartingSession(), GlobalSearch::OptBase::isStarting, GlobalSearch::OptBase::load(), GlobalSearch::Tracker::lockForWrite(), m_opt, GlobalSearch::OptBase::readOnly, startProgressUpdate(), stopProgressUpdate(), GlobalSearch::OptBase::tracker(), and GlobalSearch::Tracker::unlock().
Referenced by resumeSession().
saveSession()
virtual void GlobalSearch::AbstractDialog::saveSession () pure virtual
 Saves resume information to a state file in OptBase::filePath.
 This should look something like:
void DerivedDialog::saveSession() {
  // Notify if this was user requested.
  if (m_opt->savePending) {
    return;
  }
  bool notify = false;
  if (sender() == ui_push_save) {
    notify = true;
  }
  m_opt->savePending = true;
  QtConcurrent::run(m_opt, &DerivedOptBase::save, QString(""), notify);
}
Referenced by initialize().
sig_errorBox
void GlobalSearch::AbstractDialog::sig_errorBox (const QString &) signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
errorBox
Referenced by errorBox().
sig_messageBox
void GlobalSearch::AbstractDialog::sig_messageBox (const QString &) signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
messageBox
Referenced by initialize(), and messageBox().
sig_repaintProgressBar
void GlobalSearch::AbstractDialog::sig_repaintProgressBar () signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
repaintProgressBar
Referenced by initialize(), and repaintProgressBar().
sig_startProgressUpdate
void GlobalSearch::AbstractDialog::sig_startProgressUpdate (const QString & , int , int) signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
startProgressUpdate
Referenced by initialize(), and startProgressUpdate().
sig_stopProgressUpdate
void GlobalSearch::AbstractDialog::sig_stopProgressUpdate () signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
stopProgressUpdate
Referenced by initialize(), and stopProgressUpdate().
sig_updateProgressLabel
void GlobalSearch::AbstractDialog::sig_updateProgressLabel (const QString &) signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateProgressLabel
Referenced by initialize(), and updateProgressLabel().
sig_updateProgressMaximum
void GlobalSearch::AbstractDialog::sig_updateProgressMaximum (int) signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateProgressMaximum
Referenced by initialize(), and updateProgressMaximum().
sig_updateProgressMinimum
void GlobalSearch::AbstractDialog::sig_updateProgressMinimum (int) signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateProgressMinimum
Referenced by initialize(), and updateProgressMinimum().
sig_updateProgressValue
void GlobalSearch::AbstractDialog::sig_updateProgressValue (int) signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateProgressValue
Referenced by initialize(), and updateProgressValue().
sig_updateStatus
void GlobalSearch::AbstractDialog::sig_updateStatus (int , int , int) signal
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateStatus
Referenced by disconnectGUI(), initialize(), and updateStatus().
startProgressUpdate()
void GlobalSearch::AbstractDialog::startProgressUpdate (const QString & text, int min, int max) inline
Show the progressbar and initialize a status update.
Only one progress update may run at a time.
Parameters
text Label text describing the operation
min Minimum progress value
max Maximum progress value
Definition at line 235 of file abstractdialog.h.
References sig_startProgressUpdate().
Referenced by resumeSession_(), and GlobalSearch::OptBase::save().
startProgressUpdate_
void GlobalSearch::AbstractDialog::startProgressUpdate_ (const QString & text, int min, int max) protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
startProgressUpdate
Definition at line 188 of file abstractdialog.cpp.
References progTimer, repaintProgressBar(), ui_label_prog, and ui_progbar.
Referenced by initialize().
startSearch
virtual void GlobalSearch::AbstractDialog::startSearch () protected pure virtual slot
 Begin the search. Suggested form for derived class:
void DerivedDialog::startSearch() {
  QtConcurrent::run(m_opt, &DerivedOptBase::startSearch);
}
Referenced by initialize().
stopProgressUpdate()
void GlobalSearch::AbstractDialog::stopProgressUpdate () inline
Reset and hide progress bar and label. Also frees the associated mutex, allowing other processes to use it.
Definition at line 244 of file abstractdialog.h.
References sig_stopProgressUpdate().
Referenced by resumeSession_(), and GlobalSearch::OptBase::save().
stopProgressUpdate_
void GlobalSearch::AbstractDialog::stopProgressUpdate_ () protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
stopProgressUpdate
Definition at line 201 of file abstractdialog.cpp.
References progTimer, repaintProgressBar(), ui_label_prog, and ui_progbar.
Referenced by initialize().
tabsDisconnectGUI
void GlobalSearch::AbstractDialog::tabsDisconnectGUI () signal
Emitted when tabs should run their disconnectGUI function
Referenced by disconnectGUI().
tabsLockGUI
void GlobalSearch::AbstractDialog::tabsLockGUI () signal
Emitted when tabs should run their lockGUI function
Referenced by lockGUI().
tabsReadSettings
void GlobalSearch::AbstractDialog::tabsReadSettings (const QString & filename) signal
Emitted when tabs should run their lockGUI function
Parameters
filename Optional state file to read from
See also
readSettings
Referenced by initialize(), and readSettings().
tabsUpdateGUI
void GlobalSearch::AbstractDialog::tabsUpdateGUI () signal
Emitted when tabs should run their lockGUI function
Referenced by updateGUI().
tabsWriteSettings
void GlobalSearch::AbstractDialog::tabsWriteSettings (const QString & filename) signal
Emitted when tabs should run their writeSettings function
Parameters
filename Optional state file to write to
See also
writeSettings
Referenced by initialize(), and writeSettings().
updateGUI
void GlobalSearch::AbstractDialog::updateGUI () virtual slot
Refresh the GUI from data stored in m_opt.
Note
This call is passed on to all tabs.
Definition at line 138 of file abstractdialog.cpp.
References GlobalSearch::OptBase::description, GlobalSearch::OptBase::getIDString(), GlobalSearch::OptBase::host, m_opt, GlobalSearch::OptBase::readOnly, and tabsUpdateGUI().
Referenced by disconnectGUI(), and initialize().
updateProgressLabel()
void GlobalSearch::AbstractDialog::updateProgressLabel (const QString & text) inline
Parameters
text The text for the progress label.
Definition at line 264 of file abstractdialog.h.
References sig_updateProgressLabel().
Referenced by GlobalSearch::OptBase::save().
updateProgressLabel_
void GlobalSearch::AbstractDialog::updateProgressLabel_ (const QString & text) protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateProgressLabel
Definition at line 230 of file abstractdialog.cpp.
References repaintProgressBar(), and ui_label_prog.
Referenced by initialize().
updateProgressMaximum()
void GlobalSearch::AbstractDialog::updateProgressMaximum (int max) inline
Parameters
max The maximum value for the progress bar.
Definition at line 254 of file abstractdialog.h.
References sig_updateProgressMaximum().
updateProgressMaximum_
void GlobalSearch::AbstractDialog::updateProgressMaximum_ (int max) protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateProgressMaximum
Definition at line 218 of file abstractdialog.cpp.
References repaintProgressBar(), and ui_progbar.
Referenced by initialize().
updateProgressMinimum()
void GlobalSearch::AbstractDialog::updateProgressMinimum (int min) inline
Parameters
min The minimum value for the progress bar.
Definition at line 249 of file abstractdialog.h.
References sig_updateProgressMinimum().
updateProgressMinimum_
void GlobalSearch::AbstractDialog::updateProgressMinimum_ (int min) protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateProgressMinimum
Definition at line 212 of file abstractdialog.cpp.
References repaintProgressBar(), and ui_progbar.
Referenced by initialize().
updateProgressValue()
void GlobalSearch::AbstractDialog::updateProgressValue (int val) inline
Parameters
val The current value for the progress bar.
Definition at line 259 of file abstractdialog.h.
References sig_updateProgressValue().
updateProgressValue_
void GlobalSearch::AbstractDialog::updateProgressValue_ (int val) protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateProgressValue
Definition at line 224 of file abstractdialog.cpp.
References repaintProgressBar(), and ui_progbar.
Referenced by initialize().
updateStatus()
void GlobalSearch::AbstractDialog::updateStatus (int opt, int run, int fail) inline
Update the GUI with how many Structures are optimized, running, or failing.
Parameters
opt Number of optimized structures
run Number of running structures
fail Number of failing structures
Definition at line 214 of file abstractdialog.h.
References sig_updateStatus().
Referenced by initialize().
updateStatus_
void GlobalSearch::AbstractDialog::updateStatus_ (int opt, int run, int fail) protected slot
Hidden call. Ensures that the GUI is modified from the appropriate thread.
See also
updateStatus
Definition at line 181 of file abstractdialog.cpp.
References ui_label_fail, ui_label_opt, and ui_label_run.
Referenced by disconnectGUI(), and initialize().
writeSettings
virtual void GlobalSearch::AbstractDialog::writeSettings (const QString & filename = "") inline virtual slot
Write persistant settings or resume information. If the filename is omitted, settings are written to the configuration file. Otherwise, they are written to the provided file.
Note
This call is passed on to all tabs.
Parameters
filename Optional filename to hold resume information
Definition at line 167 of file abstractdialog.h.
References tabsWriteSettings().
Referenced by GlobalSearch::OptBase::save().
Member Data Documentation
m_molecule
GlobalSearch::Molecule* GlobalSearch::AbstractDialog::m_molecule protected
The molecule object that is selected.
Definition at line 571 of file abstractdialog.h.
m_opt
OptBase* GlobalSearch::AbstractDialog::m_opt protected
Cached pointer to the associated OptBase object.
Definition at line 561 of file abstractdialog.h.
Referenced by disconnectGUI(), getOptBase(), initialize(), resumeSession(), resumeSession_(), updateGUI(), and ~AbstractDialog().
m_ownsOptBase
bool GlobalSearch::AbstractDialog::m_ownsOptBase protected
Whether or not to delete the Optbase object upon destruction.
Definition at line 566 of file abstractdialog.h.
Referenced by ~AbstractDialog().
progMutex
QMutex* GlobalSearch::AbstractDialog::progMutex protected
Mutex governing progress bar usage.
Definition at line 576 of file abstractdialog.h.
Referenced by AbstractDialog().
progTimer
QTimer* GlobalSearch::AbstractDialog::progTimer protected
Timer to automatically refresh the progress bar.
Definition at line 581 of file abstractdialog.h.
Referenced by AbstractDialog(), initialize(), startProgressUpdate_(), and stopProgressUpdate_().
ui_label_fail
QLabel* GlobalSearch::AbstractDialog::ui_label_fail protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 630 of file abstractdialog.h.
Referenced by updateStatus_().
ui_label_opt
QLabel* GlobalSearch::AbstractDialog::ui_label_opt protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 616 of file abstractdialog.h.
Referenced by updateStatus_().
ui_label_prog
QLabel* GlobalSearch::AbstractDialog::ui_label_prog protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 637 of file abstractdialog.h.
Referenced by initialize(), repaintProgressBar_(), startProgressUpdate_(), stopProgressUpdate_(), and updateProgressLabel_().
ui_label_run
QLabel* GlobalSearch::AbstractDialog::ui_label_run protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 623 of file abstractdialog.h.
Referenced by updateStatus_().
ui_progbar
QProgressBar* GlobalSearch::AbstractDialog::ui_progbar protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 644 of file abstractdialog.h.
Referenced by initialize(), repaintProgressBar_(), startProgressUpdate_(), stopProgressUpdate_(), updateProgressMaximum_(), updateProgressMinimum_(), and updateProgressValue_().
ui_push_begin
QPushButton* GlobalSearch::AbstractDialog::ui_push_begin protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 588 of file abstractdialog.h.
Referenced by initialize(), and lockGUI().
ui_push_hide
QPushButton* GlobalSearch::AbstractDialog::ui_push_hide protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 609 of file abstractdialog.h.
Referenced by initialize().
ui_push_resume
QPushButton* GlobalSearch::AbstractDialog::ui_push_resume protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 602 of file abstractdialog.h.
Referenced by initialize(), and lockGUI().
ui_push_save
QPushButton* GlobalSearch::AbstractDialog::ui_push_save protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 595 of file abstractdialog.h.
Referenced by initialize(), and lockGUI().
ui_tabs
QTabWidget* GlobalSearch::AbstractDialog::ui_tabs protected
Pointer to GUI element. Do not use in derived class code.
Note
This must be set up in the derived-constructor. See class description.
Definition at line 651 of file abstractdialog.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/globalsearch/ui/abstractdialog.h
src/globalsearch/ui/abstractdialog.cpp