XtalOpt - API:GlobalSearch::OptBase Class Reference
GlobalSearch::OptBase Class Reference abstract
The OptBase class stores variables and helper functions for global searches.
#include <globalsearch/optbase.h>
Public Types
enum FeatureType { FT_Min = 0 , FT_Max , FT_Fil , FT_Har }
enum FailActions { FA_DoNothing = 0 , FA_KillIt , FA_Randomize , FA_NewOffspring }
enum TemplateType { TT_QueueInterface = 0 , TT_Optimizer , TT_Unknown }
Public Slots
virtual void reset ()
virtual bool startSearch ()=0
virtual void generateNewStructure ()
Signals
void doneWithFeatures (Structure *s)
void doneWithHardness (Structure *s)
void startingSession ()
void sessionStarted ()
void readOnlySessionStarted ()
void dialogSet ()
void queueInterfaceChanged (const std::string &qiName)
void optimizerChanged (const std::string &optName)
void debugStatement (const QString &s)
void warningStatement (const QString &s)
void errorStatement (const QString &s)
void messageStatement (const QString &s)
void needBoolean (const QString &message, bool *ok)
void needPassword (const QString &message, QString *newPassword, bool *ok)
void refreshAllStructureInfo ()
Public Member Functions
OptBase (AbstractDialog *parent=nullptr)
virtual ~OptBase () override
QString getIDString ()
virtual Structure * replaceWithRandom (Structure *s, const QString &reason="")
virtual Structure * replaceWithOffspring (Structure *s, const QString &reason="")
virtual bool checkLimits ()=0
virtual bool checkStepOptimizedStructure (Structure *s, QString *err=NULL)
virtual void readRuntimeOptions ()=0
void calculateHardness (Structure *s)
void startHardnessResubmissionThread ()
void resubmitUnfinishedHardnessCalcs ()
virtual bool save (QString filename="", bool notify=false)
virtual bool load (const QString &filename, const bool forceReadOnly=false)
virtual QString interpretTemplate (const QString &templateString, Structure *structure)
virtual QString getTemplateKeywordHelp ()
void setDialog (AbstractDialog *d)
AbstractDialog * dialog ()
Tracker * tracker ()
QueueManager * queue ()
virtual std::unique_ptr< QueueInterface > createQueueInterface (const std::string &queueName)
virtual std::unique_ptr< Optimizer > createOptimizer (const std::string &optName)
QueueInterface * queueInterface (int optStep) const
int queueInterfaceIndex (const QueueInterface *qi) const
Optimizer * optimizer (int optStep) const
int optimizerIndex (const Optimizer *optimizer) const
SSHManager * ssh ()
bool usingGUI ()
void setUsingGUI (bool b)
bool molecularMode ()
void setQueueRefreshInterval (int i)
int queueRefreshInterval () const
void setCleanRemoteOnStop (bool b)
bool cleanRemoteOnStop () const
void calculateFeatures (Structure *s)
void startFeatureCalculations (Structure *s)
void finishFeatureCalculations (Structure *s)
void performTheExit (int dealy=0)
void setFeaturesNum (int i)
Multi-objective functions for the run.
void setFeaturesOpt (FeatureType f)
void setFeaturesExe (QString f)
void setFeaturesOut (QString f)
void setFeaturesWgt (double f)
int getFeaturesNum () const
FeatureType getFeaturesOpt (int i) const
QString getFeaturesExe (int i) const
QString getFeaturesOut (int i) const
double getFeaturesWgt (int i) const
void resetFeatures ()
void featureListAdd (QString f)
QString featureListGet (int i)
void featureListClear ()
void featureListRemove (int i)
int featureListSize ()
void debug (const QString &s)
void warning (const QString &s)
void error (const QString &s)
void message (const QString &s)
void emitSessionStarted ()
void emitReadOnlySessionStarted ()
void emitStartingSession ()
void setIsStartingTrue ()
void setIsStartingFalse ()
void setReadOnlyTrue ()
void setReadOnlyFalse ()
size_t getNumOptSteps () const
void clearOptSteps ()
void appendOptStep ()
void insertOptStep (size_t optStep)
void removeOptStep (size_t optStep)
void setQueueInterface (size_t optStep, const std::string &qiName)
std::string getQueueInterfaceTemplate (size_t optStep, const std::string &name) const
void setQueueInterfaceTemplate (size_t optStep, const std::string &name, const std::string &temp)
void setOptimizer (size_t optStep, const std::string &optName)
std::string getOptimizerTemplate (size_t optStep, const std::string &name) const
void setOptimizerTemplate (size_t optStep, const std::string &name, const std::string &temp)
TemplateType getTemplateType (size_t optStep, const std::string &name) const
std::string getTemplate (size_t optStep, const std::string &name) const
void setTemplate (size_t optStep, const std::string &name, const std::string &temp)
void readQueueInterfaceTemplatesFromSettings (size_t optStep, const std::string &filename)
void readOptimizerTemplatesFromSettings (size_t optStep, const std::string &filename)
void readTemplatesFromSettings (size_t optStep, const std::string &filename)
void readAllTemplatesFromSettings (const std::string &filename)
void writeQueueInterfaceTemplatesToSettings (size_t optStep, const std::string &filename)
void writeOptimizerTemplatesToSettings (size_t optStep, const std::string &filename)
void writeTemplatesToSettings (size_t optStep, const std::string &filename)
void writeAllTemplatesToSettings (const std::string &filename)
void readUserValuesFromSettings (const std::string &filename="")
void writeUserValuesToSettings (const std::string &filename="")
std::string getUser1 ()
std::string getUser2 ()
std::string getUser3 ()
std::string getUser4 ()
void setUser1 (const std::string &s)
void setUser2 (const std::string &s)
void setUser3 (const std::string &s)
void setUser4 (const std::string &s)
bool isReadyToSearch (QString &err) const
bool anyRemoteQueueInterfaces () const
void promptForBoolean (const QString &message, bool *ok=0)
void promptForPassword (const QString &message, QString *newPassword, bool *ok=0)
void setClipboard (const QString &text) const
bool cancelJobAfterTime () const
double hoursForCancelJobAfterTime () const
Static Public Member Functions
static QList< QPair< Structure *, double > > getProbabilityList (const QList< Structure * > &structures, size_t popSize, double hardnessWeight, int features_num=0, QList< double > features_wgt={}, QList< FeatureType > features_opt={})
Public Attributes
bool limitRunningJobs
Whether to impose the running job limit.
uint runningJobLimit
Number of concurrent jobs allowed.
uint contStructs
Number of continuous structures generated.
int cutoff
How many structures to produce before halting search. -1 for no limit.
bool testingMode
Whether to run benchmarking tests.
uint test_nRunsStart
Starting run number for benchmark.
uint test_nRunsEnd
Ending run number for benchmark.
uint test_nStructs
Number of Structures per run when benchmarking.
uint failLimit
FailActions failAction
QString filePath
Local directory to work in.
QString description
Terse description of current search.
QString host
Host name or IP address of remote PBS server.
int port
Port on remote PBS server used for SSH communication.
QString username
Username for ssh login on remote PBS server.
QString rempath
QMutex * stateFileMutex
std::mutex saveMutex
A mutex for saving.
bool isStarting
True if a session is starting or being loaded.
bool readOnly
Whether readOnly mode is enabled (e.g. no connection to server)
bool m_softExit
Quit once maximum number of structures are generated (cli mode only)
bool m_hardExit
bool m_localQueue
To allow for slurm job submission in a local run.
bool m_featuresReDo
Should a redo for structure dismissed by filtration feature be considered?
bool m_calculateFeatures
Perform feature calculations in a multi-objective search.
bool m_logErrorDirs
Log error directories?
std::atomic< bool > m_calculateHardness
Calculate hardness using Aflow machine learning? (Requires internet)
std::atomic< double > m_hardnessFitnessWeight
What is the weight of the hardness fitness?
std::shared_ptr< QNetworkAccessManager > m_networkAccessManager
Only one QNetworkAccessManager is needed for a whole program.
std::unique_ptr< AflowML > m_aflowML
For performing Aflow ML calculations.
std::unordered_map< size_t, Structure * > m_pendingHardnessCalculations
A map of the AflowML indicies to their pending hardness calculations.
bool m_cancelJobAfterTime = false
double m_hoursForCancelJobAfterTime = 100.0
Protected Types
typedef std::vector< std::map< std::string, std::string > > fileTemplateType
Protected Slots
void _startHardnessResubmissionThread ()
void finishHardnessCalculation (size_t ind)
void _finishHardnessCalculation (size_t ind)
Protected Member Functions
void interpretKeyword_base (QString &keyword, Structure *structure)
Hidden call to interpretKeyword.
QString getTemplateKeywordHelp_base ()
Hidden call to getTemplateKeywordHelp.
Protected Attributes
int m_features_num
Multi-objective parameters for the run.
QStringList m_features_exe
QList< FeatureType > m_features_opt
QList< double > m_features_wgt
QStringList m_features_out
QStringList m_features_lst
QString m_idString
SSHManager * m_ssh
AbstractDialog * m_dialog
Tracker * m_tracker
QThread * m_queueThread
Thread to run the QueueManager.
QueueManager * m_queue
int m_numOptSteps
std::vector< std::unique_ptr< QueueInterface > > m_queueInterfaceAtOptStep
Queue interfaces for particular opt steps.
std::vector< std::unique_ptr< Optimizer > > m_optimizerAtOptStep
Optimizer for particular opt steps.
fileTemplateType m_queueInterfaceTemplates
fileTemplateType m_optimizerTemplates
std::string m_user1
std::string m_user2
std::string m_user3
std::string m_user4
unsigned int m_schemaVersion
Current version of save/resume schema.
bool m_usingGUI
int m_queueRefreshInterval
The queue refresh interval for remote queue interfaces.
bool m_cleanRemoteOnStop
Whether or not to clean remote directories after completion.
Detailed Description
The OptBase class stores variables and helper functions for global searches.
Author
David C. Lonie
OptBase is the main class in libglobalsearch. It contains the variables that define a search, as well as handling structure generation. This class ties all others together.
Definition at line 123 of file optbase.h.
Member Typedef Documentation
fileTemplateType
typedef std::vector<std::map<std::string, std::string> > GlobalSearch::OptBase::fileTemplateType protected
A vector of templates for each opt step. Each vector element is a map of the template name to its value.
Definition at line 1343 of file optbase.h.
Member Enumeration Documentation
FailActions
enum GlobalSearch::OptBase::FailActions
Actions to take when a structure has failed optimization too many times.
See also
OptBase::failAction
OptBase::failLimit
Enumerator
FA_DoNothing
Do nothing; keep submitting for optimization.
FA_KillIt
Kill the structure.
FA_Randomize
Replace the failing structure with a new random one.
FA_NewOffspring
Replace with a new offspring structure.
Definition at line 162 of file optbase.h.
FeatureType
enum GlobalSearch::OptBase::FeatureType
Types of the features in a multi-objective run
Definition at line 143 of file optbase.h.
TemplateType
enum GlobalSearch::OptBase::TemplateType
An enumeration for the various template types.
Enumerator
TT_QueueInterface
A queue interface template.
TT_Optimizer
An optimizer template.
TT_Unknown
Unknown template type.
Definition at line 177 of file optbase.h.
Constructor & Destructor Documentation
OptBase()
GlobalSearch::OptBase::OptBase (AbstractDialog * parent = nullptr) explicit
Constructor
Parameters
parent Dialog window of GUI.
Definition at line 63 of file optbase.cpp.
References calculateFeatures(), calculateHardness(), finishHardnessCalculation(), m_aflowML, m_queue, m_queueThread, m_tracker, needBoolean(), needPassword(), GlobalSearch::Tracker::newStructureAdded(), promptForBoolean(), promptForPassword(), readOnlySessionStarted(), GlobalSearch::QueueManager::readyForFeatureCalculations(), save(), sessionStarted(), setIsStartingFalse(), setIsStartingTrue(), startingSession(), and GlobalSearch::QueueManager::structureUpdated().
~OptBase()
GlobalSearch::OptBase::~OptBase () override virtual
Destructor
Definition at line 112 of file optbase.cpp.
References m_queue, m_queueThread, and m_tracker.
Member Function Documentation
_finishHardnessCalculation
void GlobalSearch::OptBase::_finishHardnessCalculation (size_t ind) protected slot
Same as above except runs in the current thread.
Definition at line 744 of file optbase.cpp.
References GlobalSearch::Tracker::contains(), doneWithHardness(), GlobalSearch::Structure::getGeneration(), GlobalSearch::Structure::getIDNumber(), GlobalSearch::Structure::lock(), m_aflowML, m_pendingHardnessCalculations, m_tracker, GlobalSearch::Tracker::rwLock(), GlobalSearch::Structure::setBulkModulus(), GlobalSearch::Structure::setShearModulus(), and GlobalSearch::Structure::setVickersHardness().
Referenced by finishHardnessCalculation().
_startHardnessResubmissionThread
void GlobalSearch::OptBase::_startHardnessResubmissionThread () protected slot
Resubmit incomplete hardness calculations every 10 minutes if m_calculateHardness is true (runs in the current thread).
Definition at line 687 of file optbase.cpp.
References _startHardnessResubmissionThread(), m_calculateHardness, and resubmitUnfinishedHardnessCalcs().
Referenced by _startHardnessResubmissionThread(), and startHardnessResubmissionThread().
anyRemoteQueueInterfaces()
bool GlobalSearch::OptBase::anyRemoteQueueInterfaces () const
Do we have any remote queue interfaces?
Returns
True if we do. False if we do not.
Definition at line 1669 of file optbase.cpp.
References GlobalSearch::QueueInterface::getIDString(), getNumOptSteps(), and queueInterface().
appendOptStep()
void GlobalSearch::OptBase::appendOptStep ()
Append an opt step to the current list of opt steps. If the list of opt steps is not empty, it will set the new opt step to be the same as the previous opt step. If the list of opt steps is empty, then the optimizer and queue interface will be set to nullptr, and the template maps will be empty.
Definition at line 1207 of file optbase.cpp.
References createOptimizer(), createQueueInterface(), m_numOptSteps, m_optimizerAtOptStep, and m_queueInterfaceAtOptStep.
Referenced by GlobalSearch::AbstractEditTab::appendOptStep(), insertOptStep(), and readAllTemplatesFromSettings().
calculateFeatures()
void GlobalSearch::OptBase::calculateFeatures (Structure * s)
Wrapper for calculating the features for multi-objective run
Parameters
s The structure whose features is to be calculated.
Definition at line 466 of file optbase.cpp.
References m_calculateFeatures, and startFeatureCalculations().
Referenced by OptBase().
calculateHardness()
void GlobalSearch::OptBase::calculateHardness (Structure * s)
Use Aflow machine learning to calculate the hardness of structure
Parameters
s. Note that
s will not be updated immediately, but it will be updated with the bulk modulus, shear modulus, and hardness when it receives the data back from the aflow servers.
s The structure whose hardness is to be calculated.
Definition at line 712 of file optbase.cpp.
References GlobalSearch::Structure::getGeneration(), GlobalSearch::Structure::getIDNumber(), m_aflowML, m_calculateHardness, and m_pendingHardnessCalculations.
Referenced by OptBase(), and resubmitUnfinishedHardnessCalcs().
cancelJobAfterTime()
bool GlobalSearch::OptBase::cancelJobAfterTime () const inline
Returns
Whether or not we are to cancel a job after a given amount of time.
Definition at line 1244 of file optbase.h.
References m_cancelJobAfterTime.
checkLimits()
virtual bool GlobalSearch::OptBase::checkLimits () pure virtual
Before starting an optimization, this function will check the parameters of the search to ensure that they are within a reasonable range.
Returns
True if the search parameters are valid, false otherwise.
checkStepOptimizedStructure()
virtual bool GlobalSearch::OptBase::checkStepOptimizedStructure (Structure * s, QString * err = NULL) inline virtual
Perform any post-optimization checks that need to be performed when a structure enters the Structure::StepOptimized state.
Parameters
s Structure to check
err If non-NULL, will be overwritten with an explaination of why the check failed.
Returns
True if structure passes, false otherwise.
Definition at line 242 of file optbase.h.
cleanRemoteOnStop()
bool GlobalSearch::OptBase::cleanRemoteOnStop () const inline
Get whether or not to clean remote directories when a job finishes.
Definition at line 516 of file optbase.h.
References m_cleanRemoteOnStop.
clearOptSteps()
void GlobalSearch::OptBase::clearOptSteps ()
Clear all optimization steps.
Definition at line 1198 of file optbase.cpp.
References m_numOptSteps, m_optimizerAtOptStep, and m_queueInterfaceAtOptStep.
createOptimizer()
std::unique_ptr< Optimizer > GlobalSearch::OptBase::createOptimizer (const std::string & optName) virtual
Create an optimizer with a given name.
Override this function in derived classes to change the allowed optimizers.
Parameters
optName The name of the optimizer.
Returns
A unique_ptr rvalue with the optimizer pointer stored in it. Contains a null pointer if optName is invalid.
Definition at line 1151 of file optbase.cpp.
Referenced by appendOptStep(), insertOptStep(), and setOptimizer().
createQueueInterface()
std::unique_ptr< QueueInterface > GlobalSearch::OptBase::createQueueInterface (const std::string & queueName) virtual
Create a queue interface with a given name.
Override this function in derived classes to change the allowed queue interfaces.
Parameters
queueName The name of the queue interface.
Returns
A unique_ptr rvalue with the queue interface pointer stored in it. Contains a null pointer if queueName is invalid.
Definition at line 1143 of file optbase.cpp.
Referenced by appendOptStep(), insertOptStep(), and setQueueInterface().
debug()
void GlobalSearch::OptBase::debug (const QString & s)
Prints a debug message to the terminal and emits debugStatement
Parameters
s The debug statement.
See also
debug
debugStatement
warning
warningStatement
error
errorStatement
Definition at line 1822 of file optbase.cpp.
References debugStatement().
debugStatement
void GlobalSearch::OptBase::debugStatement (const QString & s) signal
Emitted when debug(const QString&) is called.
Parameters
s The debugging statement.
See also
debug
debugStatement
warning
warningStatement
error
errorStatement
Referenced by debug().
dialog()
AbstractDialog * GlobalSearch::OptBase::dialog () inline
Returns
A pointer to the main dialog..
Definition at line 403 of file optbase.h.
References m_dialog.
Referenced by GlobalSearch::Optimizer::dialog(), GlobalSearch::LocalQueueInterface::dialog(), promptForBoolean(), and promptForPassword().
dialogSet
void GlobalSearch::OptBase::dialogSet () signal
Emitted when the dialog is set.
Referenced by setDialog().
doneWithFeatures
void GlobalSearch::OptBase::doneWithFeatures (Structure * s) signal
Emitted when feature calculations for the structure are finished.
Parameters
s Structure
Referenced by finishFeatureCalculations(), and startFeatureCalculations().
doneWithHardness
void GlobalSearch::OptBase::doneWithHardness (Structure * s) signal
Emitted when aflow-hardness calculation for the structure is finished.
Parameters
s Structure
Referenced by _finishHardnessCalculation().
emitReadOnlySessionStarted()
void GlobalSearch::OptBase::emitReadOnlySessionStarted () inline
Emits the readOnlySessionStarted signal.
See also
sessionStarted
emitSessionStarted
readOnlySessionStarted
startingSession
emitStartingSession
Definition at line 875 of file optbase.h.
References readOnlySessionStarted().
Referenced by GlobalSearch::AbstractDialog::resumeSession_().
emitSessionStarted()
void GlobalSearch::OptBase::emitSessionStarted () inline
Emits the sessionStarted signal.
See also
sessionStarted
readOnlySessionStarted
emitReadOnlySessionStarted
startingSession
emitStartingSession
Definition at line 865 of file optbase.h.
References sessionStarted().
Referenced by GlobalSearch::AbstractDialog::resumeSession_().
emitStartingSession()
void GlobalSearch::OptBase::emitStartingSession () inline
Emits the startingSession signal.
See also
sessionStarted
emitSessionStarted
startingSession
emitStartingSession
Definition at line 884 of file optbase.h.
References startingSession().
Referenced by GlobalSearch::AbstractDialog::resumeSession_().
error()
void GlobalSearch::OptBase::error (const QString & s)
Prints a error message to the terminal and emits errorStatement
Parameters
s The error statement.
See also
debug
debugStatement
warning
warningStatement
error
errorStatement
Definition at line 1828 of file optbase.cpp.
References errorStatement().
Referenced by finishFeatureCalculations(), save(), startFeatureCalculations(), and GlobalSearch::LocalQueueInterface::writeFiles().
errorStatement
void GlobalSearch::OptBase::errorStatement (const QString & s) signal
Emitted when error(const QString&) is called.
Parameters
s The error statement.
See also
debug
debugStatement
warning
warningStatement
error
errorStatement
Referenced by error().
featureListAdd()
void GlobalSearch::OptBase::featureListAdd (QString f) inline
Feature list-related: this holds a list of all feature-related entries with the cli input format, i.e., "opt_type script_name filename weight"
Definition at line 642 of file optbase.h.
featureListClear()
void GlobalSearch::OptBase::featureListClear () inline
Definition at line 644 of file optbase.h.
featureListGet()
QString GlobalSearch::OptBase::featureListGet (int i) inline
Definition at line 643 of file optbase.h.
featureListRemove()
void GlobalSearch::OptBase::featureListRemove (int i) inline
Definition at line 645 of file optbase.h.
featureListSize()
int GlobalSearch::OptBase::featureListSize () inline
Definition at line 646 of file optbase.h.
finishFeatureCalculations()
void GlobalSearch::OptBase::finishFeatureCalculations (Structure * s)
Finalizes the multi-objective run for a structure by waiting for output files to appear, transferring output files (if they're on a remote server) and processing them, updating structure info, and signal the finished job.
Parameters
s The structure whose features is to be calculated.
Definition at line 564 of file optbase.cpp.
References GlobalSearch::QueueInterface::checkIfFileExists(), GlobalSearch::QueueInterface::copyAFileRemoteToLocal(), doneWithFeatures(), error(), GlobalSearch::Structure::fileName(), GlobalSearch::Structure::FS_Dismiss, GlobalSearch::Structure::FS_Fail, GlobalSearch::Structure::FS_Retain, GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::QueueInterface::getIDString(), GlobalSearch::Structure::getIDString(), GlobalSearch::Structure::getRempath(), GlobalSearch::Structure::lock(), queueInterface(), and queueRefreshInterval().
Referenced by startFeatureCalculations().
finishHardnessCalculation
void GlobalSearch::OptBase::finishHardnessCalculation (size_t ind) protected slot
This should be called when the aflow calculation is completed for
Parameters
ind. It will obtain the data from Aflow and set the data to the structure. It will run in a separate thread.
ind The AflowML index to be updated.
Definition at line 804 of file optbase.cpp.
References _finishHardnessCalculation().
Referenced by OptBase().
generateNewStructure
virtual void GlobalSearch::OptBase::generateNewStructure () inline virtual slot
Called when the QueueManager requests more Structures.
See also
QueueManager
Definition at line 811 of file optbase.h.
getFeaturesExe()
QString GlobalSearch::OptBase::getFeaturesExe (int i) const inline
Definition at line 634 of file optbase.h.
getFeaturesNum()
int GlobalSearch::OptBase::getFeaturesNum () const inline
Definition at line 632 of file optbase.h.
getFeaturesOpt()
FeatureType GlobalSearch::OptBase::getFeaturesOpt (int i) const inline
Definition at line 633 of file optbase.h.
getFeaturesOut()
QString GlobalSearch::OptBase::getFeaturesOut (int i) const inline
Definition at line 635 of file optbase.h.
getFeaturesWgt()
double GlobalSearch::OptBase::getFeaturesWgt (int i) const inline
Definition at line 636 of file optbase.h.
getIDString()
QString GlobalSearch::OptBase::getIDString () inline
Returns
An ID string that uniquely identifies this OptBase.
Definition at line 190 of file optbase.h.
References m_idString.
Referenced by insertOptStep(), GlobalSearch::AbstractEditTab::loadScheme(), readAllTemplatesFromSettings(), GlobalSearch::Optimizer::readDataFromSettings(), readOptimizerTemplatesFromSettings(), readQueueInterfaceTemplatesFromSettings(), readUserValuesFromSettings(), save(), GlobalSearch::AbstractEditTab::saveScheme(), GlobalSearch::AbstractDialog::updateGUI(), writeAllTemplatesToSettings(), GlobalSearch::Optimizer::writeDataToSettings(), writeOptimizerTemplatesToSettings(), writeQueueInterfaceTemplatesToSettings(), and writeUserValuesToSettings().
getNumOptSteps()
size_t GlobalSearch::OptBase::getNumOptSteps () const inline
Get the number of optimization steps for our search.
Returns
The number of optimization steps for our search.
Definition at line 915 of file optbase.h.
References m_numOptSteps.
Referenced by anyRemoteQueueInterfaces(), GlobalSearch::AbstractEditTab::appendOptStep(), isReadyToSearch(), optimizer(), GlobalSearch::AbstractEditTab::populateOptStepList(), queueInterface(), readAllTemplatesFromSettings(), GlobalSearch::AbstractEditTab::removeCurrentOptStep(), save(), GlobalSearch::AbstractEditTab::saveCurrentTemplate(), GlobalSearch::AbstractEditTab::updateEditWidget(), and writeAllTemplatesToSettings().
getOptimizerTemplate()
std::string GlobalSearch::OptBase::getOptimizerTemplate (size_t optStep, const std::string & name) const
Get an optimizer template for a particular opt step and a particular file name.
Parameters
optStep The optimization step for which to get the template.
name The name of the file for which to get the template.
Returns
The optimization template. Returns an empty string if optStep or name are invalid.
Definition at line 1344 of file optbase.cpp.
References m_numOptSteps.
Referenced by getTemplate(), and writeOptimizerTemplatesToSettings().
getProbabilityList()
QList< QPair< Structure *, double > > GlobalSearch::OptBase::getProbabilityList (const QList< Structure * > & structures, size_t popSize, double hardnessWeight, int features_num = 0, QList< double > features_wgt = {}, QList< FeatureType > features_opt = {}) static
Generate a sorted, trimmed, cumulative probability list for selecting a structure.
The probability of a crystal being selected is as follows:
pi = N [ 1 - w (Hmax - Hi) / (Hmax - Hmin) - (1 - w) (Ei - Emin) / (Emax - Emin) ]
where H is the hardness, E is the enthalpy per formula unit, w is the fractional weight of the hardness (between 0.0 and 1.0), and N is a normalization constant.
If w is 0, then the probability selection will be based entirely upon enthalpy (lower enthalpy is more likely to be selected).
If w is 1, then the pobability selection will be based entirely upon hardness (higher hardness is more likely to be selected).
If w is anywhere between 0 and 1, the probability is based upon a combination of enthalpy and hardness, where low enthalpy is favored and high hardness is favored. A value closer to 0 puts more importance on low enthalpy, and a value closer to 1 puts more importance on high hardness.
This function's arguments are adjusted to allow for multi-objective search.
Parameters
structures The list of structures to consider (if the hardness weight is greater than 0, do not include structures whose hardness isn't set (i. e., less than 0)).
popSize The size of the population. After probabilities are generated, the low probability structures will be trimmed off until popSize is reached.
hardnessWeight w in the probability equation. This value should be between 0 and 1. 0 means hardness calculated but not used in optimization, 1 means only hardness consideration; and -1.0 is the case that no hardness calculation is performed.
features_num (Optional) The number of features introduced by the user for multi-objective optimization.
features_wgt (Optional) The weight of features introduced by the user for multi-objective optimization.
features_opt (Optional) The type of optimization (min/max) for the features introduced by the user for multi-objective optimization.
Returns
A list of pairs with a structure pointer and a double (the probability). This list will be trimmed so that it is not greater than popSize, and it will be sorted based upon probability. The probabilities will be cumulative so that the last probability is 1. To use this list, generate a random double 'r' between 0 and 1, and select the structure that is immediately larger than r. Default arguments are added for the multi-objective search which is not added to gapc part of the code.
Definition at line 293 of file optbase.cpp.
getQueueInterfaceTemplate()
std::string GlobalSearch::OptBase::getQueueInterfaceTemplate (size_t optStep, const std::string & name) const
Get a queue interface template for a particular opt step and a particular file name.
Parameters
optStep The optimization step for which to get the template.
name The name of the file for which to get the template.
Returns
The queue interface template. Returns an empty string if optStep or name are invalid.
Definition at line 1301 of file optbase.cpp.
References m_numOptSteps.
Referenced by getTemplate(), and writeQueueInterfaceTemplatesToSettings().
getTemplate()
std::string GlobalSearch::OptBase::getTemplate (size_t optStep, const std::string & name) const
A generic getTemplate() function. It uses getTemplateType() to determine the template type (either queue interface or optimizer), and then it calls getQueueInterfaceTemplate() or getOptimizerTemplate() accordingly.
Parameters
optStep The optimization step from which to obtain the template
name The name of the template to obtain
Returns
The template
Definition at line 1412 of file optbase.cpp.
References getOptimizerTemplate(), getQueueInterfaceTemplate(), getTemplateType(), TT_Optimizer, TT_QueueInterface, and TT_Unknown.
Referenced by GlobalSearch::Optimizer::getInterpretedTemplates(), and GlobalSearch::AbstractEditTab::updateEditWidget().
getTemplateKeywordHelp()
virtual QString GlobalSearch::OptBase::getTemplateKeywordHelp () inline virtual
Returns
A QString defining all known keywords.
Definition at line 386 of file optbase.h.
References getTemplateKeywordHelp_base().
Referenced by GlobalSearch::AbstractEditTab::showHelp().
getTemplateKeywordHelp_base()
QString GlobalSearch::OptBase::getTemplateKeywordHelp_base () protected
Hidden call to getTemplateKeywordHelp.
Definition at line 1105 of file optbase.cpp.
Referenced by getTemplateKeywordHelp().
getTemplateType()
OptBase::TemplateType GlobalSearch::OptBase::getTemplateType (size_t optStep, const std::string & name) const
Get the template type, either a queue interface or an optimizer. This will stop working properly if we ever have a template name that both a queue interface and an optimizer have. So far that is not the case. But this will require some re-working if that ever happens.
Parameters
optStep The optimization step to check.
name The name of the template.
Returns
An enum. Either TT_QueueInterface if it is a queue interface, or TT_Optimizer if it is an optimizer. Returns TT_Unknown if it could not be found.
Definition at line 1371 of file optbase.cpp.
References m_numOptSteps, optimizer(), queueInterface(), TT_Optimizer, TT_QueueInterface, and TT_Unknown.
Referenced by getTemplate(), and setTemplate().
getUser1()
std::string GlobalSearch::OptBase::getUser1 () inline
Returns
A user customizable string that is used in template interpretation.
Definition at line 1150 of file optbase.h.
Referenced by interpretKeyword_base(), and GlobalSearch::AbstractEditTab::updateGUI().
getUser2()
std::string GlobalSearch::OptBase::getUser2 () inline
Returns
A user customizable string that is used in template interpretation.
Definition at line 1156 of file optbase.h.
Referenced by interpretKeyword_base(), and GlobalSearch::AbstractEditTab::updateGUI().
getUser3()
std::string GlobalSearch::OptBase::getUser3 () inline
Returns
A user customizable string that is used in template interpretation.
Definition at line 1162 of file optbase.h.
Referenced by interpretKeyword_base(), and GlobalSearch::AbstractEditTab::updateGUI().
getUser4()
std::string GlobalSearch::OptBase::getUser4 () inline
Returns
A user customizable string that is used in template interpretation.
Definition at line 1168 of file optbase.h.
Referenced by interpretKeyword_base(), and GlobalSearch::AbstractEditTab::updateGUI().
hoursForCancelJobAfterTime()
double GlobalSearch::OptBase::hoursForCancelJobAfterTime () const inline
Returns
The amount of time in hours that, if exceeded, we are to cancel a job.
Definition at line 1250 of file optbase.h.
insertOptStep()
void GlobalSearch::OptBase::insertOptStep (size_t optStep)
Insert an optimization step at optStep. If this insertion is on the end of the list or the list is empty, it will call appendOptStep() instead. If the insertion is at the 0 index, the elements at the current 0 index will be copied to make the inserted element. If the insertion is at any other index, the element at the optStep - 1 index will be used to make the inserted element.
optStep The index that the new optStep will have after insertion.
Definition at line 1230 of file optbase.cpp.
References appendOptStep(), createOptimizer(), createQueueInterface(), getIDString(), m_numOptSteps, m_optimizerAtOptStep, and m_queueInterfaceAtOptStep.
interpretKeyword_base()
void GlobalSearch::OptBase::interpretKeyword_base (QString & keyword, Structure * structure) protected
Hidden call to interpretKeyword.
Definition at line 999 of file optbase.cpp.
References GlobalSearch::Structure::appendCopyFile(), description, GlobalSearch::Structure::fileName(), GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::Structure::getGeneration(), GlobalSearch::Structure::getIDNumber(), GlobalSearch::Structure::getRempath(), GlobalSearch::Structure::getSymbols(), getUser1(), getUser2(), getUser3(), and getUser4().
Referenced by interpretTemplate().
interpretTemplate()
QString GlobalSearch::OptBase::interpretTemplate (const QString & templateString, Structure * structure) virtual
Takes a template and inserts structure specific information by replacing keywords.
Parameters
templateString Template
structure Structure of interest
Returns
Interpreted template with structure information included
See also
getTemplateKeywordHelp
getTemplateKeywordHelp_base
interpretTemplate_base
Definition at line 980 of file optbase.cpp.
References interpretKeyword_base().
Referenced by GlobalSearch::Optimizer::getInterpretedTemplates().
isReadyToSearch()
bool GlobalSearch::OptBase::isReadyToSearch (QString & err) const
Are we ready to search (checks that essential variables are set and that the queue interfaces and optimizers are ready for the search).
Parameters
err The error message if we are not ready to search.
Returns
True if ready to search. False otherwise.
Definition at line 1639 of file optbase.cpp.
References filePath, getNumOptSteps(), isReadyToSearch(), optimizer(), and queueInterface().
Referenced by isReadyToSearch().
load()
virtual bool GlobalSearch::OptBase::load (const QString & filename, const bool forceReadOnly = false) inline virtual
Load a search session from the specified filename.
Parameters
filename State file to resume.
forceReadOnly Set to true to skip any prompts and load the session readonly
Returns
True is successful, false otherwise.
Definition at line 361 of file optbase.h.
Referenced by GlobalSearch::AbstractDialog::resumeSession_().
message()
void GlobalSearch::OptBase::message (const QString & s)
Prints a message to the terminal and emits messageStatement
Definition at line 1834 of file optbase.cpp.
References messageStatement().
Referenced by promptForBoolean(), and promptForPassword().
messageStatement
void GlobalSearch::OptBase::messageStatement (const QString & s) signal
Emitted when message(const QString&) is called.
Referenced by message().
molecularMode()
bool GlobalSearch::OptBase::molecularMode () inline
Old molecular unit is removed; so always return false for this function
Definition at line 491 of file optbase.h.
needBoolean
void GlobalSearch::OptBase::needBoolean (const QString & message, bool * ok) signal
Prompts user with an "Yes/No" dialog
Parameters
message Message to the user.
ok True if user accepts dialog, false if they cancel.
See also
promptForBoolean
Referenced by OptBase().
needPassword
void GlobalSearch::OptBase::needPassword (const QString & message, QString * newPassword, bool * ok) signal
Request a password from the user, used for libssh authentication.
Parameters
message Message to the user.
newPassword pointer to the QString that will hold the new password.
ok True if user accepts dialog, false if they cancel.
See also
promptForPassword
Referenced by OptBase().
optimizer()
Optimizer * GlobalSearch::OptBase::optimizer (int optStep) const
Returns
A pointer to the current Optimizer.
See also
setOptimizer
optimizerChanged
Definition at line 1178 of file optbase.cpp.
References getNumOptSteps(), and m_optimizerAtOptStep.
Referenced by GlobalSearch::AbstractEditTab::getCurrentOptimizer(), GlobalSearch::QueueInterface::getCurrentOptimizer(), GlobalSearch::Optimizer::getInterpretedTemplates(), getTemplateType(), isReadyToSearch(), optimizerIndex(), readOptimizerTemplatesFromSettings(), save(), GlobalSearch::AbstractEditTab::updateOptimizer(), GlobalSearch::QueueInterface::writeInputFiles(), and writeOptimizerTemplatesToSettings().
optimizerChanged
void GlobalSearch::OptBase::optimizerChanged (const std::string & optName) signal
Emitted when the current Optimizer changed
See also
setOptimizer
optimizer
optimizerIndex()
int GlobalSearch::OptBase::optimizerIndex (const Optimizer * optimizer) const
Returns
Get the index of the optimizer pointer or -1 if it does not exist.
Definition at line 1189 of file optbase.cpp.
References m_optimizerAtOptStep, and optimizer().
Referenced by GlobalSearch::Optimizer::readDataFromSettings(), and GlobalSearch::Optimizer::writeDataToSettings().
performTheExit()
void GlobalSearch::OptBase::performTheExit (int dealy = 0)
Performs a soft/hard exit after writing state files, closing ssh, etc.
Parameters
delay Amount of time (seconds) to wait before quitting; in case we need to make sure all files are written/copied properly, e.g., a soft_exit
Definition at line 147 of file optbase.cpp.
References GlobalSearch::QueueManager::getAllStructures(), m_dialog, m_queue, m_queueThread, m_ssh, save(), and warning().
Referenced by GlobalSearch::QueueManager::checkExit().
promptForBoolean()
void GlobalSearch::OptBase::promptForBoolean (const QString & message, bool * ok = 0)
Prompt user with a "Yes/No" dialog.
Parameters
message Message to the user.
ok True if user accepts dialog, false if they cancel.
See also
needBoolean
Definition at line 1689 of file optbase.cpp.
References dialog(), m_idString, and message().
Referenced by OptBase().
promptForPassword()
void GlobalSearch::OptBase::promptForPassword (const QString & message, QString * newPassword, bool * ok = 0)
Request a password from the user, used for libssh authentication.
Parameters
message Message to the user.
newPassword pointer to the QString that will hold the new password.
ok True if user accepts dialog, false if they cancel.
See also
needPassword
Definition at line 1678 of file optbase.cpp.
References dialog(), and message().
Referenced by OptBase().
queue()
QueueManager * GlobalSearch::OptBase::queue () inline
Returns
A pointer to the associated QueueManager.
Definition at line 413 of file optbase.h.
References m_queue.
Referenced by GlobalSearch::AbstractDialog::initialize(), readQueueInterfaceTemplatesFromSettings(), and writeQueueInterfaceTemplatesToSettings().
queueInterface()
QueueInterface * GlobalSearch::OptBase::queueInterface (int optStep) const
Returns
A pointer to the associated QueueManager.
See also
setQueueInterface
queueInterfaceChanged
Definition at line 1158 of file optbase.cpp.
References getNumOptSteps(), and m_queueInterfaceAtOptStep.
Referenced by anyRemoteQueueInterfaces(), GlobalSearch::Optimizer::checkForSuccessfulOutput(), GlobalSearch::Optimizer::checkIfOutputFileExists(), GlobalSearch::QueueManager::checkPopulation(), finishFeatureCalculations(), GlobalSearch::AbstractEditTab::getCurrentQueueInterface(), GlobalSearch::Optimizer::getInterpretedTemplates(), getTemplateType(), isReadyToSearch(), readQueueInterfaceTemplatesFromSettings(), startFeatureCalculations(), GlobalSearch::QueueManager::startJob(), GlobalSearch::QueueManager::stopJob(), GlobalSearch::Optimizer::update(), GlobalSearch::AbstractEditTab::updateQueueInterface(), and writeQueueInterfaceTemplatesToSettings().
queueInterfaceChanged
void GlobalSearch::OptBase::queueInterfaceChanged (const std::string & qiName) signal
Emitted when the current QueueInterface changes
See also
setQueueInterface
queueInterface
queueInterfaceIndex()
int GlobalSearch::OptBase::queueInterfaceIndex (const QueueInterface * qi) const
Returns
Get the index of the queue interface pointer or -1 if it does not exist.
Definition at line 1169 of file optbase.cpp.
References m_queueInterfaceAtOptStep.
queueRefreshInterval()
int GlobalSearch::OptBase::queueRefreshInterval () const inline
Get the queue refresh interval for remote jobs in seconds
Definition at line 504 of file optbase.h.
References m_queueRefreshInterval.
Referenced by finishFeatureCalculations().
readAllTemplatesFromSettings()
void GlobalSearch::OptBase::readAllTemplatesFromSettings (const std::string & filename)
Read all templates for every opt step from the settings. Also reads the number of opt steps.
Parameters
filename The name of the file to be read. If empty, the config file will be used.
Definition at line 1531 of file optbase.cpp.
References appendOptStep(), getIDString(), getNumOptSteps(), and readTemplatesFromSettings().
readOnlySessionStarted
void GlobalSearch::OptBase::readOnlySessionStarted () signal
Emitted when a read-only session finishes loading.
See also
sessionStarted
emitSessionStarted
readOnlySessionStarted
emitReadOnlySessionStarted
startingSession
emitStartingSession
Referenced by emitReadOnlySessionStarted(), and OptBase().
readOptimizerTemplatesFromSettings()
void GlobalSearch::OptBase::readOptimizerTemplatesFromSettings (size_t optStep, const std::string & filename)
Read the optimizer templates from the settings.
Parameters
optStep The optimization step to be read.
filename The filename to be read. If empty, the config file will be used.
Definition at line 1470 of file optbase.cpp.
References getIDString(), GlobalSearch::Optimizer::getIDString(), GlobalSearch::Optimizer::getTemplateFileNames(), optimizer(), GlobalSearch::Optimizer::setLocalRunCommand(), and setOptimizerTemplate().
Referenced by readTemplatesFromSettings().
readQueueInterfaceTemplatesFromSettings()
void GlobalSearch::OptBase::readQueueInterfaceTemplatesFromSettings (size_t optStep, const std::string & filename)
Read the queue interface templates from the settings.
Parameters
optStep The optimization step to be read.
filename The filename to be read. If empty, the config file will be used.
Definition at line 1446 of file optbase.cpp.
References getIDString(), queue(), queueInterface(), and setQueueInterfaceTemplate().
Referenced by readTemplatesFromSettings().
readRuntimeOptions()
virtual void GlobalSearch::OptBase::readRuntimeOptions () pure virtual
In CLI mode, read the runtime file to update options. If the runtime file is not found, this should do nothing.
Referenced by GlobalSearch::QueueManager::checkLoop().
readTemplatesFromSettings()
void GlobalSearch::OptBase::readTemplatesFromSettings (size_t optStep, const std::string & filename)
Read the queue interface and optimizer templates from the settings.
Parameters
optStep The optimization step to be read.
filename The filename to be read. If empty, the config file will be used.
Definition at line 1524 of file optbase.cpp.
References readOptimizerTemplatesFromSettings(), and readQueueInterfaceTemplatesFromSettings().
Referenced by readAllTemplatesFromSettings().
readUserValuesFromSettings()
void GlobalSearch::OptBase::readUserValuesFromSettings (const std::string & filename = "")
Parameters
filename Scheme or state file from which to load all user values (m_user[1-4])
Definition at line 1613 of file optbase.cpp.
References getIDString().
refreshAllStructureInfo
void GlobalSearch::OptBase::refreshAllStructureInfo () signal
Emitted when a major change has occurred affecting many structures, e.g. when duplicates are set/reset. It is recommended that any user-visible structure data is rebuilt from scratch when this is called.
removeOptStep()
void GlobalSearch::OptBase::removeOptStep (size_t optStep)
Remove the opt step at optStep.
optStep The optimization step to be removed.
Definition at line 1267 of file optbase.cpp.
References m_numOptSteps, m_optimizerAtOptStep, and m_queueInterfaceAtOptStep.
Referenced by GlobalSearch::AbstractEditTab::removeCurrentOptStep().
replaceWithOffspring()
virtual Structure * GlobalSearch::OptBase::replaceWithOffspring (Structure * s, const QString & reason = "") inline virtual
Replace the Structure with a new offspring. This only makes sense if the search method uses offspring (e.g. a GA). The default implementation of this method calls replaceWithRandom().
Parameters
s The Structure to be replaced. This pointer remains valid – the structure it points to will be modified.
reason Reason for replacing. This will appear in the Structure::getParents() string. (Optional)
Returns
The pointer to the structure (same as s).
Definition at line 219 of file optbase.h.
References replaceWithRandom().
replaceWithRandom()
virtual Structure * GlobalSearch::OptBase::replaceWithRandom (Structure * s, const QString & reason = "") inline virtual
Replace the Structure with an appropriate random Structure.
Parameters
s The Structure to be replaced. This pointer remains valid – the structure it points to will be modified.
reason Reason for replacing. This will appear in the Structure::getParents() string. (Optional)
Returns
The pointer to the structure (same as s).
Definition at line 202 of file optbase.h.
Referenced by replaceWithOffspring().
reset
void GlobalSearch::OptBase::reset () virtual slot
Deletes all structures from m_tracker and calls m_tracker->reset() and m_queue->reset().
Definition at line 127 of file optbase.cpp.
References GlobalSearch::Tracker::deleteAllStructures(), GlobalSearch::Tracker::lockForWrite(), m_queue, m_tracker, GlobalSearch::QueueManager::reset(), GlobalSearch::Tracker::reset(), and GlobalSearch::Tracker::unlock().
resetFeatures()
void GlobalSearch::OptBase::resetFeatures () inline
Definition at line 638 of file optbase.h.
resubmitUnfinishedHardnessCalcs()
void GlobalSearch::OptBase::resubmitUnfinishedHardnessCalcs ()
Run calculateHardness() on any structure that does not yet have vickersHardness info (i. e., vickersHardness() < 0.0).
Definition at line 729 of file optbase.cpp.
References calculateHardness(), GlobalSearch::QueueManager::getAllDuplicateStructures(), GlobalSearch::QueueManager::getAllOptimizedStructures(), GlobalSearch::QueueManager::getAllSupercellStructures(), m_calculateHardness, m_queue, m_tracker, and GlobalSearch::Tracker::rwLock().
Referenced by _startHardnessResubmissionThread().
save()
bool GlobalSearch::OptBase::save (QString filename = "", bool notify = false) virtual
Save the current search. If filename is omitted, default to m_filePath + "/[search name].state". Will only save once at a time.
Parameters
filename Filename to write to. Optional.
notify Whether to display a user-visible notification
Returns
True if successful, false otherwise.
Definition at line 810 of file optbase.cpp.
References error(), GlobalSearch::Structure::fileName(), filePath, GlobalSearch::Structure::getCurrentOptStep(), getIDString(), getNumOptSteps(), GlobalSearch::Structure::getResultsEntry(), isStarting, GlobalSearch::Tracker::list(), GlobalSearch::Structure::lock(), m_calculateHardness, m_dialog, m_idString, m_schemaVersion, m_tracker, optimizer(), readOnly, GlobalSearch::Tracker::rwLock(), GlobalSearch::Structure::setIndex(), GlobalSearch::Structure::skippedOptimization(), GlobalSearch::Structure::sortAndRankByEnthalpy(), GlobalSearch::AbstractDialog::startProgressUpdate(), stateFileMutex, GlobalSearch::AbstractDialog::stopProgressUpdate(), GlobalSearch::AbstractDialog::updateProgressLabel(), writeAllTemplatesToSettings(), GlobalSearch::Structure::writeSettings(), GlobalSearch::AbstractDialog::writeSettings(), and writeUserValuesToSettings().
Referenced by OptBase(), and performTheExit().
sessionStarted
void GlobalSearch::OptBase::sessionStarted () signal
Emitted when a session finishes starting or loading.
See also
sessionStarted
emitSessionStarted
readOnlySessionStarted
emitReadOnlySessionStarted
startingSession
emitStartingSession
Referenced by emitSessionStarted(), and OptBase().
setCleanRemoteOnStop()
void GlobalSearch::OptBase::setCleanRemoteOnStop (bool b) inline
Set whether or not to clean remote directories when a job finishes.
Whether or not to clean remote directories when a job finishes
Definition at line 511 of file optbase.h.
References m_cleanRemoteOnStop.
setClipboard()
void GlobalSearch::OptBase::setClipboard (const QString & text) const
Set the clipboard contents to text. Also sets the global mouse selection on supported systems.
Parameters
text Text to place on the clipboard
Definition at line 1711 of file optbase.cpp.
setDialog()
void GlobalSearch::OptBase::setDialog (AbstractDialog * d) inline
Set the main dialog..
Definition at line 394 of file optbase.h.
References dialogSet(), and m_dialog.
setFeaturesExe()
void GlobalSearch::OptBase::setFeaturesExe (QString f) inline
Definition at line 629 of file optbase.h.
setFeaturesNum()
void GlobalSearch::OptBase::setFeaturesNum (int i) inline
Multi-objective functions for the run.
Definition at line 627 of file optbase.h.
References m_features_num.
setFeaturesOpt()
void GlobalSearch::OptBase::setFeaturesOpt (FeatureType f) inline
Definition at line 628 of file optbase.h.
setFeaturesOut()
void GlobalSearch::OptBase::setFeaturesOut (QString f) inline
Definition at line 630 of file optbase.h.
setFeaturesWgt()
void GlobalSearch::OptBase::setFeaturesWgt (double f) inline
Definition at line 631 of file optbase.h.
setIsStartingFalse()
void GlobalSearch::OptBase::setIsStartingFalse () inline
Sets this->isStarting to false;
See also
setIsStartingTrue
Definition at line 896 of file optbase.h.
References isStarting.
Referenced by OptBase().
setIsStartingTrue()
void GlobalSearch::OptBase::setIsStartingTrue () inline
Sets this->isStarting to true;
See also
setIsStartingFalse
Definition at line 890 of file optbase.h.
References isStarting.
Referenced by OptBase().
setOptimizer()
void GlobalSearch::OptBase::setOptimizer (size_t optStep, const std::string & optName)
Update the Optimizer to the one indicated
Parameters
optStep The opt step for which to set the optimizer
optName New Optimizer to use. Does nothing if optName isn't recognized.
See also
optimizer
Definition at line 1328 of file optbase.cpp.
References createOptimizer(), m_numOptSteps, m_optimizerAtOptStep, and setOptimizerTemplate().
setOptimizerTemplate()
void GlobalSearch::OptBase::setOptimizerTemplate (size_t optStep, const std::string & name, const std::string & temp)
Set the optimizer template for a particular opt step and file name.
Parameters
optStep The optimization step for which to set the template.
name The file name for which to set the template.
temp The template to be set.
Definition at line 1360 of file optbase.cpp.
References m_numOptSteps.
Referenced by readOptimizerTemplatesFromSettings(), setOptimizer(), and setTemplate().
setQueueInterface()
void GlobalSearch::OptBase::setQueueInterface (size_t optStep, const std::string & qiName)
Update the QueueInterface to q.
Parameters
optStep The optimization step for which to set the QI.
qiName The name of the queue interface to use. Does nothing if qiName isn't in the m_queueInterfaces map.
See also
queueInterface
Definition at line 1285 of file optbase.cpp.
References createQueueInterface(), m_numOptSteps, m_queueInterfaceAtOptStep, and setQueueInterfaceTemplate().
setQueueInterfaceTemplate()
void GlobalSearch::OptBase::setQueueInterfaceTemplate (size_t optStep, const std::string & name, const std::string & temp)
Set the queue interface template for a particular opt step and file name.
Parameters
optStep The optimization step for which to set the template.
name The file name for which to set the template.
temp The template to be set.
Definition at line 1317 of file optbase.cpp.
References m_numOptSteps.
Referenced by readQueueInterfaceTemplatesFromSettings(), setQueueInterface(), and setTemplate().
setQueueRefreshInterval()
void GlobalSearch::OptBase::setQueueRefreshInterval (int i) inline
Set the refresh interval for checking remote jobs.
Parameters
i The interval in seconds
Definition at line 499 of file optbase.h.
References m_queueRefreshInterval.
setReadOnlyFalse()
void GlobalSearch::OptBase::setReadOnlyFalse () inline
Sets this->readOnly to false;
See also
setReadOnlyTrue
Definition at line 908 of file optbase.h.
References readOnly.
setReadOnlyTrue()
void GlobalSearch::OptBase::setReadOnlyTrue () inline
Sets this->readOnly to true;
See also
setReadOnlyFalse
Definition at line 902 of file optbase.h.
References readOnly.
setTemplate()
void GlobalSearch::OptBase::setTemplate (size_t optStep, const std::string & name, const std::string & temp)
A generic setTemplate() function. It uses getTemplateType() to determine the template type (either queue interface or optimizer), and then it calls setQueueInterfaceTemplate() or setOptimizerTemplate() accordingly.
Parameters
optStep The optimization step from which to set the template
name The name of the template to set
temp The template
Definition at line 1429 of file optbase.cpp.
References getTemplateType(), setOptimizerTemplate(), setQueueInterfaceTemplate(), TT_Optimizer, TT_QueueInterface, and TT_Unknown.
Referenced by GlobalSearch::AbstractEditTab::saveCurrentTemplate().
setUser1()
void GlobalSearch::OptBase::setUser1 (const std::string & s) inline
Parameters
s A user customizable string that is used in template interpretation.
Definition at line 1174 of file optbase.h.
Referenced by GlobalSearch::AbstractEditTab::updateUserValues().
setUser2()
void GlobalSearch::OptBase::setUser2 (const std::string & s) inline
Parameters
s A user customizable string that is used in template interpretation.
Definition at line 1180 of file optbase.h.
Referenced by GlobalSearch::AbstractEditTab::updateUserValues().
setUser3()
void GlobalSearch::OptBase::setUser3 (const std::string & s) inline
Parameters
s A user customizable string that is used in template interpretation.
Definition at line 1186 of file optbase.h.
Referenced by GlobalSearch::AbstractEditTab::updateUserValues().
setUser4()
void GlobalSearch::OptBase::setUser4 (const std::string & s) inline
Parameters
s A user customizable string that is used in template interpretation.
Definition at line 1192 of file optbase.h.
Referenced by GlobalSearch::AbstractEditTab::updateUserValues().
setUsingGUI()
void GlobalSearch::OptBase::setUsingGUI (bool b) inline
Are we using the GUI?
Parameters
b True if we are using the GUI. False otherwise.
Definition at line 486 of file optbase.h.
ssh()
SSHManager * GlobalSearch::OptBase::ssh () inline
Returns
A pointer to the SSHManager instance.
Definition at line 472 of file optbase.h.
References m_ssh.
startFeatureCalculations()
void GlobalSearch::OptBase::startFeatureCalculations (Structure * s)
Starts multi-objective run for structure by generating/copying relevant files, and running feature scripts
Parameters
s The structure whose features is to be calculated.
Definition at line 504 of file optbase.cpp.
References GlobalSearch::QueueInterface::copyAFileLocalToRemote(), doneWithFeatures(), error(), GlobalSearch::Structure::fileName(), finishFeatureCalculations(), GlobalSearch::Structure::FS_Fail, GlobalSearch::Structure::getCurrentOptStep(), GlobalSearch::QueueInterface::getIDString(), GlobalSearch::Structure::getIDString(), GlobalSearch::Structure::getRempath(), GlobalSearch::Structure::lock(), queueInterface(), and GlobalSearch::QueueInterface::runACommand().
Referenced by calculateFeatures().
startHardnessResubmissionThread()
void GlobalSearch::OptBase::startHardnessResubmissionThread ()
In a separate thread, resubmit incomplete hardness calculations every 10 minutes if m_calculateHardness is true.
Definition at line 676 of file optbase.cpp.
References _startHardnessResubmissionThread(), and m_calculateHardness.
startingSession
void GlobalSearch::OptBase::startingSession () signal
Emitted when a session is starting or being loaded.
See also
sessionStarted
emitSessionStarted
readOnlySessionStarted
emitReadOnlySessionStarted
startingSession
emitStartingSession
Referenced by emitStartingSession(), and OptBase().
startSearch
virtual bool GlobalSearch::OptBase::startSearch () pure virtual slot
Begin the search.
tracker()
Tracker * GlobalSearch::OptBase::tracker () inline
Returns
A pointer to the main Structure Tracker.
Definition at line 408 of file optbase.h.
References m_tracker.
Referenced by GlobalSearch::AbstractDialog::resumeSession_().
usingGUI()
bool GlobalSearch::OptBase::usingGUI () inline
Are we using the GUI?
Returns
Whether or not we are using the GUI.
Definition at line 479 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkLoop(), and GlobalSearch::QueueManager::startJob().
warning()
void GlobalSearch::OptBase::warning (const QString & s)
Prints a warning message to the terminal and emits warningStatement
Parameters
s The warning message.
See also
debug
debugStatement
warning
warningStatement
error
errorStatement
Definition at line 1816 of file optbase.cpp.
References warningStatement().
Referenced by GlobalSearch::QueueManager::checkExit(), GlobalSearch::LocalQueueInterface::getStatus(), GlobalSearch::Optimizer::load(), performTheExit(), GlobalSearch::LocalQueueInterface::runACommand(), GlobalSearch::QueueManager::startJob(), GlobalSearch::LocalQueueInterface::startJob(), and GlobalSearch::Optimizer::update().
warningStatement
void GlobalSearch::OptBase::warningStatement (const QString & s) signal
Emitted when warning(const QString&) is called.
Parameters
s The warning statement.
See also
debug
debugStatement
warning
warningStatement
error
errorStatement
Referenced by warning().
writeAllTemplatesToSettings()
void GlobalSearch::OptBase::writeAllTemplatesToSettings (const std::string & filename)
Write all templates for every opt step to the settings. Also writes the number of opt steps.
Parameters
filename The name of the file to be written to. If empty, the config file will be used.
Definition at line 1603 of file optbase.cpp.
References getIDString(), getNumOptSteps(), and writeTemplatesToSettings().
Referenced by save().
writeOptimizerTemplatesToSettings()
void GlobalSearch::OptBase::writeOptimizerTemplatesToSettings (size_t optStep, const std::string & filename)
Write the optimizer templates to the settings.
Parameters
optStep The optimization step to be written.
filename The filename to be written to. If empty, the config file will be used.
Definition at line 1569 of file optbase.cpp.
References getIDString(), GlobalSearch::Optimizer::getIDString(), getOptimizerTemplate(), GlobalSearch::Optimizer::getTemplateFileNames(), GlobalSearch::Optimizer::localRunCommand(), and optimizer().
Referenced by writeTemplatesToSettings().
writeQueueInterfaceTemplatesToSettings()
void GlobalSearch::OptBase::writeQueueInterfaceTemplatesToSettings (size_t optStep, const std::string & filename)
Write the queue interface templates to the settings.
Parameters
optStep The optimization step to be written.
filename The filename to be written to. If empty, the config file will be used.
Definition at line 1544 of file optbase.cpp.
References getIDString(), getQueueInterfaceTemplate(), queue(), and queueInterface().
Referenced by writeTemplatesToSettings().
writeTemplatesToSettings()
void GlobalSearch::OptBase::writeTemplatesToSettings (size_t optStep, const std::string & filename)
Write the queue interface and optimizer templates to the settings.
Parameters
optStep The optimization step to be written.
filename The filename to be written to. If empty, the config file will be used.
Definition at line 1596 of file optbase.cpp.
References writeOptimizerTemplatesToSettings(), and writeQueueInterfaceTemplatesToSettings().
Referenced by writeAllTemplatesToSettings().
writeUserValuesToSettings()
void GlobalSearch::OptBase::writeUserValuesToSettings (const std::string & filename = "")
Parameters
filename Scheme or state file in which to write all user values (m_user[1-4])
Definition at line 1625 of file optbase.cpp.
References getIDString().
Referenced by save().
Member Data Documentation
contStructs
uint GlobalSearch::OptBase::contStructs
Number of continuous structures generated.
Definition at line 525 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkPopulation().
cutoff
int GlobalSearch::OptBase::cutoff
How many structures to produce before halting search. -1 for no limit.
Definition at line 528 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkExit(), and GlobalSearch::QueueManager::checkPopulation().
description
QString GlobalSearch::OptBase::description
Terse description of current search.
Definition at line 556 of file optbase.h.
Referenced by interpretKeyword_base(), and GlobalSearch::AbstractDialog::updateGUI().
failAction
FailActions GlobalSearch::OptBase::failAction
What to do when a Structure exceeds failLimit
See also
OptBase::FailActions
OptBase::failLimit
Definition at line 550 of file optbase.h.
failLimit
uint GlobalSearch::OptBase::failLimit
Number of times a Structure may fail
See also
OptBase::failAction
OptBase::FailActions
Definition at line 545 of file optbase.h.
filePath
QString GlobalSearch::OptBase::filePath
Local directory to work in.
Definition at line 553 of file optbase.h.
Referenced by isReadyToSearch(), GlobalSearch::LocalQueueInterface::isReadyToSearch(), GlobalSearch::LocalQueueInterface::logErrorDirectory(), GlobalSearch::AbstractDialog::resumeSession(), and save().
host
QString GlobalSearch::OptBase::host
Host name or IP address of remote PBS server.
Definition at line 559 of file optbase.h.
Referenced by GlobalSearch::AbstractDialog::updateGUI().
isStarting
bool GlobalSearch::OptBase::isStarting
True if a session is starting or being loaded.
Definition at line 579 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkLoop(), GlobalSearch::AbstractDialog::resumeSession_(), save(), setIsStartingFalse(), setIsStartingTrue(), and GlobalSearch::QueueManager::unlockForNaming().
limitRunningJobs
bool GlobalSearch::OptBase::limitRunningJobs
Whether to impose the running job limit.
Definition at line 519 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkPopulation().
m_aflowML
std::unique_ptr<AflowML> GlobalSearch::OptBase::m_aflowML
For performing Aflow ML calculations.
Definition at line 1382 of file optbase.h.
Referenced by _finishHardnessCalculation(), calculateHardness(), and OptBase().
m_calculateFeatures
bool GlobalSearch::OptBase::m_calculateFeatures
Perform feature calculations in a multi-objective search.
Definition at line 624 of file optbase.h.
Referenced by calculateFeatures(), and GlobalSearch::QueueManager::updateStructureFeatureStatus().
m_calculateHardness
std::atomic<bool> GlobalSearch::OptBase::m_calculateHardness
Calculate hardness using Aflow machine learning? (Requires internet)
Definition at line 1373 of file optbase.h.
Referenced by _startHardnessResubmissionThread(), calculateHardness(), resubmitUnfinishedHardnessCalcs(), save(), startHardnessResubmissionThread(), and GlobalSearch::QueueManager::updateStructureFeatureStatus().
m_cancelJobAfterTime
bool GlobalSearch::OptBase::m_cancelJobAfterTime = false
Should we cancel the job if a number of hours are exceeded? This is primarily implemented because some optimizers have bugs that cause them to run forever. But also because XtalOpt will sometimes think a job is queued even though it is not.
Definition at line 1391 of file optbase.h.
Referenced by cancelJobAfterTime().
m_cleanRemoteOnStop
bool GlobalSearch::OptBase::m_cleanRemoteOnStop protected
Whether or not to clean remote directories after completion.
Definition at line 1366 of file optbase.h.
Referenced by cleanRemoteOnStop(), and setCleanRemoteOnStop().
m_dialog
AbstractDialog* GlobalSearch::OptBase::m_dialog protected
Cached pointer to the Dialog window
See also
tracker
Definition at line 1317 of file optbase.h.
Referenced by dialog(), performTheExit(), save(), and setDialog().
m_features_exe
QStringList GlobalSearch::OptBase::m_features_exe protected
Definition at line 1301 of file optbase.h.
m_features_lst
QStringList GlobalSearch::OptBase::m_features_lst protected
Definition at line 1305 of file optbase.h.
m_features_num
int GlobalSearch::OptBase::m_features_num protected
Multi-objective parameters for the run.
Definition at line 1300 of file optbase.h.
Referenced by setFeaturesNum().
m_features_opt
QList<FeatureType> GlobalSearch::OptBase::m_features_opt protected
Definition at line 1302 of file optbase.h.
m_features_out
QStringList GlobalSearch::OptBase::m_features_out protected
Definition at line 1304 of file optbase.h.
m_features_wgt
QList<double> GlobalSearch::OptBase::m_features_wgt protected
Definition at line 1303 of file optbase.h.
m_featuresReDo
bool GlobalSearch::OptBase::m_featuresReDo
Should a redo for structure dismissed by filtration feature be considered?
Definition at line 621 of file optbase.h.
m_hardExit
bool GlobalSearch::OptBase::m_hardExit
Quit immediately! This is only a runtime option in the cli mode, but won't be written to runtime file; it can be added by the user.
Definition at line 615 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkExit().
m_hardnessFitnessWeight
std::atomic<double> GlobalSearch::OptBase::m_hardnessFitnessWeight
What is the weight of the hardness fitness?
Definition at line 1376 of file optbase.h.
m_hoursForCancelJobAfterTime
double GlobalSearch::OptBase::m_hoursForCancelJobAfterTime = 100.0
Definition at line 1392 of file optbase.h.
m_idString
QString GlobalSearch::OptBase::m_idString protected
String that uniquely identifies the derived OptBase
See also
getIDString
Definition at line 1309 of file optbase.h.
Referenced by getIDString(), promptForBoolean(), and save().
m_localQueue
bool GlobalSearch::OptBase::m_localQueue
To allow for slurm job submission in a local run.
Definition at line 618 of file optbase.h.
m_logErrorDirs
bool GlobalSearch::OptBase::m_logErrorDirs
Log error directories?
Definition at line 1370 of file optbase.h.
Referenced by GlobalSearch::LocalQueueInterface::stopJob().
m_networkAccessManager
std::shared_ptr<QNetworkAccessManager> GlobalSearch::OptBase::m_networkAccessManager
Only one QNetworkAccessManager is needed for a whole program.
Definition at line 1379 of file optbase.h.
m_numOptSteps
int GlobalSearch::OptBase::m_numOptSteps protected
The number of optimization steps Do not change this number directly. Instead, call appendOptStep(), insertOptStep(), and removeOptStep().
Definition at line 1333 of file optbase.h.
Referenced by appendOptStep(), clearOptSteps(), getNumOptSteps(), getOptimizerTemplate(), getQueueInterfaceTemplate(), getTemplateType(), insertOptStep(), removeOptStep(), setOptimizer(), setOptimizerTemplate(), setQueueInterface(), and setQueueInterfaceTemplate().
m_optimizerAtOptStep
std::vector<std::unique_ptr<Optimizer> > GlobalSearch::OptBase::m_optimizerAtOptStep protected
Optimizer for particular opt steps.
Definition at line 1339 of file optbase.h.
Referenced by appendOptStep(), clearOptSteps(), insertOptStep(), optimizer(), optimizerIndex(), removeOptStep(), and setOptimizer().
m_optimizerTemplates
fileTemplateType GlobalSearch::OptBase::m_optimizerTemplates protected
Definition at line 1347 of file optbase.h.
m_pendingHardnessCalculations
std::unordered_map<size_t, Structure*> GlobalSearch::OptBase::m_pendingHardnessCalculations
A map of the AflowML indicies to their pending hardness calculations.
Definition at line 1385 of file optbase.h.
Referenced by _finishHardnessCalculation(), and calculateHardness().
m_queue
QueueManager* GlobalSearch::OptBase::m_queue protected
Cached pointer to the QueueManager
See also
queue
Definition at line 1328 of file optbase.h.
Referenced by OptBase(), performTheExit(), queue(), reset(), resubmitUnfinishedHardnessCalcs(), and ~OptBase().
m_queueInterfaceAtOptStep
std::vector<std::unique_ptr<QueueInterface> > GlobalSearch::OptBase::m_queueInterfaceAtOptStep protected
Queue interfaces for particular opt steps.
Definition at line 1336 of file optbase.h.
Referenced by appendOptStep(), clearOptSteps(), insertOptStep(), queueInterface(), queueInterfaceIndex(), removeOptStep(), and setQueueInterface().
m_queueInterfaceTemplates
fileTemplateType GlobalSearch::OptBase::m_queueInterfaceTemplates protected
Definition at line 1345 of file optbase.h.
m_queueRefreshInterval
int GlobalSearch::OptBase::m_queueRefreshInterval protected
The queue refresh interval for remote queue interfaces.
Definition at line 1363 of file optbase.h.
Referenced by queueRefreshInterval(), and setQueueRefreshInterval().
m_queueThread
QThread* GlobalSearch::OptBase::m_queueThread protected
Thread to run the QueueManager.
Definition at line 1324 of file optbase.h.
Referenced by OptBase(), performTheExit(), and ~OptBase().
m_schemaVersion
unsigned int GlobalSearch::OptBase::m_schemaVersion protected
Current version of save/resume schema.
Definition at line 1358 of file optbase.h.
Referenced by save().
m_softExit
bool GlobalSearch::OptBase::m_softExit
Quit once maximum number of structures are generated (cli mode only)
Definition at line 611 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkExit().
m_ssh
SSHManager* GlobalSearch::OptBase::m_ssh protected
Cached pointer to the SSHManager
See also
ssh
Definition at line 1313 of file optbase.h.
Referenced by performTheExit(), and ssh().
m_tracker
Tracker* GlobalSearch::OptBase::m_tracker protected
Cached pointer to the main Tracker
See also
tracker
Definition at line 1321 of file optbase.h.
Referenced by _finishHardnessCalculation(), OptBase(), reset(), resubmitUnfinishedHardnessCalcs(), save(), tracker(), and ~OptBase().
m_user1
std::string GlobalSearch::OptBase::m_user1 protected
Definition at line 1349 of file optbase.h.
m_user2
std::string GlobalSearch::OptBase::m_user2 protected
Definition at line 1349 of file optbase.h.
m_user3
std::string GlobalSearch::OptBase::m_user3 protected
Definition at line 1349 of file optbase.h.
m_user4
std::string GlobalSearch::OptBase::m_user4 protected
Definition at line 1349 of file optbase.h.
m_usingGUI
bool GlobalSearch::OptBase::m_usingGUI protected
Definition at line 1360 of file optbase.h.
port
int GlobalSearch::OptBase::port
Port on remote PBS server used for SSH communication.
Definition at line 562 of file optbase.h.
readOnly
bool GlobalSearch::OptBase::readOnly
Whether readOnly mode is enabled (e.g. no connection to server)
Definition at line 582 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkLoop(), GlobalSearch::AbstractDialog::resumeSession_(), save(), setReadOnlyFalse(), setReadOnlyTrue(), and GlobalSearch::AbstractDialog::updateGUI().
rempath
QString GlobalSearch::OptBase::rempath
Path on remote server to store files during and after optimization
Definition at line 569 of file optbase.h.
runningJobLimit
uint GlobalSearch::OptBase::runningJobLimit
Number of concurrent jobs allowed.
Definition at line 522 of file optbase.h.
saveMutex
std::mutex GlobalSearch::OptBase::saveMutex
A mutex for saving.
Definition at line 576 of file optbase.h.
stateFileMutex
QMutex* GlobalSearch::OptBase::stateFileMutex
This should be locked whenever the state file (resume file) is being written
Definition at line 573 of file optbase.h.
Referenced by save().
test_nRunsEnd
uint GlobalSearch::OptBase::test_nRunsEnd
Ending run number for benchmark.
Definition at line 537 of file optbase.h.
test_nRunsStart
uint GlobalSearch::OptBase::test_nRunsStart
Starting run number for benchmark.
Definition at line 534 of file optbase.h.
test_nStructs
uint GlobalSearch::OptBase::test_nStructs
Number of Structures per run when benchmarking.
Definition at line 540 of file optbase.h.
testingMode
bool GlobalSearch::OptBase::testingMode
Whether to run benchmarking tests.
Definition at line 531 of file optbase.h.
Referenced by GlobalSearch::QueueManager::checkPopulation().
username
QString GlobalSearch::OptBase::username
Username for ssh login on remote PBS server.
Definition at line 565 of file optbase.h.
The documentation for this class was generated from the following files:
src/globalsearch/optbase.h
src/globalsearch/optbase.cpp