XtalOpt - API:GlobalSearch::PwscfFormat Class Reference
GlobalSearch::PwscfFormat Class Reference
Static Public Member Functions
static bool read (Structure *s, const QString &filename)
Detailed Description
Definition at line 30 of file pwscfformat.h.
Member Function Documentation
read()
bool GlobalSearch::PwscfFormat::read (Structure * s, const QString & filename) static
The output we are looking for should look something like this:
Final enthalpy =     -94.4276660887 Ry
Begin final coordinates new unit-cell volume = 107.95826 a.u.^3 (15.99776 Ang^3) density = 0.31139 g/cm^3
CELL_PARAMETERS (alat= 1.00000000) 3.874174633 -0.256713398 0.047571808 0.960054464 5.090350807 0.072713918 0.694196504 1.552402373 5.434153937
ATOMIC_POSITIONS (crystal) O -0.238428760 0.078189145 0.088947201 O 0.736946363 0.004722226 0.509718838 O 0.249167697 0.541516629 0.799216961 End final coordinates
...
! total energy = -95.01479203 Ry
Definition at line 54 of file pwscfformat.cpp.
References GlobalSearch::UnitCell::cellMatrix(), GlobalSearch::UnitCell::toCartesian(), GlobalSearch::Molecule::unitCell(), and GlobalSearch::Structure::updateAndAddToHistory().
Referenced by GlobalSearch::Formats::read().
The documentation for this class was generated from the following files:
src/globalsearch/formats/pwscfformat.h
src/globalsearch/formats/pwscfformat.cpp