XtalOpt - API:GlobalSearch::AbstractEditTab Class Reference
GlobalSearch::AbstractEditTab Class Reference
Abstract class implementing a template editor.
#include <globalsearch/abstractedittab.h>
Public Slots
virtual void lockGUI () override
virtual void updateGUIQueueInterface ()
virtual void updateGUIOptimizer ()
virtual void updateGUI () override
virtual void updateEditWidget ()
virtual void showHelp ()
virtual void saveCurrentTemplate ()
virtual void populateOptStepList ()
virtual void populateTemplates ()
virtual void appendOptStep ()
virtual void removeCurrentOptStep ()
virtual int getCurrentOptStep ()
virtual Optimizer * getCurrentOptimizer ()
virtual QueueInterface * getCurrentQueueInterface ()
virtual void saveScheme ()
virtual void loadScheme ()
virtual QStringList getTemplateNames (size_t optStep)
Public Slots inherited from GlobalSearch::AbstractTab
virtual void lockGUI ()
Signals
void optimizerChanged (size_t optStep, const std::string &)
void queueInterfaceChanged (size_t optStep, const std::string &)
Signals inherited from GlobalSearch::AbstractTab
void moleculeChanged (GlobalSearch::Structure *)
void startingBackgroundProcessing ()
void finishedBackgroundProcessing ()
void initialized ()
Public Member Functions
AbstractEditTab (AbstractDialog *parent, OptBase *p)
virtual ~AbstractEditTab () override
Public Member Functions inherited from GlobalSearch::AbstractTab
AbstractTab (AbstractDialog *parent, OptBase *p)
virtual ~AbstractTab () override
QWidget * getTabWidget ()
virtual void readSettings (const QString &filename="")
virtual void writeSettings (const QString &filename="")
virtual void updateGUI ()
virtual void disconnectGUI ()
Protected Slots
virtual void initialize () override
virtual void updateUserValues ()
virtual void updateQueueInterface ()
virtual void updateOptimizer ()
virtual void configureQueueInterface ()
virtual void configureOptimizer ()
Protected Slots inherited from GlobalSearch::AbstractTab
virtual void initialize ()
void setBusyCursor ()
void clearBusyCursor ()
Protected Attributes
QStringList m_optimizers
QStringList m_queueInterfaces
QComboBox * ui_combo_queueInterfaces
Cached GUI pointer. This is set in DefaultEditTab.
QComboBox * ui_combo_optimizers
Cached GUI pointer. This is set in DefaultEditTab.
QComboBox * ui_combo_templates
Cached GUI pointer. This is set in DefaultEditTab.
QLineEdit * ui_edit_user1
Cached GUI pointer. This is set in DefaultEditTab.
QLineEdit * ui_edit_user2
Cached GUI pointer. This is set in DefaultEditTab.
QLineEdit * ui_edit_user3
Cached GUI pointer. This is set in DefaultEditTab.
QLineEdit * ui_edit_user4
Cached GUI pointer. This is set in DefaultEditTab.
QListWidget * ui_list_edit
Cached GUI pointer. This is set in DefaultEditTab.
QListWidget * ui_list_optStep
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_add
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_help
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_loadScheme
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_optimizerConfig
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_queueInterfaceConfig
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_remove
Cached GUI pointer. This is set in DefaultEditTab.
QPushButton * ui_push_saveScheme
Cached GUI pointer. This is set in DefaultEditTab.
QTextEdit * ui_edit_edit
Cached GUI pointer. This is set in DefaultEditTab.
Protected Attributes inherited from GlobalSearch::AbstractTab
QWidget * m_tab_widget
The actual widget that will be made into a tab.
AbstractDialog * m_dialog
A pointer to the parent dialog.
OptBase * m_opt
A pointer to the associated OptBase class.
bool m_isInitialized
Set to true once initialized() completes.
std::atomic< bool > m_updateGuiInProgress {false}
Used to determine if a gui update is in progress.
Detailed Description
Abstract class implementing a template editor.
Author
David C. Lonie
Definition at line 43 of file abstractedittab.h.
Constructor & Destructor Documentation
AbstractEditTab()
GlobalSearch::AbstractEditTab::AbstractEditTab (AbstractDialog * parent, OptBase * p) explicit
Constructor
Parameters
parent AbstractDialog that will use this tab
p Associated OptBase
Definition at line 37 of file abstractedittab.cpp.
~AbstractEditTab()
GlobalSearch::AbstractEditTab::~AbstractEditTab () override virtual
Destructor
Definition at line 140 of file abstractedittab.cpp.
Member Function Documentation
appendOptStep
void GlobalSearch::AbstractEditTab::appendOptStep () virtual slot
Create a new optstep at the end of the optstep list. It will initialize using the currently selected optstep's templates.
Definition at line 430 of file abstractedittab.cpp.
References GlobalSearch::OptBase::appendOptStep(), getCurrentOptStep(), GlobalSearch::OptBase::getNumOptSteps(), GlobalSearch::AbstractTab::m_opt, and populateOptStepList().
Referenced by initialize().
configureOptimizer
void GlobalSearch::AbstractEditTab::configureOptimizer () protected virtual slot
Launch the Optimizer configuration dialog.
Definition at line 284 of file abstractedittab.cpp.
References GlobalSearch::Optimizer::dialog(), and getCurrentOptimizer().
Referenced by initialize().
configureQueueInterface
void GlobalSearch::AbstractEditTab::configureQueueInterface () protected virtual slot
Launch the QueueInterface configuration dialog.
Definition at line 272 of file abstractedittab.cpp.
References GlobalSearch::QueueInterface::dialog(), and getCurrentQueueInterface().
Referenced by initialize().
getCurrentOptimizer
virtual Optimizer * GlobalSearch::AbstractEditTab::getCurrentOptimizer () inline virtual slot
Get the optimizer for the currently selected step.
Returns
The optimizer for the currently selected step.
Definition at line 132 of file abstractedittab.h.
References getCurrentOptStep(), GlobalSearch::AbstractTab::m_opt, and GlobalSearch::OptBase::optimizer().
Referenced by configureOptimizer(), getTemplateNames(), updateGUIOptimizer(), and updateOptimizer().
getCurrentOptStep
virtual int GlobalSearch::AbstractEditTab::getCurrentOptStep () inline virtual slot
Get the current opt step index.
Returns
The curent opt step index.
Definition at line 125 of file abstractedittab.h.
References ui_list_optStep.
Referenced by appendOptStep(), getCurrentOptimizer(), getCurrentQueueInterface(), populateOptStepList(), populateTemplates(), removeCurrentOptStep(), saveCurrentTemplate(), updateEditWidget(), updateOptimizer(), and updateQueueInterface().
getCurrentQueueInterface
virtual QueueInterface * GlobalSearch::AbstractEditTab::getCurrentQueueInterface () inline virtual slot
Get the queue interface for the currently selected step.
Returns
The queue interface for the currently selected step.
Definition at line 143 of file abstractedittab.h.
References getCurrentOptStep(), GlobalSearch::AbstractTab::m_opt, and GlobalSearch::OptBase::queueInterface().
Referenced by configureQueueInterface(), getTemplateNames(), updateGUIQueueInterface(), and updateQueueInterface().
getTemplateNames
QStringList GlobalSearch::AbstractEditTab::getTemplateNames (size_t optStep) virtual slot
Returns
A list of the available template names for the QueueInterface and Optimizer at a particular opt step.
Definition at line 296 of file abstractedittab.cpp.
References getCurrentOptimizer(), getCurrentQueueInterface(), GlobalSearch::Optimizer::getTemplateFileNames(), and GlobalSearch::AbstractTab::m_isInitialized.
Referenced by populateTemplates(), saveCurrentTemplate(), and updateEditWidget().
initialize
void GlobalSearch::AbstractEditTab::initialize () override protected virtual slot
Create connections and initialize GUI.
Definition at line 47 of file abstractedittab.cpp.
References appendOptStep(), configureOptimizer(), configureQueueInterface(), GlobalSearch::AbstractTab::initialize(), loadScheme(), GlobalSearch::AbstractTab::m_dialog, GlobalSearch::AbstractTab::m_opt, m_optimizers, m_queueInterfaces, optimizerChanged(), populateOptStepList(), populateTemplates(), queueInterfaceChanged(), removeCurrentOptStep(), saveCurrentTemplate(), saveScheme(), showHelp(), ui_combo_optimizers, ui_combo_queueInterfaces, ui_combo_templates, ui_edit_edit, ui_edit_user1, ui_edit_user2, ui_edit_user3, ui_edit_user4, ui_list_optStep, ui_push_add, ui_push_help, ui_push_loadScheme, ui_push_optimizerConfig, ui_push_queueInterfaceConfig, ui_push_remove, ui_push_saveScheme, updateEditWidget(), updateGUI(), updateGUIOptimizer(), updateGUIQueueInterface(), updateOptimizer(), updateQueueInterface(), and updateUserValues().
Referenced by GlobalSearch::DefaultEditTab::initialize().
loadScheme
void GlobalSearch::AbstractEditTab::loadScheme () virtual slot
Load an optimization scheme from a file. This will prompt the user for the filename.
Definition at line 477 of file abstractedittab.cpp.
References GlobalSearch::OptBase::getIDString(), GlobalSearch::AbstractTab::m_opt, and GlobalSearch::AbstractTab::readSettings().
Referenced by initialize().
lockGUI
void GlobalSearch::AbstractEditTab::lockGUI () override virtual slot
Lock GUI elements that shouldn't change once the search begins.
Definition at line 204 of file abstractedittab.cpp.
References ui_combo_optimizers, and ui_combo_queueInterfaces.
optimizerChanged
void GlobalSearch::AbstractEditTab::optimizerChanged (size_t optStep, const std::string &) signal
Emitted when the Optimizer changes.
Referenced by initialize(), and updateOptimizer().
populateOptStepList
void GlobalSearch::AbstractEditTab::populateOptStepList () virtual slot
Generate the list of optsteps.
Definition at line 406 of file abstractedittab.cpp.
References getCurrentOptStep(), GlobalSearch::OptBase::getNumOptSteps(), GlobalSearch::AbstractTab::m_isInitialized, GlobalSearch::AbstractTab::m_opt, and ui_list_optStep.
Referenced by appendOptStep(), initialize(), removeCurrentOptStep(), saveCurrentTemplate(), updateEditWidget(), and updateGUI().
populateTemplates
void GlobalSearch::AbstractEditTab::populateTemplates () virtual slot
Fill the template selection combo using the template names for the current QueueInterface and Optimizer.
Definition at line 307 of file abstractedittab.cpp.
References getCurrentOptStep(), getTemplateNames(), GlobalSearch::AbstractTab::m_isInitialized, and ui_combo_templates.
Referenced by initialize().
queueInterfaceChanged
void GlobalSearch::AbstractEditTab::queueInterfaceChanged (size_t optStep, const std::string &) signal
Emitted when the QueueInterface changes.
Referenced by initialize(), and updateQueueInterface().
removeCurrentOptStep
void GlobalSearch::AbstractEditTab::removeCurrentOptStep () virtual slot
Delete the currently selected optstep.
Definition at line 442 of file abstractedittab.cpp.
References getCurrentOptStep(), GlobalSearch::OptBase::getNumOptSteps(), GlobalSearch::AbstractTab::m_opt, populateOptStepList(), and GlobalSearch::OptBase::removeOptStep().
Referenced by initialize().
saveCurrentTemplate
void GlobalSearch::AbstractEditTab::saveCurrentTemplate () virtual slot
Save the text in the template editor to the appropriate template list.
Definition at line 371 of file abstractedittab.cpp.
References getCurrentOptStep(), GlobalSearch::OptBase::getNumOptSteps(), getTemplateNames(), GlobalSearch::AbstractTab::m_opt, populateOptStepList(), GlobalSearch::OptBase::setTemplate(), ui_combo_templates, ui_edit_edit, and ui_list_optStep.
Referenced by initialize().
saveScheme
void GlobalSearch::AbstractEditTab::saveScheme () virtual slot
Save the current optimization scheme. This will prompt for the user to specify the filename.
Definition at line 458 of file abstractedittab.cpp.
References GlobalSearch::OptBase::getIDString(), GlobalSearch::AbstractTab::m_opt, and GlobalSearch::AbstractTab::writeSettings().
Referenced by initialize().
showHelp
void GlobalSearch::AbstractEditTab::showHelp () virtual slot
Popup a message box displaying the keyword documentation.
Definition at line 210 of file abstractedittab.cpp.
References GlobalSearch::OptBase::getTemplateKeywordHelp(), GlobalSearch::AbstractTab::m_dialog, and GlobalSearch::AbstractTab::m_opt.
Referenced by initialize().
updateEditWidget
void GlobalSearch::AbstractEditTab::updateEditWidget () virtual slot
Display the currently selected template in the text editor.
Definition at line 334 of file abstractedittab.cpp.
References getCurrentOptStep(), GlobalSearch::OptBase::getNumOptSteps(), GlobalSearch::OptBase::getTemplate(), getTemplateNames(), GlobalSearch::AbstractTab::m_isInitialized, GlobalSearch::AbstractTab::m_opt, populateOptStepList(), ui_combo_templates, ui_edit_edit, ui_list_edit, and ui_list_optStep.
Referenced by initialize().
updateGUI
void GlobalSearch::AbstractEditTab::updateGUI () override virtual slot
Force a refresh of the GUI elements using the internal state.
Definition at line 191 of file abstractedittab.cpp.
References GlobalSearch::OptBase::getUser1(), GlobalSearch::OptBase::getUser2(), GlobalSearch::OptBase::getUser3(), GlobalSearch::OptBase::getUser4(), GlobalSearch::AbstractTab::m_opt, populateOptStepList(), ui_edit_user1, ui_edit_user2, ui_edit_user3, ui_edit_user4, updateGUIOptimizer(), and updateGUIQueueInterface().
Referenced by initialize().
updateGUIOptimizer
void GlobalSearch::AbstractEditTab::updateGUIOptimizer () virtual slot
Update the optimizer in the GUI.
Definition at line 171 of file abstractedittab.cpp.
References getCurrentOptimizer(), GlobalSearch::AbstractTab::m_isInitialized, m_optimizers, and ui_combo_optimizers.
Referenced by initialize(), and updateGUI().
updateGUIQueueInterface
void GlobalSearch::AbstractEditTab::updateGUIQueueInterface () virtual slot
Update the queue interface in the GUI.
Definition at line 144 of file abstractedittab.cpp.
References getCurrentQueueInterface(), GlobalSearch::AbstractTab::m_isInitialized, m_queueInterfaces, ui_combo_queueInterfaces, and ui_push_queueInterfaceConfig.
Referenced by initialize(), and updateGUI().
updateOptimizer
void GlobalSearch::AbstractEditTab::updateOptimizer () protected virtual slot
Determine the currently selected Optimizer and emit optimizerChanged if it differs from the current one.
Definition at line 250 of file abstractedittab.cpp.
References getCurrentOptimizer(), getCurrentOptStep(), GlobalSearch::Optimizer::hasDialog(), GlobalSearch::AbstractTab::m_opt, m_optimizers, GlobalSearch::OptBase::optimizer(), optimizerChanged(), ui_combo_optimizers, and ui_push_optimizerConfig.
Referenced by initialize().
updateQueueInterface
void GlobalSearch::AbstractEditTab::updateQueueInterface () protected virtual slot
Determine the currently selected QueueInterface and emit queueInterfaceChanged if it differs from the current one.
Definition at line 227 of file abstractedittab.cpp.
References getCurrentOptStep(), getCurrentQueueInterface(), GlobalSearch::QueueInterface::hasDialog(), GlobalSearch::AbstractTab::m_opt, m_queueInterfaces, GlobalSearch::OptBase::queueInterface(), queueInterfaceChanged(), ui_combo_queueInterfaces, and ui_push_queueInterfaceConfig.
Referenced by initialize().
updateUserValues
void GlobalSearch::AbstractEditTab::updateUserValues () protected virtual slot
Refresh the "userX" line edits.
Definition at line 398 of file abstractedittab.cpp.
References GlobalSearch::AbstractTab::m_opt, GlobalSearch::OptBase::setUser1(), GlobalSearch::OptBase::setUser2(), GlobalSearch::OptBase::setUser3(), GlobalSearch::OptBase::setUser4(), ui_edit_user1, ui_edit_user2, ui_edit_user3, and ui_edit_user4.
Referenced by initialize().
Member Data Documentation
m_optimizers
QStringList GlobalSearch::AbstractEditTab::m_optimizers protected
List of all optimizers. This must be filled in derived classes prior to calling initialize()
Definition at line 214 of file abstractedittab.h.
Referenced by initialize(), updateGUIOptimizer(), and updateOptimizer().
m_queueInterfaces
QStringList GlobalSearch::AbstractEditTab::m_queueInterfaces protected
List of all QueueInterfaces. This must be filled in derived classes prior to calling initialize()
Definition at line 218 of file abstractedittab.h.
Referenced by initialize(), updateGUIQueueInterface(), and updateQueueInterface().
ui_combo_optimizers
QComboBox* GlobalSearch::AbstractEditTab::ui_combo_optimizers protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 223 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), lockGUI(), updateGUIOptimizer(), and updateOptimizer().
ui_combo_queueInterfaces
QComboBox* GlobalSearch::AbstractEditTab::ui_combo_queueInterfaces protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 221 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), lockGUI(), updateGUIQueueInterface(), and updateQueueInterface().
ui_combo_templates
QComboBox* GlobalSearch::AbstractEditTab::ui_combo_templates protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 225 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), populateTemplates(), saveCurrentTemplate(), and updateEditWidget().
ui_edit_edit
QTextEdit* GlobalSearch::AbstractEditTab::ui_edit_edit protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 253 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), saveCurrentTemplate(), and updateEditWidget().
ui_edit_user1
QLineEdit* GlobalSearch::AbstractEditTab::ui_edit_user1 protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 227 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), updateGUI(), and updateUserValues().
ui_edit_user2
QLineEdit* GlobalSearch::AbstractEditTab::ui_edit_user2 protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 229 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), updateGUI(), and updateUserValues().
ui_edit_user3
QLineEdit* GlobalSearch::AbstractEditTab::ui_edit_user3 protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 231 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), updateGUI(), and updateUserValues().
ui_edit_user4
QLineEdit* GlobalSearch::AbstractEditTab::ui_edit_user4 protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 233 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), updateGUI(), and updateUserValues().
ui_list_edit
QListWidget* GlobalSearch::AbstractEditTab::ui_list_edit protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 235 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), and updateEditWidget().
ui_list_optStep
QListWidget* GlobalSearch::AbstractEditTab::ui_list_optStep protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 237 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), getCurrentOptStep(), initialize(), populateOptStepList(), saveCurrentTemplate(), and updateEditWidget().
ui_push_add
QPushButton* GlobalSearch::AbstractEditTab::ui_push_add protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 239 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), and initialize().
ui_push_help
QPushButton* GlobalSearch::AbstractEditTab::ui_push_help protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 241 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), and initialize().
ui_push_loadScheme
QPushButton* GlobalSearch::AbstractEditTab::ui_push_loadScheme protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 243 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), and initialize().
ui_push_optimizerConfig
QPushButton* GlobalSearch::AbstractEditTab::ui_push_optimizerConfig protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 245 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), and updateOptimizer().
ui_push_queueInterfaceConfig
QPushButton* GlobalSearch::AbstractEditTab::ui_push_queueInterfaceConfig protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 247 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), initialize(), updateGUIQueueInterface(), and updateQueueInterface().
ui_push_remove
QPushButton* GlobalSearch::AbstractEditTab::ui_push_remove protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 249 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), and initialize().
ui_push_saveScheme
QPushButton* GlobalSearch::AbstractEditTab::ui_push_saveScheme protected
Cached GUI pointer. This is set in DefaultEditTab.
Definition at line 251 of file abstractedittab.h.
Referenced by GlobalSearch::DefaultEditTab::DefaultEditTab(), and initialize().
The documentation for this class was generated from the following files:
src/globalsearch/ui/abstractedittab.h
src/globalsearch/ui/abstractedittab.cpp