XtalOpt - API:GlobalSearch::Atom Class Reference
GlobalSearch::Atom Class Reference
A basic atom class. Each atom has an atomic number and a position.
#include <atom.h>
Public Member Functions
Atom (unsigned short atomicNum=0, const Vector3 &pos=Vector3(0.0, 0.0, 0.0))
Atom (const Atom &other)=default
Atom (Atom &&other) noexcept
Atom & operator= (const Atom &other)=default
Atom & operator= (Atom &&other) noexcept
bool operator== (const Atom &other) const
void setAtomicNumber (unsigned short num)
void setPos (const Vector3 &pos)
unsigned short atomicNumber () const
Vector3 & pos ()
const Vector3 & pos () const
Detailed Description
A basic atom class. Each atom has an atomic number and a position.
Definition at line 27 of file atom.h.
Constructor & Destructor Documentation
Atom() [1/2]
GlobalSearch::Atom::Atom (unsigned short atomicNum = 0, const Vector3 & pos = Vector3(0.0, 0.0, 0.0)) inline explicit
Atom constructor. Default atomic number is 0. Default position is (0, 0, 0).
Parameters
atomicNum The atomic number. Default is zero.
pos The 3-dimensional Cartesian coordinates in Angstroms. Default is (0, 0, 0).
Definition at line 118 of file atom.h.
Atom() [2/2]
GlobalSearch::Atom::Atom (Atom && other) inline noexcept
Move constructor. Unfortunately, we must define it ourselves for it to be noexcept because Eigen::Matrix does not have a noexcept move constructor.
Definition at line 123 of file atom.h.
Member Function Documentation
atomicNumber()
unsigned short GlobalSearch::Atom::atomicNumber () const inline
Get the atomic number of the atom.
Returns
The atomic number of the atom.
Definition at line 87 of file atom.h.
Referenced by GlobalSearch::Structure::generateIADHistogram().
operator=()
Atom & GlobalSearch::Atom::operator= (Atom && other) inline noexcept
Move assignment operator. Unfortunately, we must define it ourselves for it to be noexcept because Eigen::Matrix does not have a noexcept move assignment operator.
Definition at line 129 of file atom.h.
operator==()
bool GlobalSearch::Atom::operator== (const Atom & other) const inline
Definition at line 138 of file atom.h.
pos() [1/2]
Vector3 & GlobalSearch::Atom::pos () inline
Get the position of the atom in 3-dimensional Cartesian coordinates in Angstroms.
Returns
The 3-dimensional Cartesian position in Angstroms.
Definition at line 95 of file atom.h.
Referenced by GlobalSearch::Structure::generateIADHistogram(), GlobalSearch::Structure::getNearestNeighborDistance(), GlobalSearch::Structure::getNeighbors(), setPos(), GlobalSearch::Molecule::wrapMoleculesToSmallestBonds(), GlobalSearch::Structure::writeCurrentStructureInfo(), and GlobalSearch::ZMatrixFormat::writeSiestaZMatrix().
pos() [2/2]
const Vector3 & GlobalSearch::Atom::pos () const inline
Get the position of the atom in 3-dimensional Cartesian coordinates in Angstroms.
Returns
The 3-dimensional Cartesian position in Angstroms.
Definition at line 103 of file atom.h.
setAtomicNumber()
void GlobalSearch::Atom::setAtomicNumber (unsigned short num) inline
Set the atomic number of the atom. It may be any number between 0 and
However, real atoms will be be between 1 and 118.
Parameters
num The atomic number.
Definition at line 73 of file atom.h.
Referenced by GlobalSearch::Structure::addAtomRandomly(), GlobalSearch::Structure::readCurrentStructureInfo(), and GlobalSearch::Structure::updateAndSkipHistory().
setPos()
void GlobalSearch::Atom::setPos (const Vector3 & pos) inline
Set the position of the atom using Cartesian coordinates in Angstroms.
Parameters
pos The 3-dimensional Cartesian coordinates in Angstroms.
Definition at line 80 of file atom.h.
References pos().
Referenced by GlobalSearch::Structure::addAtomRandomly(), GlobalSearch::Structure::readCurrentStructureInfo(), GlobalSearch::Structure::updateAndSkipHistory(), and GlobalSearch::Molecule::wrapMoleculesToSmallestBonds().
The documentation for this class was generated from the following file:
src/globalsearch/structures/atom.h