XtalOpt - API:GlobalSearch::Bond Class Reference
GlobalSearch::Bond Class Reference
A basic bond class. Just stores two atom indices and a bond order. There is potential for more to be added in the future...
#include <bond.h>
Public Member Functions
Bond (size_t ind1, size_t ind2, unsigned short bondOrder=1)
Bond (const Bond &other)=default
Bond (Bond &&other)=default
Bond & operator= (const Bond &other)=default
Bond & operator= (Bond &&other)=default
size_t first () const
size_t second () const
void swapIndices (size_t ind1, size_t ind2)
void setBondOrder (unsigned short o)
unsigned short bondOrder () const
void atomIndexRemoved (size_t atomInd)
Detailed Description
A basic bond class. Just stores two atom indices and a bond order. There is potential for more to be added in the future...
Definition at line 26 of file bond.h.
Constructor & Destructor Documentation
Bond()
GlobalSearch::Bond::Bond (size_t ind1, size_t ind2, unsigned short bondOrder = 1) inline explicit
Bond constructor. Default bond order is 1.
Parameters
ind1 The index of the first atom in the bond.
ind2 The index of the second atom in the bond.
bondOrder The bond order. Default is 1.
Definition at line 117 of file bond.h.
Member Function Documentation
atomIndexRemoved()
void GlobalSearch::Bond::atomIndexRemoved (size_t atomInd) inline
Indicate to this bond that the atom index, atomInd, has been removed, so any indices higher than this should be decremented. Because the index has been removed, all bonds to the removed atom should have already been deleted. This bond SHOULD NOT have one of its indices equal to atomInd.
Parameters
atomInd The atom index that has been removed.
Definition at line 135 of file bond.h.
Referenced by GlobalSearch::Molecule::removeAtom().
bondOrder()
unsigned short GlobalSearch::Bond::bondOrder () const inline
Get the bond order.
Returns
The bond order.
Definition at line 91 of file bond.h.
Referenced by GlobalSearch::Molecule::addMolecule().
first()
size_t GlobalSearch::Bond::first () const inline
Get the index of the first atom in the bond.
Returns
The index of the first atom in the bond.
Definition at line 58 of file bond.h.
Referenced by GlobalSearch::Molecule::addMolecule(), GlobalSearch::Molecule::areBonded(), and GlobalSearch::Molecule::isBonded().
second()
size_t GlobalSearch::Bond::second () const inline
Get the index of the second atom in the bond.
Returns
The index of the second atom in the bond.
Definition at line 65 of file bond.h.
Referenced by GlobalSearch::Molecule::addMolecule(), GlobalSearch::Molecule::areBonded(), and GlobalSearch::Molecule::isBonded().
setBondOrder()
void GlobalSearch::Bond::setBondOrder (unsigned short o) inline
Set the bond order. Should be 1, 2, 3, or 4...
Parameters
o The bond order.
Definition at line 84 of file bond.h.
swapIndices()
void GlobalSearch::Bond::swapIndices (size_t ind1, size_t ind2) inline
This function is to be used when swapping atom indices in a molecule. If this bond contains ind1 as one of it's indices, it will swap it with ind2. If this bond contains ind2 as one of it's indices, it will swap it with ind1. This function does nothing if the bond does not contain ind1 or ind2.
Parameters
ind1 The index (if it exists) to be swapped with ind2.
ind2 The index (if it exists) to be swapped with ind1.
Definition at line 122 of file bond.h.
Referenced by GlobalSearch::Molecule::swapAtoms().
The documentation for this class was generated from the following file:
src/globalsearch/structures/bond.h