XtalOpt - API:GlobalSearch::Formats Class Reference
GlobalSearch::Formats Class Reference
Static Public Member Functions
static QString detectFormat (const QString &filename)
static bool read (Structure *s, const QString &filename)
static bool read (Structure *s, const QString &filename, const QString &format)
Detailed Description
Definition at line 21 of file formats.h.
Member Function Documentation
detectFormat()
QString GlobalSearch::Formats::detectFormat (const QString & filename) static
Detect the format from the filename extension and return it as a QString. Returns an empty QString if no format was detected.
Parameters
filename The filename whose extension is to be examined.
Returns
The format. Returns an empty QString if no format was found.
Definition at line 55 of file formats.cpp.
Referenced by read().
read() [1/2]
bool GlobalSearch::Formats::read (Structure * s, const QString & filename) static
Try to detect the format and then read the structure. If it fails to detect the format, nothing will be done to s, and the return will be false.
Parameters
s The structure to be written to. Nothing will be done if the format is not found correctly.
filename The filename which is to be read and whose extension is to be examined.
Returns
True on success and false on failure.
Definition at line 71 of file formats.cpp.
References detectFormat(), and read().
Referenced by read(), and GlobalSearch::Optimizer::read().
read() [2/2]
bool GlobalSearch::Formats::read (Structure * s, const QString & filename, const QString & format) static
Attempts to read the filename with the given format, and writes the information to the Structure, s. Returns true on succes and false on failure.
Parameters
s The structure to be written to. Nothing will be done if an invalid format is given.
filename The name of the file to be read.
format The format to be used. If an invalid format is given, nothing will be done to s and false will be returned.
Returns
True on success and false on failure.
Definition at line 79 of file formats.cpp.
References GlobalSearch::CastepFormat::read(), and GlobalSearch::PwscfFormat::read().
The documentation for this class was generated from the following files:
src/globalsearch/formats/formats.h
src/globalsearch/formats/formats.cpp