XtalOpt - API:Dialog access
Dialog access
Functions
bool GlobalSearch::Optimizer::hasDialog ()
virtual QDialog * GlobalSearch::Optimizer::dialog ()
bool GlobalSearch::QueueInterface::hasDialog ()
virtual QDialog * GlobalSearch::QueueInterface::dialog ()
Public Slots
virtual QDialog * GlobalSearch::LocalQueueInterface::dialog () override
Detailed Description
Function Documentation
dialog() [1/2]
QDialog * GlobalSearch::Optimizer::dialog () virtual
Returns
The configuration dialog for this QueueInterface, if it exists, otherwise 0.
See also
hasDialog()
Definition at line 180 of file optimizer.cpp.
References GlobalSearch::OptBase::dialog(), and GlobalSearch::Optimizer::m_opt.
Referenced by GlobalSearch::AbstractEditTab::configureOptimizer().
dialog() [2/2]
virtual QDialog * GlobalSearch::QueueInterface::dialog () inline virtual
Returns
The configuration dialog for this QueueInterface, if it exists, otherwise 0.
See also
hasDialog()
Definition at line 337 of file queueinterface.h.
References GlobalSearch::QueueInterface::m_dialog.
Referenced by GlobalSearch::AbstractEditTab::configureQueueInterface().
hasDialog() [1/2]
bool GlobalSearch::Optimizer::hasDialog () inline
Returns
True if this QueueInterface has a configuration dialog.
See also
dialog()
Definition at line 307 of file optimizer.h.
Referenced by GlobalSearch::AbstractEditTab::updateOptimizer().
hasDialog() [2/2]
bool GlobalSearch::QueueInterface::hasDialog () inline
Returns
True if this QueueInterface has a configuration dialog.
See also
dialog()
Definition at line 329 of file queueinterface.h.
References GlobalSearch::QueueInterface::m_hasDialog.
Referenced by GlobalSearch::AbstractEditTab::updateQueueInterface().
Public Slots
dialog
QDialog * GlobalSearch::LocalQueueInterface::dialog () override virtual slot
Returns
The configuration dialog for this QueueInterface, if it exists, otherwise 0.
See also
hasDialog()
Definition at line 465 of file local.cpp.
References GlobalSearch::OptBase::dialog(), GlobalSearch::QueueInterface::m_dialog, and GlobalSearch::QueueInterface::m_opt.